version: '2'

services:
  mqtt:
    image: toke/mosquitto
    restart: always
    dns: 192.168.0.1
    dns_search: singularity.net
    user: '119:999'
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mqtt/config:/mqtt/config:rw
      - ./mqtt/log:/mqtt/log
      - ./mqtt/data:/mqtt/data
  postgres:
    image: library/postgres:9.6.1
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hass
      - POSTGRES_PASSWORD=automatethethings
      - POSTGRES_DB=homeassistant
  homeassistant:
    image: jawilson/homeassistant:latest
    links:
      - mqtt
      - mqtt:mqtt.singularity.net
      - postgres:database
    restart: always
    dns: 192.168.0.1
    dns_search: singularity.net
    networks:
      default:
      macvlan:
        ipv4_address: 192.168.0.60
    devices:
      - /dev/zwave
      - /dev/zigbee
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant:/config
      - ./letsencrypt/config:/etc/letsencrypt:ro
      - ./tools:/opt/tools:ro
    environment:
      - HA_LOG_LEVEL=warning
    entrypoint:
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'mqtt:1883'
      - '--'
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'database:5432'
      - '--'
      - 'python'
      - '-m'
      - 'homeassistant'
      - '--config'
      - '/config'

networks:
  default:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: 'eth1'
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
