version: '3.7'

services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    dns: 192.168.0.1
    dns_search: singularity.net
    user: '114:118'
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mqtt/log:/mosquitto/log
      - ./mqtt/data:/mosquitto/data
      - ./ssl/certs:/mosquitto/config/certs:ro
      - ./ssl/private/mqtt.singularity.net.key:/mosquitto/config/private/mqtt.singularity.net.key:ro
  database:
    image: library/postgres:9
    restart: unless-stopped
    user: '114:118'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./postgres/secrets.env
  adbd:
    image: sorccu/adb:latest
    restart: unless-stopped
    dns: 192.168.0.1
    dns_search: singularity.net
    volumes:
      - ./adb:/root/.android
    command: /root/.android/startup.sh
  homeassistant:
    image: homeassistant/home-assistant:0.113.3
    init: true
    links:
      - mqtt
      - mqtt:mqtt.singularity.net
      - database
      - adbd
    restart: unless-stopped
    user: '0:118'
    dns: 192.168.0.1
    dns_search: singularity.net
    networks:
      default:
      macvlan:
        ipv4_address: 192.168.0.60
    devices:
      - /dev/zwave
      - /dev/zigbee
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant:/config
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./tools:/opt/tools:ro
      - ./ssl/certs:/config/certs:ro
      - ./.ssh:/config/.ssh:ro
    environment:
      - HA_LOG_LEVEL=warning
      - TZ=America/New_York
    entrypoint:
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'mqtt:1883'
      - '--'
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'database:5432'
      - '--'
      - 'python'
      - '-m'
      - 'homeassistant'
      - '--config'
      - '/config'
  node-red:
    build: ./node-red
    restart: unless-stopped
    user: '114:118'
    links:
      - homeassistant
    ports:
      - 1880:1880
    volumes:
      - ./node-red/data:/data
  appdaemon:
    image: acockburn/appdaemon:latest
    restart: unless-stopped
    user: '114:118'
    links:
      - homeassistant
    ports:
      - 5051:5051
    environment:
      - HA_URL="http://homeassistant:8123"
      - DASH_URL="http://0.0.0.0:5051"
    env_file: ./appdaemon/appdaemon.env
    volumes:
      - ./appdaemon/conf:/conf
networks:
  default:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: 'enp8s0'
    ipam:
      config:
        - subnet: 192.168.0.0/24
          #gateway: 192.168.0.1
