version: '2'

services:
  openhab:
    image: peez/openhab
    restart: always
    dns: 192.168.0.1
    dns_search: singularity.net
    expose:
      - 8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./openhab:/opt/openhab/configurations
  harmony:
    image: jawilson/harmony-api:latest
    links:
      - mqtt
    restart: always
    dns: 192.168.0.1
    dns_search: singularity.net
    volumes:
      - ./harmony-api:/config:ro
      - ./tools:/opt/tools:ro
    ports:
      - 8282:8282
    entrypoint: >
      /opt/tools/wait-for-it/wait-for-it.sh -s mqtt:1883 -- npm start
  mqtt:
    image: toke/mosquitto
    restart: always
    dns: 192.168.0.1
    dns_search: singularity.net
    user: '119:999'
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mqtt/config:/mqtt/config:rw
      - ./mqtt/log:/mqtt/log
      - ./mqtt/data:/mqtt/data
  homeassistant:
    image: jawilson/homeassistant:latest
    links:
      - mqtt
      - mqtt:mqtt.singularity.net
      - openhab
    restart: always
    dns: 192.168.0.1
    dns_search: singularity.net
    networks:
      default:
      macvlan:
        ipv4_address: 192.168.0.60
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant:/config
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./tools:/opt/tools:ro
    environment:
      - HA_LOG_LEVEL=error
    entrypoint:
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'mqtt:1883'
      - '--'
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'openhab:8080'
      - '--'
      - 'python'
      - '-m'
      - 'homeassistant'
      - '--config'
      - '/config'

networks:
  default:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: 'eth1'
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
