version: '2'

services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    dns: 192.168.0.1
    dns_search: singularity.net
    user: '114:118'
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mqtt/log:/mosquitto/log
      - ./mqtt/data:/mosquitto/data
      - ./ssl/certs:/mosquitto/config/certs:ro
      - ./ssl/private/mqtt.singularity.net.key:/mosquitto/config/private/mqtt.singularity.net.key:ro
  database:
    image: library/postgres:9
    restart: unless-stopped
    user: '114:118'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=hass
      - POSTGRES_PASSWORD=automatethethings
      - POSTGRES_DB=homeassistant
  influxdb:
    image: library/influxdb
    restart: unless-stopped
    user: '114:118'
    volumes:
      - ./influxdb:/var/lib/influxdb
  homeassistant:
    image: homeassistant/home-assistant:latest
    links:
      - mqtt
      - mqtt:mqtt.singularity.net
      - database
      - influxdb
    restart: unless-stopped
    dns: 192.168.0.1
    dns_search: singularity.net
    networks:
      default:
      macvlan:
        ipv4_address: 192.168.0.60
    devices:
      - /dev/zwave
      - /dev/zigbee
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant:/config
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./tools:/opt/tools:ro
      - ./ssl/certs:/config/certs:ro
    environment:
      - HA_LOG_LEVEL=warning
    entrypoint:
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'mqtt:1883'
      - '--'
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'database:5432'
      - '--'
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'influxdb:8086'
      - '--'
      - 'python'
      - '-m'
      - 'homeassistant'
      - '--config'
      - '/config'
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    links:
      - database
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana:ro
      - ./tools:/opt/tools:ro
    environment:
      - GF_INSTALL_PLUGINS=natel-discrete-panel
    entrypoint:
      - '/opt/tools/wait-for-it/wait-for-it.sh'
      - '-s'
      - 'database:5432'
      - '--'
      - '/run.sh'

networks:
  default:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: 'enp8s0'
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
