#
# Templates
#
- platform: template
  sensors:
    apartment_feels_like:
      friendly_name: 'Feels Like'
      value_template: '{{ (0.5 * ( (states.sensor.apartment_temperatures.state|float) + 61.0 + ( ((states.sensor.apartment_temperatures.state|float) - 68.0) * 1.2 ) + ((states.sensor.apartment_humidities.state|float) * 0.094) ) )|round(2) }}'
      unit_of_measurement: '°F'


#
# Statistics
#
- platform: min_max
  name: Apartment Temperatures
  type: mean
  unique_id: min_max_apartment_temps_mean
  entity_ids:
    - sensor.apartment_thermostat_temperature
    - sensor.bathroom_temperature
    - sensor.bedroom_temperature
    - sensor.sunroom_temperature
    - sensor.ficus_temperature

- platform: min_max
  name: Min Apartment Temperature
  type: min
  unique_id: min_max_apartment_temps_min
  entity_ids:
    - sensor.apartment_thermostat_temperature
    - sensor.bathroom_temperature
    - sensor.bedroom_temperature
    - sensor.sunroom_temperature
    - sensor.ficus_temperature

- platform: min_max
  name: Max Apartment Temperature
  type: max
  unique_id: min_max_apartment_temps_max
  entity_ids:
    - sensor.apartment_thermostat_temperature
    - sensor.bathroom_temperature
    - sensor.bedroom_temperature
    - sensor.sunroom_temperature
    - sensor.ficus_temperature

- platform: min_max
  name: Sunroom Temperatures
  type: mean
  unique_id: min_max_sunroom_temps_mean
  entity_ids:
    - sensor.sunroom_temperature
    - sensor.ficus_temperature

- platform: min_max
  name: Non-Sunroom Temperatures
  type: mean
  unique_id: min_max_non_sunroom_temps_mean
  entity_ids:
    - sensor.apartment_thermostat_temperature
    - sensor.bathroom_temperature
    - sensor.bedroom_temperature

- platform: min_max
  name: Apartment Humidities
  type: mean
  unique_id: min_max_apartment_humidities_mean
  entity_ids:
    - sensor.apartment_thermostat_humidity
    - sensor.dehumidifier_humidity
    - sensor.bathroom_relative_humidity
    - sensor.bedroom_relative_humidity
    - sensor.humidifier_current_humidity
    - sensor.sunroom_relative_humidity
    - sensor.ficus_humidity

- platform: statistics
  name: Ficus Moisture (Filtered)
  entity_id: sensor.ficus_moisture
  state_characteristic: average_linear
  unique_id: stats_ficus_moisture_average_linear
  max_age:
    hours: 2

- platform: statistics
  name: Ficus Brightness (Filtered)
  entity_id: sensor.ficus_illuminance
  state_characteristic: average_linear
  unique_id: stats_ficus_brightness_average_linear
  max_age:
    hours: 2

- platform: statistics
  name: Ficus Temperature (Filtered)
  entity_id: sensor.ficus_temperature
  state_characteristic: average_linear
  unique_id: stats_ficus_temperature_average_linear
  max_age:
    hours: 2

- platform: statistics
  name: Ficus Humidity (Filtered)
  entity_id: sensor.ficus_humidity
  state_characteristic: average_linear
  unique_id: stats_ficus_humidity_average_linear
  max_age:
    hours: 2

- platform: statistics
  name: Pathos Moisture (Filtered)
  entity_id: sensor.pathos_moisture
  state_characteristic: average_linear
  unique_id: stats_pathos_moisture_average_linear
  max_age:
    hours: 2

- platform: statistics
  name: Pathos Brightness (Filtered)
  entity_id: sensor.pathos_illuminance
  state_characteristic: average_linear
  unique_id: stats_pathos_brightness_average_linear
  max_age:
    hours: 2

- platform: statistics
  name: Pathos Temperature (Filtered)
  entity_id: sensor.pathos_temperature
  state_characteristic: average_linear
  unique_id: stats_pathos_temperature_average_linear
  max_age:
    hours: 2

- platform: statistics
  name: Pathos Humidity (Filtered)
  entity_id: sensor.pathos_humidity
  state_characteristic: average_linear
  unique_id: stats_pathos_humidity_average_linear
  max_age:
    hours: 2

- platform: history_stats
  name: HVAC Fan Runtime
  entity_id: switch.apartment_fan
  state: 'on'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 4
