#
# Templates
#
- platform: template
  sensors:
    apartment_feels_like:
      friendly_name: 'Feels Like'
      value_template: '{{ (0.5 * ( (states.sensor.apartment_temperatures.state|float) + 61.0 + ( ((states.sensor.apartment_temperatures.state|float) - 68.0) * 1.2 ) + ((states.sensor.apartment_humidities.state|float) * 0.094) ) )|round(2) }}'
      unit_of_measurement: '°F'


#
# Statistics
#
- platform: min_max
  name: Apartment Temperatures
  type: mean
  entity_ids:
    - sensor.apartment_thermostat_temperature
    - sensor.bathroom_temperature
    - sensor.bedroom_temperature
    - sensor.sunroom_temperature

- platform: min_max
  name: Non-Sunroom Temperatures
  type: mean
  entity_ids:
    - sensor.apartment_thermostat_temperature
    - sensor.bathroom_temperature
    - sensor.bedroom_temperature

- platform: min_max
  name: Apartment Humidities
  type: mean
  entity_ids:
    - sensor.apartment_thermostat_humidity
    - sensor.bathroom_relative_humidity
    - sensor.bedroom_relative_humidity
    - sensor.sunroom_relative_humidity

- platform: statistics
  entity_id: sensor.bathroom_temperature
  name: Bathroom Temp Stats
  sampling_size: 400
  max_age:
    hours: 12

- platform: statistics
  entity_id: sensor.bathroom_relative_humidity
  name: Bathroom Humidity Stats
  sampling_size: 400
  max_age:
    hours: 12

- platform: history_stats
  name: HVAC Fan Runtime
  entity_id: binary_sensor.apartment_thermostat_fan
  state: 'on'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 4
