#
# Nest
#
- platform: nest
  monitored_conditions:
    - 'humidity'

#
# MQTT
#
- platform: mqtt
  name: "Office Temperature"
  state_topic: "esp8266-007461/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: "Office Humidity"
  state_topic: "esp8266-007461/humidity"
  qos: 0
  unit_of_measurement: "%"

#
# Template
#
- platform: template
  sensors:
    office_temperature_diff:
      friendly_name: "Office Temperature Difference"
      value_template: |
        {{ (float(states.sensor.office_temperature.state) -
           float(states.sensor.apartment_thermostat_temperature.state)) | round(2) }}
      unit_of_measurement: '°F'
    office_humidity_diff:
      friendly_name: "Office Humidity Difference"
      value_template: |
        {{ (float(states.sensor.office_humidity.state) -
           float(states.sensor.apartment_thermostat_humidity.state)) | round(2) }}
      unit_of_measurement: '%'
