#
# Nest
#
- platform: nest

#
# MQTT
#
- platform: mqtt
  name: "Office Temperature"
  state_topic: "esp8266-007461/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: "Office Humidity"
  state_topic: "esp8266-007461/humidity"
  qos: 0
  unit_of_measurement: "%"


#
# Statistics
#
- platform: min_max
  name: Apartment Temperatures
  type: mean
  entity_ids:
    - sensor.apartment_thermostat_temperature
    - sensor.bathroom_temperature
    - sensor.bedroom_temperature
    - sensor.office_temperature

- platform: min_max
  name: Apartment Humidities
  type: mean
  entity_ids:
    - sensor.apartment_thermostat_humidity
    - sensor.bathroom_relative_humidity
    - sensor.bedroom_relative_humidity
    - sensor.office_humidity

- platform: statistics
  entity_id: sensor.bathroom_temperature
  name: Bathroom Temp Stats
  sampling_size: 400
  max_age:
    hours: 12

- platform: statistics
  entity_id: sensor.bathroom_relative_humidity
  name: Bathroom Humidity Stats
  sampling_size: 400
  max_age:
    hours: 12
