# Jeff

- platform: mqtt
  state_topic: 'person/jeff/alarm'
  name: 'Jeff Alarm'
  qos: 1
  value_template: '{{ value|capitalize }}'

- platform: mqtt
  state_topic: 'owntracks/jawilson/oxygen'
  name: 'Jeff Battery'
  unit_of_measurement: '%'
  value_template: |
    {% if value_json.batt %}
      {{ value_json.batt }}
    {% else %}
      {{ states.sensor.ajeff_battery.state }}
    {% endif %}

- platform: template
  sensors:
    jeff_sleep_state:
      value_template: |
        {% if is_state('binary_sensor.jeff_sleeping', 'on') %}
          Sleeping
        {% else %}
          Awake
        {% endif %}
      friendly_name: 'Jeff Sleeping'

# AK

- platform: mqtt
  state_topic: 'person/ak/alarm'
  name: 'AK Alarm'
  qos: 1
  value_template: '{{ value|capitalize }}'

- platform: mqtt
  state_topic: 'owntracks/annekat/reality'
  name: 'AK Battery'
  unit_of_measurement: '%'
  value_template: |
    {% if value_json.batt %}
      {{ value_json.batt }}
    {% else %}
      {{ states.sensor.ak_battery.state }}
    {% endif %}

- platform: template
  sensors:
    ak_sleep_state:
      value_template: |
        {% if is_state('binary_sensor.ak_sleeping', 'on') %}
          Sleeping
        {% else %}
          Awake
        {% endif %}
      friendly_name: 'AK Sleeping'
