# Jeff

- platform: mqtt
  state_topic: 'person/jeff/alarm'
  name: 'Jeff Alarm'
  qos: 1
  value_template: "{{ value|capitalize|replace('_',' ') }}"

- platform: mqtt
  state_topic: 'owntracks/jawilson/fluorine'
  name: 'Jeff Battery'
  unit_of_measurement: '%'
  value_template: >-
    {%- if value_json.batt -%}
    {{ value_json.batt }}
    {%- else -%}
    {{ states.sensor.jeff_battery.state }}
    {%- endif -%}

- platform: template
  sensors:
    jeff_sleep_state:
      friendly_name: 'Jeff Sleeping'
      value_template: >-
        {%- if is_state('binary_sensor.jeff_sleeping', 'on') -%}
        Sleeping
        {%- else -%}
        Awake
        {%- endif -%}

- platform: google_reverse_geocode
  api_key: !secret google_api_key
  entity_id: device_tracker.jawilson_fluorine

# AK

- platform: mqtt
  state_topic: 'person/ak/alarm'
  name: 'AK Alarm'
  qos: 1
  value_template: '{{ value|capitalize }}'

- platform: mqtt
  state_topic: 'owntracks/annekat/reality'
  name: 'AK Battery'
  unit_of_measurement: '%'
  value_template: >-
    {%- if value_json.batt -%}
    {{ value_json.batt }}
    {%- else -%}
    {{ states.sensor.ak_battery.state }}
    {%- endif -%}

- platform: template
  sensors:
    ak_sleep_state:
      friendly_name: 'AK Sleeping'
      value_template: >-
        {%- if is_state('binary_sensor.ak_sleeping', 'on') -%}
        Sleeping
        {%- else -%}
        Awake
        {%- endif -%}

- platform: google_reverse_geocode
  api_key: !secret google_api_key
  entity_id: device_tracker.annekat_reality
