# Jeff

- platform: mqtt
  state_topic: 'person/jeff/alarm'
  name: 'Jeff Alarm'
  icon: mdi:alarm
  qos: 1
  value_template: "{{ value_json.alarm_state|capitalize|replace('_',' ') }}"
  json_attributes_topic: 'person/jeff/alarm'

- platform: template
  sensors:
    jeff_sleep_state:
      friendly_name: 'Jeff Sleeping'
      value_template: "{{ state_attr('sensor.jeff_alarm', 'sleep_state')|capitalize }}"
    jeff_leave_work_today:
      friendly_name: 'Jeff leave work today'
      value_template: >
        {{ (
              as_timestamp(states.sensor.jeff_at_work_today.last_changed) +
              (8 - states.sensor.jeff_at_work_today.state|float) * 60 * 60
           )|timestamp_custom('%-I:%M %p') }}


- platform: google_reverse_geocode
  api_key: !secret google_api_key
  entity_id: person.jeff

- platform: google_reverse_geocode
  api_key: !secret google_api_key
  entity_id: person.sasha

- platform: history_stats
  name: Jeff at work today
  entity_id: person.jeff
  state: 'B-Line'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Jeff at work this week
  entity_id: person.jeff
  state: 'B-Line'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'

- platform: google_travel_time
  name: Jeff walk home
  api_key: !secret google_api_key
  origin: person.jeff
  destination: zone.home
  options:
    mode: walking

- platform: google_travel_time
  name: Jeff transit home
  api_key: !secret google_api_key
  origin: person.jeff
  destination: zone.home
  options:
    mode: transit

- platform: google_travel_time
  name: Jeff drive home
  api_key: !secret google_api_key
  origin: person.jeff
  destination: zone.home
  options:
    mode: driving
