# Jeff

- platform: mqtt
  state_topic: 'person/jeff/alarm'
  name: 'Jeff Alarm'
  qos: 1
  value_template: "{{ value|capitalize|replace('_',' ') }}"

- platform: mqtt
  state_topic: 'owntracks/jawilson/phosphorus'
  name: 'Jeff Battery'
  unit_of_measurement: '%'
  value_template: >-
    {%- if value_json.batt -%}
    {{ value_json.batt }}
    {%- else -%}
    {{ states.sensor.jeff_battery.state }}
    {%- endif -%}

- platform: template
  sensors:
    jeff_sleep_state:
      friendly_name: 'Jeff Sleeping'
      value_template: >-
        {%- if is_state('binary_sensor.jeff_sleeping', 'on') -%}
        Sleeping
        {%- else -%}
        Awake
        {%- endif -%}
    jeff_leave_work_today:
      friendly_name: 'Jeff leave work today'
      value_template: >
        {{(as_timestamp(now())+(8 - states.sensor.jeff_at_work_today.state|float)*60*60)|timestamp_custom('%-I:%M %p')}}


- platform: google_reverse_geocode
  api_key: !secret google_api_key
  entity_id: device_tracker.jawilson_phosphorus

- platform: history_stats
  name: Jeff at work today
  entity_id: device_tracker.jawilson_phosphorus
  state: 'B-Line'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Jeff at work this week
  entity_id: device_tracker.jawilson_phosphorus
  state: 'B-Line'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'

- platform: google_travel_time
  name: Jeff walk home
  api_key: !secret google_api_key
  origin: device_tracker.jawilson_phosphorus
  destination: zone.home
  options:
    mode: walking

- platform: google_travel_time
  name: Jeff transit home
  api_key: !secret google_api_key
  origin: device_tracker.jawilson_phosphorus
  destination: zone.home
  options:
    mode: transit

- platform: google_travel_time
  name: Jeff drive home
  api_key: !secret google_api_key
  origin: device_tracker.jawilson_phosphorus
  destination: zone.home
  options:
    mode: driving
