# Jeff

- platform: template
  sensors:
    jeff_leave_work_today:
      friendly_name: 'Jeff leave work today'
      value_template: >
        {{ (
              as_timestamp(states.sensor.jeff_at_work_today.last_changed) +
              (8 - states.sensor.jeff_at_work_today.state|float(0)) * 60 * 60
           )|timestamp_custom('%-I:%M %p') }}

- platform: google_reverse_geocode
  api_key: !secret google_api_key
  entity_id: person.jeff

- platform: google_reverse_geocode
  api_key: !secret google_api_key
  entity_id: person.sasha

- platform: history_stats
  name: Jeff at work today
  entity_id: person.jeff
  state: 'B-Line'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Jeff at work this week
  entity_id: person.jeff
  state: 'B-Line'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'
