# Jeff

- platform: mqtt
  state_topic: 'person/jeff/alarm'
  name: 'Jeff Alarm'
  qos: 1
  value_template: "{{ value|capitalize|replace('_',' ') }}"

- platform: mqtt
  state_topic: 'owntracks/jawilson/phosphorus'
  name: 'Jeff Battery'
  unit_of_measurement: '%'
  value_template: >-
    {%- if value_json.batt -%}
    {{ value_json.batt }}
    {%- else -%}
    {{ states.sensor.jeff_battery.state }}
    {%- endif -%}

- platform: template
  sensors:
    jeff_sleep_state:
      friendly_name: 'Jeff Sleeping'
      value_template: >-
        {%- if is_state('binary_sensor.jeff_sleeping', 'on') -%}
        Sleeping
        {%- else -%}
        Awake
        {%- endif -%}

- platform: google_reverse_geocode
  api_key: !secret google_api_key
  entity_id: device_tracker.jawilson_phosphorus
