# Forecast.io
- name: forecastio
  platform: darksky
  api_key: !secret forecast_key
  monitored_conditions:
    - summary
    - precip_intensity
    - temperature
    - humidity

# Sun
- platform: template
  sensors:
    sunrise:
      value_template: |
        {{ as_timestamp(states.sun.sun.attributes.next_rising)|timestamp_custom('%I:%M:%S %p') }}
      friendly_name: 'Next Sunrise'
    sunset:
      value_template: |
        {{ as_timestamp(states.sun.sun.attributes.next_setting)|timestamp_custom('%I:%M:%S %p') }}
      friendly_name: 'Next Sunset'


- name: WUndergound
  platform: wunderground
  api_key: !secret wunderground_key
  pws_id: KDCWASHI185
  monitored_conditions:
    - weather
    - temp_f
    - feelslike_f
    - wind_mph
    - precip_today_in
