- id: dehydrator_timer
  alias: Dehydrator Timer
  description: ''
  trigger:
  - platform: time
    at: input_datetime.dehydrator_start
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.orvibo
  - delay: '{{ states(''input_number.dehydrator_runtime'') | multiply(3600) | int
      }}'
  - service: switch.turn_off
    target:
      entity_id: switch.orvibo
  - service: notify.jeff_phone
    data:
      title: Dehydrator
      message: Dehydration is complete!
  mode: single
- id: '1646497667520'
  alias: Track Crosstrek
  description: Regularly locate the Crosstrek until it is turned off
  trigger:
  - type: powered
    platform: device
    device_id: 24995f8cf56359dc4e8fdc9976e35e81
    entity_id: binary_sensor.crosstrek_ignition
    domain: binary_sensor
  - platform: template
    value_template: '{% set devices = state_attr(''sensor.jawilson_phone_bluetooth_connection'',
      ''connected_paired_devices'') %}

      {{ ''F8:E8:77:8C:C3:45 (Subaru BT)'' in devices

      or ''86:1B:5F:D3:45:C4 (AndroidAuto-AAWNiM5fhLR)'' in devices

      }}'
  condition: []
  action:
  - repeat:
      until:
      - type: is_not_powered
        condition: device
        device_id: 24995f8cf56359dc4e8fdc9976e35e81
        entity_id: binary_sensor.crosstrek_ignition
        domain: binary_sensor
      sequence:
      - delay:
          hours: 0
          minutes: 2
          seconds: 0
          milliseconds: 0
      - service: button.press
        data: {}
        target:
          entity_id: button.crosstrek_locate
  mode: single
  max_exceeded: silent
- id: '1647013889004'
  alias: Update on Remote Start
  description: ''
  trigger:
  - platform: state
    entity_id: button.crosstrek_remote_start
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: button.press
    data: {}
    target:
      entity_id: button.crosstrek_locate
  mode: single
- id: '1665878909554'
  alias: Turn Off Dehumidifier When Sleeping
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.jeff_sleeping_at_home
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.jeff_sleeping_at_home
      state: 'on'
    then:
    - service: humidifier.turn_off
      data: {}
      target:
        entity_id: humidifier.dehumidifier
    else:
    - service: humidifier.turn_on
      data: {}
      target:
        entity_id: humidifier.dehumidifier
  mode: single
- id: '1679762800279'
  alias: Romantic Radio
  description: '[BROKEN] Ask Google to play Good Taste Bad Intentions radio when the
    romantic scene is activated.'
  trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: scene
      service: turn_on
      service_data:
        entity_id: scene.romantic
  condition: []
  action:
  - service: google_assistant_sdk.send_text_command
    data:
      command: Play good taste bad intentions on home group
  mode: single
- id: '1680153704895'
  alias: Sleep Humidifier
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.jeff_sleeping_at_home
    id: sleeping
  - platform: state
    entity_id:
    - sensor.jeff_alarm
    to: Bedtime
  - platform: numeric_state
    entity_id:
    - sensor.jawilson_phone_next_alarm
    - sensor.time
    - input_number.bedtime_cooldown_hours
    value_template: '{{ 24 if has_value(''sensor.jawilson_phone_next_alarm'') or state_attr(''sensor.jawilson_phone_next_alarm'',
      ''Package'') != ''com.urbandroid.sleep'' else (states(''sensor.jawilson_phone_next_alarm'')|as_timestamp
      - states.sensor.time.last_changed|as_timestamp)/60/60 }}'
    below: input_number.bedtime_cooldown_hours
    alias: Cooldown time
  condition:
  - condition: state
    entity_id: input_boolean.climate_auto
    state: 'on'
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.jeff_sleeping_at_home
        state: 'on'
      - condition: not
        conditions:
        - condition: trigger
          id: sleeping
        alias: Not triggered by sleeping
      alias: Jeff is sleeping at home or not triggered by sleeping
    then:
    - type: turn_on
      device_id: 81210812f6c61de9ef02bc74a31be9a7
      entity_id: humidifier.humidifier
      domain: humidifier
    - type: turn_on
      device_id: 81210812f6c61de9ef02bc74a31be9a7
      entity_id: switch.humidifier_auto_mode
      domain: switch
    - device_id: 81210812f6c61de9ef02bc74a31be9a7
      domain: number
      entity_id: number.humidifier_target_level
      type: set_value
      value: 60
    - type: turn_off
      device_id: 81210812f6c61de9ef02bc74a31be9a7
      entity_id: switch.humidifier_display
      domain: switch
    - device_id: 81210812f6c61de9ef02bc74a31be9a7
      domain: humidifier
      entity_id: humidifier.humidifier
      type: set_mode
      mode: sleep
    else:
    - type: turn_off
      device_id: 81210812f6c61de9ef02bc74a31be9a7
      entity_id: humidifier.humidifier
      domain: humidifier
  mode: single
- id: '1686175328990'
  alias: Notify Jeff Watch Charged
  description: Notify Jeff when his Pixel watch is fully charged.
  trigger:
  - type: battery_level
    platform: device
    device_id: b9264bcc99a8feea5c137ab34af1345e
    entity_id: sensor.jeff_s_pixel_watch_battery_level
    domain: sensor
    above: 99
    enabled: false
  - platform: state
    entity_id:
    - sensor.jawilson_watch_battery_state
    to: full
    from: charging
  - platform: state
    entity_id:
    - sensor.jeff_s_pixel_watch_battery_level
    to: '100'
  condition:
  - type: is_plugged_in
    condition: device
    device_id: b9264bcc99a8feea5c137ab34af1345e
    entity_id: binary_sensor.jeff_s_pixel_watch_is_charging
    domain: binary_sensor
  - type: is_off
    condition: device
    device_id: b9264bcc99a8feea5c137ab34af1345e
    entity_id: binary_sensor.jeff_s_pixel_watch_on_body_sensor
    domain: binary_sensor
  action:
  - wait_template: '{{ is_state(''binary_sensor.jeff_sleeping'', ''off'') }}'
    continue_on_timeout: true
    timeout: 00:30:00
    alias: Wait for Jeff to be awake
  - service: notify.jeff_phone
    data:
      message: Your Pixel watch has finished charging.
      title: Watch Charged
      data:
        tag: watch-charged
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.jeff_s_pixel_watch_on_body_sensor
      to: 'on'
      alias: When Jeff puts his watch on
    - platform: event
      event_type: mobile_app_notification_cleared
      context:
        user_id:
        - 94f1fb97e8374becb77c3979bbd3fc0b
      event_data:
        tag: watch-charged
      alias: When the notification is cleared
      id: notification_cleared
    - type: not_plugged_in
      platform: device
      device_id: b9264bcc99a8feea5c137ab34af1345e
      entity_id: binary_sensor.jeff_s_pixel_watch_is_charging
      domain: binary_sensor
    timeout:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - if:
    - condition: template
      value_template: '{{ wait.trigger.id != ''notification_cleared'' }}'
      alias: Notification not cleared
    then:
    - service: notify.jeff_phone
      data:
        message: clear_notification
        data:
          tag: watch-charged
    alias: Clear notification if Jeff put his watch on
  mode: single
- id: '1687403992329'
  alias: Play news when waking up bedroom
  description: ''
  trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.wake_up_bedroom
  condition:
  - condition: state
    entity_id: person.jeff
    state: home
  action:
  - service: notify.jeff_phone
    data:
      message: Would you like to hear the latest news?
      data:
        tag: morning-news
        actions:
        - action: 'yes'
          title: 'Yes'
        - action: 'no'
          title: 'No'
  - wait_for_trigger:
    - platform: event
      event_type: mobile_app_notification_cleared
      event_data:
        tag: morning-news
      context:
        user_id:
        - 94f1fb97e8374becb77c3979bbd3fc0b
      alias: Notification is cleared
    - platform: event
      event_type: mobile_app_notification_action
      alias: Notification responded to
      event_data:
        tag: morning-news
      context:
        user_id:
        - 94f1fb97e8374becb77c3979bbd3fc0b
    - platform: state
      entity_id:
      - person.jeff
      from: home
      alias: Jeff Leaves Home
    - platform: state
      entity_id:
      - binary_sensor.jeff_sleeping
      alias: Jeff Goes Back to Sleep
      to: 'on'
    timeout:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ wait.trigger.event.data.action == ''yes'' }}'
        alias: Responded Yes to Notification
      sequence:
      - service: google_assistant_sdk.send_text_command
        data:
          command: listen to the latest news on home group
    - conditions:
      - condition: template
        value_template: '{{ wait.trigger.event.event_type != ''mobile_app_notification_cleared''
          }}'
        alias: Notification wasn't cleared
      sequence:
      - service: notify.jeff_phone
        data:
          message: clear_notification
          data:
            tag: morning-news
        alias: Clear notification
  mode: single
- id: '1687406200035'
  alias: Notify Tasker When Sleeping at Home Alone
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.jeff_sleeping_at_home_alone
    to: 'on'
  condition: []
  action:
  - service: notify.jeff_phone
    data:
      message: command_broadcast_intent
      data:
        intent_package_name: net.dinglisch.android.taskerm
        intent_action: net.dinglisch.android.taskerm.SLEEPING_AT_HOME_ALONE
  mode: single
