homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: 38.904135
  longitude: -77.016510
  elevation: 17
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_named customizations
  customize_glob: !include customize_glob.yaml

default_config:
discovery:

# Web
http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies: 192.168.0.100

lovelace:
  mode: yaml

cloud:
  google_actions: !include google_actions.yaml

# Use a postgresql server for recording data
recorder:
  db_url: 'postgresql://hass:automatethethings@database/homeassistant'
  exclude:
    domains:
      - camera
      - scene
      - zone
    entities:
      - sun.sun
      - binary_sensor.p3steel_printing
      - binary_sensor.p3steel_printing_error
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_icon
      - sensor.dark_sky_summary
      - sensor.dark_sky_wind_speed
      - sensor.p3steel_actual_bed_temp
      - sensor.p3steel_actual_tool0_temp
      - sensor.p3steel_job_percentage
      - sensor.p3steel_target_bed_temp
      - sensor.p3steel_target_tool0_temp
      - sensor.sunrise
      - sensor.sunset
      - sensor.jeff_leave_work_today

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
      - zwave
    entities:
      - automation.force_bathroom_fan_off
      - automation.force_closet_light_off
      - automation.force_dining_lights_off
      - automation.force_kitchen_cabinet_lights_off
      - automation.update_jeff_travel_sensors_on_movement
      - automation.update_jeff_travel_sensors_periodic
      - automation.update_sasha_travel_sensors_on_movement
      - automation.update_sasha_travel_sensors_periodic
      - binary_sensor.jeff_home
      - binary_sensor.sasha_home
      - binary_sensor.bathroom_humidity_trend
      - binary_sensor.bathroom_temp_trend
      - binary_sensor.remote_ui
      - light.living_area_lights
      - light.entryway_lights
      - light.entryway_light
      - light.kitchen_lights
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.kitchen_light_3
      - light.kitchen_light_4
      - light.bedroom
      - light.bedroom_lights
      - light.bedroom_nook_1
      - light.bedroom_nook_2
      - light.bedroom_nook_3
      - light.tree_lamp_1
      - light.tree_lamp_2
      - light.tree_lamp_3
      - light.tree_lamp_4
      - light.tree_lamp_5
      - light.living_room
      - light.living_room_lights
      - light.entertainment_light_1
      - light.entertainment_light_2
      - light.projector
      - light.bathroom
      - light.bathroom_lights
      - light.bathroom_mirror_1
      - light.bathroom_mirror_2
      - light.bathroom_mirror_3
      - light.bathroom_mirror_4
      - light.closet_lights
      - light.sunroom
      - light.sunroom_lights
      - light.sunroom_fan_light_1
      - light.sunroom_fan_light_2
      - light.color_lights
      - light.color_temperature_lights
      - media_player.bathroom_mini
      - media_player.bedroom_speaker
      - media_player.home
      - media_player.kitchen_display
      - media_player.living_room_speaker
      - media_player.shield
      - media_player.sunroom
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
      - sensor.sunrise
      - sensor.sunset
      - sensor.google_reverse_geocode_jeff
      - sensor.google_reverse_geocode_sasha
      - sensor.jeff_sleeping_at_home
      - sensor.sashag_phone_battery_level
      - sensor.sashag_phone_battery_state
      - sensor.neo_coolcam_door_window_detector_access_control
      - sensor.neo_coolcam_door_window_detector_alarm_level
      - switch.apartment_fan
      - switch.bedroom_motion_automations
      - switch.bathroom_motion_automations
      - switch.closet_motion_automations
  include:
    entities:
      - group.everyone

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - binary_sensor
      - climate
      - device_tracker
      - person
      - light
      - proximity
      - sensor
      - switch
      - vacuum
    entities:
      - media_player.cast_bedroom
      - media_player.cast_kitchen_display
      - media_player.cast_living_room_speaker
      - media_player.cast_everything_group
      - media_player.shield
  exclude:
    entities:
      - binary_sensor.apartment_thermostat_has_leaf
      - binary_sensor.jeff_home
      - binary_sensor.sasha_home
      - binary_sensor.jeff_sleeping_at_home
      - binary_sensor.bathroom_humidity_trend
      - binary_sensor.bathroom_temp_trend
      - binary_sensor.remote_ui
      - device_tracker.jawilson_phone
      - device_tracker.jawilson_phone_owntracks
      - device_tracker.sashag_phone
      - device_tracker.sashag_phone_ios
      - light.entryway
      - light.entryway_lights
      - light.kitchen
      - light.kitchen_lights
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.kitchen_light_3
      - light.kitchen_light_4
      - light.bathroom
      - light.bathroom_lights
      - light.bathroom_mirror_1
      - light.bathroom_mirror_2
      - light.bathroom_mirror_3
      - light.bathroom_mirror_4
      - light.shower
      - light.closet
      - light.closet_lights
      - light.bedroom
      - light.bedroom_lights
      - light.nightstand_1
      - light.nightstand_2
      - light.tree_lamp_1
      - light.tree_lamp_2
      - light.tree_lamp_3
      - light.tree_lamp_4
      - light.tree_lamp_5
      - light.living_room
      - light.living_room_lights
      - light.living_area_lights
      - light.projector
      - light.entertainment_light_1
      - light.entertainment_light_2
      - light.sunroom
      - light.sunroom_lights
      - light.sunroom_fan_light_1
      - light.sunroom_fan_light_2
      - light.bedroom_lamp
      - light.desk_lamp
      - light.color_lights
      - light.color_temperature_lights
      - sensor.apartment_temperatures
      - sensor.apartment_thermostat_humidity
      - sensor.apartment_thermostat_target
      - sensor.apartment_thermostat_temperature
      - sensor.apartment_feels_like
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
      - sensor.google_reverse_geocode_jeff
      - sensor.google_reverse_geocode_sasha
      - sensor.sashag_phone_battery_level
      - sensor.sashag_phone_battery_state
      - switch.apartment_fan
      - switch.bathroom_fluxer
      - switch.bathroom_motion
      - switch.bedroom_fluxer
      - switch.bedroom_motion
      - switch.closet_fluxer
      - switch.closet_motion
      - switch.living_area_fluxer
      - switch.plex
      - switch.projector
      - switch.shield
      - switch.xbox_360
      - switch.xbox_one


#
# Integrations
#

tts:
  - platform: google_translate
    service_name: google_say

emulated_hue: !include emulated_hue.yaml

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret
  track_new_calendar: false

notify:
  - platform: html5
    name: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: ios
    name: ios
  - platform: group
    name: jeff
    services:
      - service: html5_jawilson_phone
      - service: html5_jawilson_work
      - service: html5_jawilson_maxwell
  - platform: group
    name: sasha
    services:
      - service: ios_sashag_phone_ios
  - platform: group
    name: family
    services:
      - service: jeff
      - service: sasha
  - platform: group
    name: family_phones
    services:
      - service: html5_jawilson_phone
      - service: ios_sashag_phone_ios

# Intent services
alexa:
dialogflow:
intent_script: !include intent_scripts.yaml

#
# Hubs
#
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  binary_sensors:
    monitored_conditions:
      - 'fan'
      - 'has_leaf'
  sensors:
    monitored_conditions:
      - 'temperature'
      - 'target'
      - 'humidity'
      - 'hvac_mode'
      - 'hvac_state'

hue:
  bridges:
    - host: 192.168.0.54
      allow_unreachable: true
      filename: hue_hub_token.conf

ios: !include ios.yaml

octoprint:
  name: P3Steel
  host: p3steel.singularity.net
  api_key: !secret octoprint_key
  bed: true
  number_of_tools: 1
  sensors:
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage
  binary_sensors:
    monitored_conditions:
      - Printing
      - Printing Error

mqtt:
  broker: mqtt.singularity.net
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /config/certs/ca.crt

zwave:
  usb_path: /dev/zwave
  device_config: !include zwave_device_config.yaml
  device_config_glob: !include zwave_device_config_glob.yaml

zha:
  usb_path: /dev/zigbee
  database_path: /config/zigbee.db

apcupsd:
  host: feynman.singularity.net
  port: 3551


# Sensors
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors

# Inputs
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml

#
# Devices
#
climate:
  - platform: nest
  - platform: generic_thermostat
    name: Sunroom
    heater: switch.sunroom_switch
    target_sensor: sensor.sunroom_temperature
    min_cycle_duration: 00:10:00
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_temp: 50
    max_temp: 90
    away_temp: 55
    precision: 0.5

light: !include lights.yaml

person: !include people.yaml

device_tracker:

owntracks:
  max_gps_accuracy: 45

asuswrt:
  host: 192.168.0.1
  username: !secret asuswrt_username
  protocol: ssh
  port: 22
  mode: router
  ssh_key: /config/.ssh/asuswrt_id_rsa

cast:
media_player: !include media_players.yaml

remote:
  - platform: harmony
    name: Living Room
    host: HarmonyHub.singularity.net

camera: !include cameras.yaml

switch: !include_dir_merge_list switches

vacuum:
  - platform: roomba
    name: Doomba
    host: Doomba.singularity.net
    username: !secret doomba_blid
    password: !secret doomba_password

# Groups
group: !include groups.yaml

# Zones
zone: !include zones.yaml

# Proximity
proximity:
  home:
    ignored_zones:
      - bline
      - river
    devices:
      - person.jeff
      - person.sasha
    tolerance: 50
    unit_of_measurement: m

# Scenes
scene: !include scenes.yaml

# Scripts
script: !include_dir_named scripts
python_script:

# Automation
automation old: !include_dir_merge_list automation

# Rest Commands
rest_command: !include rest_command.yaml

shell_command: !include shell_command.yaml

#
# Logger
#
logger:
  default: error
  logs:
    homeassistant: !env_var HA_LOG_LEVEL
    homeassistant.core: warning
    homeassistant.bootstrap: error
    homeassistant.components.api: error
    homeassistant.components.http: error
    homeassistant.components.websocket_api: error
    homeassistant.components.recorder: error
    homeassistant.components.remote.harmony: error
    homeassistant.components.device_tracker.asuswrt: error
    homeassistant.components.device_tracker.owntracks: error
    homeassistant.components.sensor.octoprint: error
    homeassistant.components.switch.orvibo: critical
    #custom_components.google_reverse_geocode.sensor: debug
