homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 38.9039
  longitude: -77.0165
  elevation: 17
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_named customizations

# Web
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Discover some devices automatically
#discovery:

# Track the sun
sun:

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

# Hue Emulation
emulated_hue:
  host_ip: 192.168.0.60
  listen_port: 8300
  exposed_domains:
    - switch
    - light
    - input_boolean
    - scene

# If This Then That
ifttt:
  key: !secret ifttt_key

# MQTT
mqtt:
  broker: mqtt.singularity.net
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /config/certs/ca.crt

#
# Hubs
#
nest:
  username: !secret nest_username
  password: !secret nest_password

octoprint:
  host: p3steel.singularity.net
  api_key: !secret octoprint_key

asuswrt:
  host: dark-knight.singularity.net
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  protocol: telnet


# Sensors
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors

# Inputs
input_boolean: !include input_boolean.yaml

#
# Devices
#
climate:
  platform: nest

light: !include lights.yaml

device_tracker:
  - platform: asuswrt
    host: dark-knight.singularity.net
    username: !secret asuswrt_username
    password: !secret asuswrt_password
    track_new_devices: no
    protocol: telnet
  - platform: owntracks
    max_gps_accuracy: 50

media_player: !include media_players.yaml

# Cameras
camera: !include cameras.yaml

alexa: !include alexa.yaml

# Switches
switch: !include_dir_merge_list switches

# Notifications
notify: !include notifications.yaml

# Groups
group: !include groups.yaml

# Zones
zone: !include zones.yaml

# Proximity
proximity:
  home:
    ignored_zones:
      - blackstone
      - bline
      - dhs
    devices:
      - device_tracker.jawilson_fluorine
      - device_tracker.annekat_reality
    tolerance: 50
    unit_of_measurement: m

# Scenes
scene: !include scenes.yaml

# Scripts
script: !include_dir_named scripts

# Automation
automation: !include_dir_merge_list automation

#
# Logger
#
logger:
  default: error
  logs:
    homeassistant: !env_var HA_LOG_LEVEL
    homeassistant.bootstrap: error
    homeassistant.core: error
    homeassistant.components.api: error
    homeassistant.components.http: error
    homeassistant.components.recorder: error
    homeassistant.components.device_tracker.asuswrt: error
