homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 38.9039
  longitude: -77.0165
  elevation: 17
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_named customizations
  customize_glob: !include customize_glob.yaml

# Web
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Use a postgresql server for recording data
recorder:
  db_url: 'postgresql://hass:automatethethings@database/homeassistant'

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
    entities:
      - light.bedroom
      - light.living_room
      - light.tree_lamp_1
      - light.tree_lamp_2
      - light.tree_lamp_3
      - light.tree_lamp_4
      - light.tree_lamp_5
      - light.living_room_lamp_1
      - light.living_room_lamp_2
      - sensor.sunrise
      - sensor.sunset
      - switch.apartment_fan

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - binary_sensor
      - climate
      - device_tracker
      - light
      - proximity
      - sensor
      - switch
    entities:
      - media_player.cast_bedroom
      - media_player.cast_kitchen_home
      - media_player.shield
  exclude:
    entities:
      - binary_sensor.ak_sleeping
      - binary_sensor.ak_sleeping_at_home
      - binary_sensor.apartment_thermostat_has_leaf
      - binary_sensor.everyone_at_home_sleeping
      - binary_sensor.jeff_sleeping
      - binary_sensor.jeff_sleeping_at_home
      - binary_sensor.p3steel_printing
      - binary_sensor.p3steel_printing_error
      - binary_sensor.sleeping_at_home
      - light.bathroom
      - light.bathroom_mirror_1
      - light.bathroom_mirror_2
      - light.bathroom_mirror_3
      - light.bathroom_mirror_4
      - light.bedroom
      - light.closet
      - light.living_room
      - light.living_room_lamp_1
      - light.living_room_lamp_2
      - light.tree_lamp_1
      - light.tree_lamp_2
      - light.tree_lamp_3
      - light.tree_lamp_4
      - light.tree_lamp_5
      - sensor.apartment_temperatures
      - sensor.apartment_thermostat_humidity
      - sensor.apartment_thermostat_target
      - sensor.apartment_thermostat_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_icon
      - sensor.dark_sky_pressure
      - sensor.dark_sky_summary
      - sensor.dark_sky_wind_bearing
      - sensor.google_reverse_geocode__ak
      - sensor.google_reverse_geocode__jeff
      - sensor.office_temperature_stats_mean
      - sensor.office_voltage
      - sensor.pws_feelslike_f
      - sensor.pws_temp_f
      - sensor.pws_wind_mph
      - sensor.pws_precip_today_in
      - sensor.p3steel_actual_bed_temp
      - sensor.p3steel_actual_tool0_temp
      - sensor.p3steel_current_state
      - sensor.p3steel_job_percentage
      - sensor.p3steel_target_bed_temp
      - sensor.p3steel_target_tool0_temp
      - sensor.sunrise
      - sensor.sunset
      - switch.apartment_fan
      - switch.bathroom_fluxer
      - switch.bedroom_fluxer
      - switch.cat_water
      - switch.christmas_tree
      - switch.crockpot
      - switch.living_area_fluxer
      - switch.orvibo1
      - switch.orvibo2
      - switch.plex
      - switch.projector
      - switch.shield
      - switch.shield_audio
      - switch.wii
      - switch.xbox_360
      - switch.xbox_one

# Enables the frontend
frontend:

# Enables map panel
map:

# Enables configuration panel
config:

# Discover some devices automatically
#discovery:

# Track the sun
sun:

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:


#
# Integrations
#

emulated_hue:
  type: google_home
  host_ip: 192.168.0.60
  listen_port: 80
  exposed_domains:
    - switch
    - light
    - scene
    - fan

ifttt:
  key: !secret ifttt_key

notify: !include notifications.yaml

# Intent services
alexa:
apiai:
intent_script: !include intent_scripts.yaml

#
# Hubs
#
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  binary_sensors:
    monitored_conditions:
      - 'fan'
      - 'has_leaf'
  sensors:
    monitored_conditions:
      - 'temperature'
      - 'target'
      - 'humidity'
      - 'operation_mode'
      - 'hvac_state'

octoprint:
  host: p3steel.singularity.net
  api_key: !secret octoprint_key

mqtt:
  broker: mqtt.singularity.net
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /config/certs/ca.crt

insteon_local:
  host: insteonhub.singularity.net
  username: !secret insteon_username
  password: !secret insteon_password

zwave:
  usb_path: /dev/zwave
  device_config: !include zwave_device_config.yaml
  device_config_glob: !include zwave_device_config_glob.yaml

zha:
  usb_path: /dev/zigbee
  database_path: /config/zigbee.db


# Sensors
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors

# Inputs
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml

#
# Devices
#
climate:
  platform: nest

light: !include lights.yaml

device_tracker:
  - platform: asuswrt
    host: dark-knight.singularity.net
    username: !secret asuswrt_username
    password: !secret asuswrt_password
    track_new_devices: no
    protocol: telnet
  - platform: owntracks
    max_gps_accuracy: 45

media_player: !include media_players.yaml

remote:
  - platform: harmony
    name: Living Room
    host: harmonyhub.singularity.net
    activity: 'Play Shield'

camera: !include cameras.yaml

switch: !include_dir_merge_list switches

fan:
  platform: insteon_local

# Groups
group: !include groups.yaml

# Zones
zone: !include zones.yaml

# Proximity
proximity:
  home:
    ignored_zones:
      - blackstone
      - bline
      - dhs
      - 650_mass
    devices:
      - device_tracker.jawilson_fluorine
      - device_tracker.annekat_reality
    tolerance: 50
    unit_of_measurement: m

# Scenes
scene: !include scenes.yaml

# Scripts
script: !include_dir_named scripts
python_script:

# Automation
automation: !include_dir_merge_list automation

#
# Logger
#
logger:
  default: error
  logs:
    homeassistant: !env_var HA_LOG_LEVEL
    homeassistant.core: warning
    homeassistant.bootstrap: error
    homeassistant.components.api: error
    homeassistant.components.http: error
    homeassistant.components.websocket_api: error
    homeassistant.components.recorder: error
    homeassistant.components.remote.harmony: error
    homeassistant.components.device_tracker.asuswrt: error
    homeassistant.components.insteon_local: warning
    homeassistant.components.sensor.octoprint: error
