homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 38.9039
  longitude: -77.0165
  elevation: 17
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_named customizations

# Web
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Use a postgresql server for recording data
recorder:
  db_url: 'postgresql://hass:automatethethings@database/homeassistant'

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - binary_sensor
      - climate
      - device_tracker
      - light
      - proximity
      - sensor
      - switch
    entities:
      - media_player.cast_bedroom
      - media_player.cask_kitchen_home
      - media_player.cask_shield
      - media_player.plex_shield
  exclude:
    entities:
      - binary_sensor.ak_sleeping
      - binary_sensor.apartment_thermostat_has_leaf
      - binary_sensor.apartment_thermostat_is_locked
      - binary_sensor.apartment_thermostat_is_using_emergency_heat
      - binary_sensor.apartment_thermostat_online
      - binary_sensor.jeff_sleeping
      - binary_sensor.p3steel_printing
      - binary_sensor.p3steel_printing_error
      - light.bedroom
      - light.entryway_2
      - light.hgrp0000000006
      - light.living_room
      - sensor.p3steel_actual_bed_temp
      - sensor.p3steel_actual_tool0_temp
      - sensor.p3steel_job_percentage
      - sensor.p3steel_target_bed_temp
      - sensor.p3steel_target_tool0_temp
      - sensor.sunrise
      - sensor.sunset
      - switch.bedroom_fluxer
      - switch.christmas_tree
      - switch.feynman
      - switch.guests
      - switch.living_area_fluxer
      - switch.orvibo1
      - switch.orvibo2
      - switch.plex
      - switch.presence
      - switch.projector
      - switch.shield
      - switch.shield_audio
      - switch.wii
      - switch.xbox_360
      - switch.xbox_one

# Enables the frontend
frontend:

# Discover some devices automatically
#discovery:

# Track the sun
sun:

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

# Hue Emulation
emulated_hue:
  type: google_home
  host_ip: 192.168.0.60
  listen_port: 80
  exposed_domains:
    - switch
    - light
    - scene

# If This Then That
ifttt:
  key: !secret ifttt_key

# MQTT
mqtt:
  broker: mqtt.singularity.net
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /config/certs/ca.crt

#
# Hubs
#
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

octoprint:
  host: p3steel.singularity.net
  api_key: !secret octoprint_key

asuswrt:
  host: dark-knight.singularity.net
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  protocol: telnet

insteon_local:
  host: insteonhub.singularity.net
  username: !secret insteon_username
  password: !secret insteon_password


# Sensors
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors

# Inputs
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml

#
# Devices
#
climate:
  platform: nest

light: !include lights.yaml

device_tracker:
  - platform: asuswrt
    host: dark-knight.singularity.net
    username: !secret asuswrt_username
    password: !secret asuswrt_password
    track_new_devices: no
    protocol: telnet
  - platform: owntracks
    max_gps_accuracy: 45

media_player: !include media_players.yaml

remote:
  - platform: harmony
    name: Living Room
    host: harmonyhub.singularity.net
    activity: 'Play Shield'

# Cameras
camera: !include cameras.yaml

alexa: !include alexa.yaml

# Switches
switch: !include_dir_merge_list switches

# Notifications
notify: !include notifications.yaml

# Groups
group: !include groups.yaml

# Zones
zone: !include zones.yaml

# Proximity
proximity:
  home:
    ignored_zones:
      - blackstone
      - bline
      - dhs
    devices:
      - device_tracker.jawilson_fluorine
      - device_tracker.annekat_reality
    tolerance: 50
    unit_of_measurement: m

# Scenes
scene: !include scenes.yaml

# Scripts
script: !include_dir_named scripts

# Automation
automation: !include_dir_merge_list automation

#
# Logger
#
logger:
  default: error
  logs:
    homeassistant: !env_var HA_LOG_LEVEL
    homeassistant.bootstrap: error
    homeassistant.core: error
    homeassistant.components.api: error
    homeassistant.components.http: error
    homeassistant.components.websocket_api: error
    homeassistant.components.recorder: error
    homeassistant.components.remote.harmony: error
    homeassistant.components.device_tracker.asuswrt: error
