homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: 38.904135
  longitude: -77.016510
  elevation: 17
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  country: US

  external_url: !secret http_base_url
  internal_url: http://192.168.0.60:8123

  customize: !include_dir_merge_named customizations
  customize_glob: !include customize_glob.yaml

default_config:
discovery:
update:

# Web
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.25.0.0/16

lovelace:
  mode: yaml
  resources:
    - url: /local/ui/more-info-map.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module

cloud:
  google_actions: !include google_actions.yaml

# Use a postgresql server for recording data
recorder:
  db_url: 'postgresql://hass:automatethethings@database/homeassistant'
  exclude:
    domains:
      - camera
      - scene
      - zone
    entities:
      - sun.sun
      - binary_sensor.p3steel_printing
      - binary_sensor.p3steel_printing_error
      - sensor.p3steel_actual_bed_temp
      - sensor.p3steel_actual_tool0_temp
      - sensor.p3steel_job_percentage
      - sensor.p3steel_target_bed_temp
      - sensor.p3steel_target_tool0_temp
      - sensor.sunrise
      - sensor.sunset
      - sensor.time
      - sensor.jeff_leave_work_today

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
      - zwave
    entities:
      - automation.force_bathroom_fan_off
      - automation.force_closet_light_off
      - automation.force_dining_lights_off
      - automation.force_kitchen_cabinet_lights_off
      - automation.sunroom_fan
      - automation.update_jeff_travel_sensors_on_movement
      - automation.update_jeff_travel_sensors_periodically
      - binary_sensor.jeff_home
      - binary_sensor.bathroom_humidity_trend
      - binary_sensor.bathroom_temp_trend
      - binary_sensor.remote_ui
      - light.living_area_lights
      - light.entryway_lights
      - light.entryway_light
      - light.kitchen_lights
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.kitchen_light_3
      - light.kitchen_light_4
      - light.bedroom
      - light.bedroom_lights
      - light.tree_lamp_1
      - light.tree_lamp_2
      - light.tree_lamp_3
      - light.tree_lamp_4
      - light.tree_lamp_5
      - light.living_room
      - light.living_room_lights
      - light.entertainment_light_1
      - light.entertainment_light_2
      - light.projector
      - light.bathroom
      - light.bathroom_lights
      - light.bathroom_mirror_1
      - light.bathroom_mirror_2
      - light.bathroom_mirror_3
      - light.bathroom_mirror_4
      - light.closet_lights
      - light.sunroom
      - light.sunroom_lights
      - light.sunroom_fan_light_1
      - light.sunroom_fan_light_2
      - light.color_lights
      - light.color_temperature_lights
      - media_player.bathroom_mini
      - media_player.bedroom_speaker
      - media_player.home
      - media_player.kitchen_display
      - media_player.living_room_speaker
      - media_player.shield
      - media_player.sunroom
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
      - sensor.sunrise
      - sensor.sunset
      - sensor.google_reverse_geocode_jeff
      - sensor.jeff_sleeping_at_home
      - sensor.time
      - sensor.neo_coolcam_door_window_detector_access_control
      - switch.apartment_fan
      - switch.bedroom_motion_automations
      - switch.bathroom_motion_automations
      - switch.closet_motion_automations

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - binary_sensor
      - climate
      - device_tracker
      - person
      - light
      - proximity
      - sensor
      - switch
      - vacuum
    entities:
      - media_player.cast_bedroom_speaker
      - media_player.cast_kitchen_display
      - media_player.cast_living_room_speaker
      - media_player.shield
  exclude:
    entities:
      - binary_sensor.apartment_thermostat_has_leaf
      - binary_sensor.jeff_home
      - binary_sensor.jeff_sleeping_at_home
      - binary_sensor.bathroom_humidity_trend
      - binary_sensor.bathroom_temp_trend
      - binary_sensor.remote_ui
      - device_tracker.jawilson_phone
      - light.entryway
      - light.entryway_lights
      - light.kitchen
      - light.kitchen_lights
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.kitchen_light_3
      - light.kitchen_light_4
      - light.bathroom
      - light.bathroom_lights
      - light.bathroom_mirror_1
      - light.bathroom_mirror_2
      - light.bathroom_mirror_3
      - light.bathroom_mirror_4
      - light.shower
      - light.closet
      - light.closet_lights
      - light.bedroom
      - light.bedroom_lights
      - light.nightstand_1
      - light.nightstand_2
      - light.tree_lamp_1
      - light.tree_lamp_2
      - light.tree_lamp_3
      - light.tree_lamp_4
      - light.tree_lamp_5
      - light.living_room
      - light.living_room_lights
      - light.living_area_lights
      - light.projector
      - light.entertainment_light_1
      - light.entertainment_light_2
      - light.sunroom
      - light.sunroom_lights
      - light.sunroom_fan_light_1
      - light.sunroom_fan_light_2
      - light.bedroom_lamp
      - light.desk_lamp
      - light.color_lights
      - light.color_temperature_lights
      - sensor.apartment_temperatures
      - sensor.apartment_thermostat_humidity
      - sensor.apartment_thermostat_target
      - sensor.apartment_thermostat_temperature
      - sensor.apartment_feels_like
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
      - sensor.google_reverse_geocode_jeff
      - sensor.time
      - switch.apartment_fan
      - switch.circadian_lighting_bathroom
      - switch.bathroom_motion
      - switch.circadian_lighting_bedroom
      - switch.bedroom_motion
      - switch.circadian_lighting_closet
      - switch.closet_motion
      - switch.circadian_lighting_living_area


#
# Integrations
#

circadian_lighting:

ffmpeg:

tts:
  - platform: google_translate
    service_name: google_say

emulated_hue: !include emulated_hue.yaml


notify:
  - platform: html5
    name: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: group
    name: jeff_phone
    services:
      - service: mobile_app_jawilson_phone
  - platform: group
    name: jeff
    services:
      - service: jeff_phone
      - service: html5_jawilson_work
      - service: html5_jawilson_maxwell
  - platform: group
    name: family
    services:
      - service: jeff
  - platform: group
    name: family_phones
    services:
      - service: jeff_phone

# Intent services
alexa:
dialogflow:
intent_script: !include intent_scripts.yaml

#
# Hubs
#
ios:

# Sensors
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
template: !include_dir_merge_list template_sensors

# Inputs
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_datetime:
  dehydrator_start:
    name: Dehydrator Start Time
    has_date: true
    has_time: true

#
# Devices
#
climate:
  - platform: generic_thermostat
    name: Sunroom
    unique_id: sunroom_thermostat
    heater: switch.sunroom_switch
    target_sensor: sensor.sunroom_temperature
    min_cycle_duration: 00:10:00
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_temp: 50
    max_temp: 90
    away_temp: 55
    precision: 0.5

light: !include lights.yaml

device_tracker:

media_player: !include media_players.yaml

switch: !include_dir_merge_list switches


# Groups
group: !include groups.yaml

# Zones
zone: !include zones.yaml

# Proximity
proximity:
  home:
    ignored_zones:
      - lldc
    devices:
      - person.jeff
    tolerance: 50
    unit_of_measurement: m

# Scenes
scene: !include scenes.yaml

# Scripts
script: !include_dir_named scripts
script ui: !include scripts.yaml
python_script:

# Automation
automation: !include automations.yaml
automation old: !include_dir_merge_list automation

# Rest Commands
rest_command: !include rest_command.yaml

shell_command: !include shell_command.yaml

#
# Logger
#
logger:
  default: error
  logs:
    homeassistant: !env_var HA_LOG_LEVEL
    homeassistant.core: warning
    homeassistant.bootstrap: error
    homeassistant.components.api: error
    homeassistant.components.http: error
    homeassistant.components.websocket_api: error
    homeassistant.components.recorder: error
    homeassistant.components.remote.harmony: error
    homeassistant.components.device_tracker.asuswrt: error
    homeassistant.components.sensor.octoprint: error
    homeassistant.components.switch.orvibo: critical
    #custom_components.google_reverse_geocode.sensor: debug
