# Hue
- platform: hue
  host: philipshue.singularity.net
  allow_unreachable: true
  filename: hue_hub_token.conf

# Insteon
- platform: insteondimmeroh
  name: "Entertainment"
  url: http://openhab:8080/rest/items/Dimmer2
- platform: insteondimmeroh
  name: "Dining"
  url: http://openhab:8080/rest/items/DimmerSwitch1
- platform: insteondimmeroh
  name: "Kitchen"
  url: http://openhab:8080/rest/items/DimmerSwitch2
