# Ikea Dioder
- platform: mqtt
  name: "Liquor cabinet lights"
  schema: json
  state_topic: "home/livingroom/liquorcabinet"
  command_topic: "home/livingroom/liquorcabinet/set"
  brightness: true
  rgb: true
  optimistic: false
  qos: 0

- platform: group
  name: Entryway Lights
  entities:
    - light.entryway

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen
    - light.kitchen_cabinet_lights

- platform: group
  name: Living Area Lights
  entities:
    - light.entryway_lights
    - light.kitchen_lights
    - light.dining_lights_level
    - light.living_room_lights
    - light.sunroom_lights

- platform: group
  name: Tree Lamp
  unique_id: 'tree_lamp'
  entities:
    - light.tree_lamp_1
    - light.tree_lamp_2
    - light.tree_lamp_3
    - light.tree_lamp_4
    - light.tree_lamp_5

- platform: group
  name: Entertainment Lights
  unique_id: 'entertainment_lights'
  entities:
    - light.entertainment_light_1
    - light.entertainment_light_2

- platform: group
  name: Living Room Lights
  entities:
    - light.living_room

- platform: group
  name: Sunroom Fan Light
  unique_id: 'sunroom_fan_light'
  entities:
    - light.sunroom_fan_light_1
    - light.sunroom_fan_light_2

- platform: group
  name: Sunroom Lights
  entities:
    - light.sunroom

- platform: group
  name: Bedroom Nook
  entities:
    - light.bedroom_nook_1
    - light.bedroom_nook_2
    - light.bedroom_nook_3

- platform: group
  name: Bedroom Lights
  unique_id: 'bedroom_lights_group'
  entities:
    - light.bedroom
    - light.bedroom_nook

- platform: group
  name: Closet Lights
  entities:
    - light.closet

- platform: group
  name: Bathroom Mirror
  entities:
    - light.bathroom_mirror_1
    - light.bathroom_mirror_2
    - light.bathroom_mirror_3
    - light.bathroom_mirror_4

- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom

- platform: group
  name: Color Lights
  entities:
    - light.kitchen_lights
    - light.liquor_cabinet_lights
    - light.entertainment_lights
    - light.bedroom_lamp
    - light.bedroom_nook

- platform: group
  name: Color Temperature Lights
  entities:
    - light.entryway_lights
    - light.tree_lamp
    - light.nightstand_1
    - light.nightstand_2
    - light.closet_lights
    - light.bathroom_mirror
    - light.shower
    - light.kitchen_lights
    - light.entertainment_lights
    - light.bedroom_lamp
    - light.sunroom_nightstand_lamp
