# Ikea Dioder
- platform: group
  name: Entryway Lights
  unique_id: entryway_lights_group
  entities:
    - light.entryway

- platform: group
  name: Kitchen Lights
  unique_id: kitchen_lights_group
  entities:
    - light.kitchen
    - light.kitchen_cabinet_lights

- platform: group
  name: Living Area Lights
  unique_id: living_area_lights_group
  entities:
    - light.entryway_lights
    - light.kitchen_lights
    - light.living_room_nook
    - light.dining_lights_level
    - light.living_room_lights
    - light.sunroom_lights

- platform: group
  name: Tree Lamp
  unique_id: 'tree_lamp'
  entities:
    - light.tree_lamp_1
    - light.tree_lamp_2
    - light.tree_lamp_3
    - light.tree_lamp_4
    - light.tree_lamp_5

- platform: group
  name: Entertainment Lights
  unique_id: 'entertainment_lights'
  entities:
    - light.entertainment_light_1
    - light.entertainment_light_2

- platform: group
  name: Living Room Lights
  unique_id: living_room_lights_group
  entities:
    - light.living_room

- platform: group
  name: Sunroom Fan Light
  unique_id: 'sunroom_fan_light'
  entities:
    - light.sunroom_fan_light_1
    - light.sunroom_fan_light_2

- platform: group
  name: Sunroom Lights
  unique_id: sunroom_lights_group
  entities:
    - light.sunroom
    - light.sunroom_lamp

- platform: group
  name: Bedroom Lights
  unique_id: 'bedroom_lights_group'
  entities:
    - light.bedroom

- platform: group
  name: Closet Lights
  unique_id: closet_lights_group
  entities:
    - light.closet

- platform: group
  name: Bathroom Mirror
  unique_id: bathroom_mirror
  entities:
    - light.bathroom_mirror_1
    - light.bathroom_mirror_2
    - light.bathroom_mirror_3
    - light.bathroom_mirror_4

- platform: group
  name: Bathroom Lights
  unique_id: bathroom_lights_group
  entities:
    - light.bathroom

- platform: group
  name: Color Lights
  unique_id: color_lights_group
  entities:
    - light.entryway_lights
    - light.kitchen_lights
    - light.entertainment_lights
    - light.sunroom_lights
    - light.closet_light

- platform: group
  name: Color Temperature Lights
  unique_id: color_temperature_lights_group
  entities:
    - light.entryway_lights
    - light.tree_lamp
    - light.nightstand_1
    - light.nightstand_2
    - light.closet_lights
    - light.bathroom_mirror
    - light.shower
    - light.kitchen_lights
    - light.entertainment_lights
    - light.bedroom_lights
    - light.sunroom_lights
