# Ikea Dioder
- platform: mqtt_json
  name: "Liquor cabinet lights"
  state_topic: "home/livingroom/liquorcabinet"
  command_topic: "home/livingroom/liquorcabinet/set"
  brightness: true
  rgb: true
  optimistic: false
  qos: 0
