- platform: plex
  entity_namespace: plex

- platform: universal
  name: Shield
  children:
    - media_player.plex_shield
    - media_player.cast_shield
  commands:
    turn_on:
      service: remote.turn_on
      data:
        entity_id: remote.living_room
        activity: 'Play Shield'
    turn_off:
      service: remote.turn_off
      data:
        entity_id: remote.living_room
    volume_up:
      service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 31874484
        command: VolumeUp
    volume_down:
      service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 31874484
        command: VolumeDown
    volume_mute:
      service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 31874484
        command: Mute
    select_source:
      service: remote.turn_on
      data_template:
        entity_id: remote.living_room
        activity: '{{ source }}'
  attributes:
    state: remote.living_room
    source: remote.living_room|current_activity
    source_list: input_select.living_room_activity|options
