- platform: plex

- platform: androidtv
  entity_namespace: androidtv
  name: SHIELD
  host: SHIELD.singularity.net
  adb_server_ip: adbd
  apps:
    com.google.android.apps.mediashell: Cast
    com.nbcuni.nbc.androidtv: NBC/Universal
    com.hbo.hbonow: HBO Now
    com.jackboxgames.JackboxPartyLoaderFull: Jackbox Party Pack 1
    com.jackboxgames.TJPP3Loader: Jackbox Party Pack 3
    com.jackboxgames.TJPP4Loader: Jackbox Party Pack 4
    com.jackboxgames.TJPP5Loader: Jackbox Party Pack 5
    com.jackboxgames.TJPP6Loader: Jackbox Party Pack 6
    com.espn.score_center: Watch ESPN
    us.zoom.videomeetings: Zoom Meetings
  state_detection_rules:
    'com.google.android.tvlauncher':
      - 'standby'
    'com.netflix.ninja':
      - 'paused':
          'audio_state': 'paused'
      - 'playing':
          'media_session_state': 3
          'wake_lock_size': 3
      - 'standby'
    'com.plexapp.android':
      - 'playing':
          'media_session_state': 3
          'wake_lock_size': 4
      - 'paused':
          'media_session_state': 3
      - 'standby'
    'com.amazon.amazonvideo.livingroom':
      - 'paused':
          'audio_state': 'paused'
      - 'playing':
          'wake_lock_size': 3
      - 'standby'
    'com.espn.score_center':
      - 'paused':
          'audio_state': 'paused'
      - 'playing':
          'wake_lock_size': 3
      - 'standby'
    'us.zoom.videomeetings':
      - 'standby'
    'com.jackboxgames.JackboxPartyLoaderFull':
      - 'standby'
    'com.jackboxgames.TJPP3Loader':
      - 'standby'
    'com.jackboxgames.TJPP4Loader':
      - 'standby'
    'com.jackboxgames.TJPP5Loader':
      - 'standby'
    'com.jackboxgames.TJPP6Loader':
      - 'standby'


- platform: universal
  name: Shield
  children:
    - media_player.plex_shield
    - media_player.cast_shield
    - media_player.androidtv_shield
  commands:
    turn_on:
      service: remote.turn_on
      data:
        entity_id: remote.living_room
        activity: 'Play Shield'
    turn_off:
      service: remote.turn_off
      data:
        entity_id: remote.living_room
    volume_up:
      service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 31874484
        command: VolumeUp
    volume_down:
      service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 31874484
        command: VolumeDown
    volume_mute:
      service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 31874484
        command: Mute
    select_source:
      service: remote.turn_on
      data_template:
        entity_id: remote.living_room
        activity: '{{ source }}'
  attributes:
    state: remote.living_room
    source: remote.living_room|current_activity
    source_list: input_select.living_room_activity|options

- platform: universal
  name: Kitchen Display
  children:
    - media_player.cast_kitchen_display
    - media_player.cast_home_group
    - media_player.cast_everything_group
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_kitchen_display
    turn_off:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_kitchen_display
    volume_set:
      service: media_player.volume_set
      data:
        entity_id: media_player.cast_kitchen_display
        volume_level: '{{ volume_level }}'
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.cast_kitchen_display
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.cast_kitchen_display
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.cast_kitchen_display
  attributes:
    is_volume_muted: media_player.cast_kitchen_display|is_volume_muted
    volume_level: media_player.cast_kitchen_display|volume_level


- platform: universal
  name: Living Room Speaker
  children:
    - media_player.cast_living_room_speaker
    - media_player.cast_entertaining_group
    - media_player.cast_home_group
    - media_player.cast_everything_group
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_living_room_speaker
    turn_off:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_living_room_speaker
    volume_set:
      service: media_player.volume_set
      data:
        entity_id: media_player.cast_living_room_speaker
        volume_level: '{{ volume_level }}'
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.cast_living_room_speaker
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.cast_living_room_speaker
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.cast_living_room_speaker
  attributes:
    is_volume_muted: media_player.cast_living_room_speaker|is_volume_muted
    volume_level: media_player.cast_living_room_speaker|volume_level

- platform: universal
  name: Sunroom
  children:
    - media_player.cast_sunroom
    - media_player.cast_entertaining_group
    - media_player.cast_home_group
    - media_player.cast_everything_group
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_sunroom
    turn_off:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_sunroom
    volume_set:
      service: media_player.volume_set
      data:
        entity_id: media_player.cast_sunroom
        volume_level: '{{ volume_level }}'
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.cast_sunroom
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.cast_sunroom
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.cast_sunroom
  attributes:
    is_volume_muted: media_player.cast_sunroom|is_volume_muted
    volume_level: media_player.cast_sunroom|volume_level

- platform: universal
  name: Bedroom Speaker
  children:
    - media_player.cast_bedroom_speaker
    - media_player.cast_entertaining_group
    - media_player.cast_home_group
    - media_player.cast_everything_group
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_bedroom_speaker
    turn_off:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_bedroom_speaker
    volume_set:
      service: media_player.volume_set
      data:
        entity_id: media_player.cast_bedroom_speaker
        volume_level: '{{ volume_level }}'
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.cast_bedroom_speaker
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.cast_bedroom_speaker
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.cast_bedroom_speaker
  attributes:
    is_volume_muted: media_player.cast_bedroom_speaker|is_volume_muted
    volume_level: media_player.cast_bedroom_speaker|volume_level

- platform: universal
  name: Bathroom Mini
  children:
    - media_player.cast_bathroom_mini
    - media_player.cast_entertaining_group
    - media_player.cast_home_group
    - media_player.cast_everything_group
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_bathroom_mini
    turn_off:
      service: media_player.turn_on
      data:
        entity_id: media_player.cast_bathroom_mini
    volume_set:
      service: media_player.volume_set
      data:
        entity_id: media_player.cast_bathroom_mini
        volume_level: '{{ volume_level }}'
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.cast_bathroom_mini
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.cast_bathroom_mini
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.cast_bathroom_mini
  attributes:
    is_volume_muted: media_player.cast_bathroom_mini|is_volume_muted
    volume_level: media_player.cast_bathroom_mini|volume_level

- platform: universal
  name: Home
  children:
    - media_player.cast_entertaining_group
    - media_player.cast_home_group
    - media_player.cast_everything_group
