- platform: plex
  entity_namespace: plex
- platform: cast
  entity_namespace: cast
- platform: harmony
  host: 'faraday.singularity.net:8282'
  topic_namespace: 'home/harmony/hubs'
  entity_namespace: harmony

- platform: universal
  name: Entertainment Center
  children:
    - media_player.plex_shield
    - media_player.cast_shield
    - media_player.harmony_living_room
  commands:
    turn_on:
      service: media_player.select_source
      data:
        entity_id: media_player.harmony_living_room
        source: 'Play Shield'
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.harmony_living_room
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.harmony_living_room
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.harmony_living_room
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.harmony_living_room
  attributes:
    state: media_player.harmony_living_room
