- platform: pushbullet
  name: pushbullet_jeff
  api_key: !secret pushbullet_key
- platform: slack
  name: slack
  api_key: !secret slack_key
  default_channel: '#bots'
- platform: html5
  name: html5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_project_number

