title: Home
resources:
  - url: /local/ui/more-info-map.js
    type: module
  - url: /local/ui/entity-hidden-filter-card.js
    type: js
  - url: /local/ui/card-tools.js?track=true
    type: js
  - url: /local/ui/vertical-stack-in-card.js?track=true
    type: js
  - url: /local/ui/fold-entity-row.js?track=true
    type: js
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
views:
  - !include /config/lovelace/home.yaml
  - !include /config/lovelace/kitchen.yaml
  - !include /config/lovelace/living-room.yaml
  - !include /config/lovelace/bedroom.yaml
  - !include /config/lovelace/bathroom.yaml
  - !include /config/lovelace/sunroom.yaml
  - !include /config/lovelace/lights.yaml
  - !include /config/lovelace/other.yaml
  - !include /config/lovelace/admin.yaml
