title: Home
resources:
  - url: /local/ui/entity-hidden-filter-card.js
    type: js
  - url: /local/ui/more-info-map.js
    type: module
views:
  - title: Home
    icon: mdi:home
    cards:
      #
      # First column
      #
      - type: vertical-stack
        cards:
          - type: map
            title: Locations
            aspect_ratio: 50%
            entities:
              - entity: device_tracker.jawilson_phone
              - entity: device_tracker.sashag_phone
              - zone.home
              - zone.bline
              - zone.sashas_apartment
              - zone.river
          - type: conditional
            conditions:
              - entity: device_tracker.jawilson_phone
                state: B-Line
            card:
              type: glance
              show_name: false
              column_width: calc(100% / 3)
              entities:
                - sensor.jeff_at_work_this_week
                - sensor.jeff_at_work_today
                - sensor.jeff_leave_work_today
          - type: conditional
            conditions:
              - entity: device_tracker.jawilson_phone
                state: not_home
            card:
              type: glance
              title: Travel Times Home
              show_name: false
              column_width: calc(100% / 3)
              entities:
                - sensor.jeff_drive_home
                - sensor.jeff_transit_home
                - sensor.jeff_walk_home
          - type: entities
            title: Jeff
            show_header_toggle: false
            entities:
              - entity: sensor.google_reverse_geocode_jeff
                name: Location
                secondary_info: last-changed
              - entity: sensor.jeff_sleep_state
                name: Sleeping
              - entity: sensor.jeff_alarm
                name: Alarm
          - type: entities
            title: Sasha
            show_header_toggle: false
            entities:
              - entity: sensor.google_reverse_geocode_sasha
                name: Location
                secondary_info: last-changed
          - type: 'custom:entity-hidden-filter-card'
            entities: !include /config/device_groups/guests.yaml
            show_empty: false
            secondary_info: last-changed
            card:
              type: entities
              title: Guests
              show_header_toggle: false

      #
      # Second column
      #
      - type: vertical-stack
        cards:
          - type: entities
            title: Climate
            show_header_toggle: false
            entities:
              - climate.apartment
              - switch.apartment_home
              - switch.apartment_fan
              - switch.humidifier
              - sensor.apartment_feels_like
              - sensor.apartment_temperatures
              - sensor.apartment_humidities
          - type: entities
            title: Vacuum
            show_header_toggle: false
            entities:
              - entity: vacuum.doomba
                secondary_info: last-changed
              - entity: automation.run_doomba
                name: Automatically Run
              - input_boolean.schedule_vacuum
          - type: media-control
            entity: media_player.cast_home_group

      #
      # Third column
      #
      - type: vertical-stack
        cards:
          - type: entities
            title: Scenes
            show_header_toggle: false
            entities:
              - script.getting_ready
              - scene.couch_reading
              - script.cooking
              - script.dinner
              - scene.tv_dinner
              - scene.romantic
              - script.bedtime
              - type: call-service
                name: Go to sleep
                icon: mdi:sleep
                action_name: Trigger
                service: automation.trigger
                service_data:
                  entity_id: automation.go_to_sleep
              - type: call-service
                name: Lights Out
                icon: mdi:flashlight-off
                action_name: Execute
                service: script.turn_on
                service_data:
                  entity_id: script.lights_out


  - title: Kitchen
    icon: mdi:fridge
    cards:
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - entity: light.kitchen_lights
            name: All lights
          - type: divider
          - light.kitchen
          - light.dining_lights_level
          - type: divider
          - light.kitchen_light_1
          - light.kitchen_light_2
          - light.kitchen_light_3
          - light.kitchen_light_4

      - type: entities
        title: Other Lights
        show_header_toggle: false
        entities:
          - light.entryway
          - type: divider
          - light.entryway_light_1
          - light.entryway_light_2

      - type: entities
        title: Accent Lights
        show_header_toggle: false
        entities:
          - light.liquor_cabinet_lights

      - type: entities
        title: Control
        show_header_toggle: false
        entities:
          - entity: switch.living_area_fluxer
            name: Fluxer
          - entity: script.living_area_wake_up
            name: Wake-Up

      - type: glance
        title: Sensors
        show_name: false
        entities:
          - sensor.living_room_temperature
          - sensor.living_room_relative_humidity

      - type: media-control
        entity: media_player.cast_kitchen


  - title: Living Room
    icon: mdi:sofa
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Lights
            show_header_toggle: false
            entities:
              - entity: light.living_room_lights
                name: All lights
              - type: divider
              - light.entertainment_lights
              - type: divider
              - light.entertainment_light_1
              - light.entertainment_light_2
              - light.living_room_lamp
              - light.desk_lamp

          - type: entities
            title: Other Lights
            entities:
              - light.kitchen_lights
              - light.entryway_lights

          - type: media-control
            entity: media_player.cast_living_room_speaker

      - type: vertical-stack
        cards:
          - type: entities
            title: Harmony
            show_header_toggle: false
            entities:
              - type: custom:hui-toggle-entity-row
                entity: remote.living_room
                secondary_info: last-changed
              - switch.shield
              - switch.xbox_one
              - switch.xbox_360

          - type: media-control
            entity: media_player.shield

      - type: glance
        title: Sensors
        show_name: false
        entities:
          - sensor.living_room_temperature
          - sensor.living_room_relative_humidity

      - type: entities
        title: Control
        show_header_toggle: false
        entities:
          - switch.living_area_fluxer
          - script.living_area_wake_up


  - title: Bedroom
    icon: mdi:hotel
    cards:
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - entity: light.bedroom_lights
            name: All lights
          - type: divider
          - light.tree_lamp
          - type: divider
          - light.tree_lamp_1
          - light.tree_lamp_2
          - light.tree_lamp_3
          - light.tree_lamp_4
          - light.tree_lamp_5
          - light.nightstand_1
          - light.nightstand_2

      - type: entities
        title: Control
        show_header_toggle: false
        entities:
          - entity: switch.humidifier
            name: Humidifier
          - entity: switch.bedroom_fluxer
            name: Fluxer
          - entity: switch.bedroom_motion
            name: Motion
          - type: call-service
            name: Go to sleep
            icon: mdi:sleep
            action_name: Trigger
            service: automation.trigger
            service_data:
              entity_id: automation.go_to_sleep
          - entity: script.bedroom_wake_up
            name: Wake-Up
          - entity: script.sunrise_wake_up
            icon: mdi:weather-sunset-up

      - type: glance
        title: Sensors
        show_name: false
        entities:
          - sensor.bedroom_temperature
          - sensor.bedroom_relative_humidity
          - sensor.bedroom_luminance

      - type: entities
        title: Other Lights
        show_header_toggle: false
        entities:
          - light.closet_light

      - type: entities
        title: Other Control
        show_header_toggle: false
        entities:
          - switch.closet_fluxer
          - entity: switch.closet_motion
            name: Closet Motion
          - script.closet_wake_up

      - type: media-control
        entity: media_player.cast_bedroom_mini


  - title: Bathroom
    icon: mdi:scale-bathroom
    cards:
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - entity: light.bathroom_lights
            name: All Lights
          - type: divider
          - light.bathroom_mirror
          - light.shower_light
          - type: divider
          - light.bathroom_mirror_1
          - light.bathroom_mirror_2
          - light.bathroom_mirror_3
          - light.bathroom_mirror_4

      - type: entities
        title: Control
        show_header_toggle: false
        entities:
          - entity: switch.bathroom_fan_switch
            name: Fan
          - entity: switch.bathroom_fluxer
            name: Fluxer
          - entity: switch.bathroom_motion
            name: Motion
          - entity: script.bathroom_wake_up
            name: Wake-Up

      - type: glance
        title: Sensors
        show_name: false
        entities:
          - sensor.bathroom_temperature
          - sensor.bathroom_relative_humidity
          - sensor.bathroom_luminance

      - type: entities
        title: Other Lights
        show_header_toggle: false
        entities:
          - light.closet_light

      - type: entities
        title: Other Control
        show_header_toggle: false
        entities:
          - switch.closet_fluxer
          - entity: switch.closet_motion
            name: Closet Motion
          - script.closet_wake_up

      - type: media-control
        entity: media_player.cast_bathroom_speaker


  - title: Lights
    icon: mdi:lightbulb
    cards:
      - type: entities
        title: Room Lights
        show_header_toggle: false
        entities:
          - entity: light.entryway_lights
            name: Entryway
          - entity: light.kitchen_lights
            name: Kitchen
          - entity: light.living_area_lights
            name: Living Area
          - entity: light.living_room_lights
            name: Living Room
          - entity: light.bedroom_lights
            name: Bedroom
          - entity: light.closet_lights
            name: Closet
          - entity: light.bathroom_lights
            name: Bathroom

      - type: entities
        title: Light Types
        show_header_toggle: false
        entities:
          - entity: light.color_lights
            name: Color
          - entity: light.color_temperature_lights
            name: Color Temperature

      - type: entities
        title: Fluxers
        entities:
          - entity: switch.bedroom_fluxer
            name: Bedroom
          - entity: switch.closet_fluxer
            name: Closet
          - entity: switch.bathroom_fluxer
            name: Bathroom
          - entity: switch.living_area_fluxer
            name: Living Area

      - type: entities
        title: Motion Automations
        entities:
          - entity: switch.bedroom_motion
            name: Bedroom
          - entity: switch.closet_motion
            name: Closet
          - entity: switch.bathroom_motion
            name: Bathroom

      - type: entities
        title: Wake-Up Scripts
        entities:
          - entity: script.bedroom_wake_up
            name: Bedroom
          - entity: script.closet_wake_up
            name: Closet
          - entity: script.bathroom_wake_up
            name: Bathroom
          - entity: script.living_area_wake_up
            name: Living Area
          - entity: script.living_room_wake_up
            name: Living Room
          - entity: script.apartment_wake_up
            name: Apartment


  - title: Other
    icon: mdi:information
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Temperatures
            show_header_toggle: false
            entities:
              - sensor.dark_sky_temperature
              - sensor.apartment_thermostat_temperature
              - sensor.bathroom_temperature
              - sensor.bedroom_temperature
              - sensor.living_room_temperature

          - type: entities
            title: Humidities
            show_header_toggle: false
            entities:
              - sensor.dark_sky_humidity
              - sensor.apartment_thermostat_humidity
              - sensor.bathroom_relative_humidity
              - sensor.bedroom_relative_humidity
              - sensor.living_room_relative_humidity

      - type: vertical-stack
        cards:
          - type: entities
            title: P3Steel
            show_header_toggle: false
            entities:
              - sensor.p3steel_current_state
              - sensor.p3steel_job_percentage
              - sensor.p3steel_actual_tool0_temp
              - sensor.p3steel_target_tool0_temp
              - sensor.p3steel_actual_bed_temp
              - sensor.p3steel_target_bed_temp
              - binary_sensor.p3steel_printing
              - binary_sensor.p3steel_printing_error

          - type: picture-entity
            entity: camera.p3steel
            camera_image: camera.p3steel
            show_state: false

      - type: entities
        title: UPS
        show_header_toggle: false
        entities:
          - sensor.ups_status
          - sensor.ups_battery
          - sensor.ups_load
          - sensor.ups_time_left


  - title: Admin
    icon: mdi:settings
    cards:
      - type: entities
        title: Scripts
        show_header_toggle: false
        entities:
          - script.bedroom_sleep
          - script.bathroom_sleep
          - script.living_area_sleep
          - script.apartment_sleep
          - script.alarm_ringing
          - script.alarm_snooze
          - script.alarm_dismiss
          - script.bedroom_wake_up
          - script.bathroom_wake_up
          - script.living_area_wake_up
          - script.apartment_wake_up
          - script.nest_home
          - script.bedroom_arrive
          - script.living_area_arrive
          - script.nest_home
          - script.apartment_shutdown

      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - automation.home_assistant_start
          - automation.alarm_bedtime
          - automation.someone_leaves_while_jeff_sleeping
          - automation.alarm_smart_period
          - automation.alarm_ringing
          - automation.alarm_snooze
          - automation.alarm_dismiss
          - automation.wake_up
          - automation.wake_up_bedroom
          - automation.sasha_warm_up
          - automation.sasha_wake_up
          - automation.cancel_wake_up
          - automation.cancel_alarm_ringing
          - automation.cancel_bedroom_wake_up
          - automation.fan_while_showering
          - automation.fan_after_showering
          - automation.limit_bathroom_fan
          - automation.handle_lights_when_leaving
          - automation.nest_away
          - automation.front_door_open
          - automation.handle_lights_when_arriving_home
          - automation.handle_lights_when_turned_on_not_home
          - automation.run_doomba
          - automation.dock_doomba_when_arriving_home
          - automation.notify_doomba_ran
          - automation.notify_doomba_not_docked
          - automation.notify_doomba_error
          - automation.nest_home
          - automation.nest_while_home
          - automation.circulate_air
          - automation.end_circulate_air
          - automation.humidity_too_low
          - automation.humidity_too_high
          - automation.projector_off
          - automation.shield_plex_idle
          - automation.location_update_notification
          - automation.light_intruder_alert
          - automation.motion_intruder_alert
          - automation.update_available_notification
          - automation.jeff_stop_working

      - type: entities
        title: Input boolean
        show_header_toggle: false
        entities:
          - input_boolean.climate_auto
          - input_boolean.guests
          - input_boolean.intruder_alerts
          - input_boolean.media_automation
          - input_boolean.motion
          - input_boolean.presence


excluded_entities: !include /config/www/ui/excluded_entities.yaml
