title: Home
resources:
  - url: /local/ui/more-info-map.js
    type: module
  - url: /local/ui/card-tools.js?v=0.4
    type: js
  - url: /local/ui/entity-hidden-filter-card.js
    type: js
  - url: /local/ui/vertical-stack-in-card.js?v=0.0.9
    type: js
  - url: /local/ui/fold-entity-row.js?v=0
    type: js
views:
  - !include /config/lovelace/home.yaml
  - !include /config/lovelace/kitchen.yaml
  - !include /config/lovelace/living-room.yaml
  - !include /config/lovelace/bedroom.yaml
  - !include /config/lovelace/bathroom.yaml
  - !include /config/lovelace/lights.yaml
  - !include /config/lovelace/other.yaml
  - !include /config/lovelace/admin.yaml

excluded_entities: !include /config/lovelace/excluded-entities.yaml
