"sensor.*_alarm_type":
  ignored: true
"sensor.*_burglar":
  ignored: true
"sensor.*_clock":
  ignored: true
"sensor.*_emergency":
  ignored: true
"sensor.*_power_management":
  ignored: true
"sensor.*_sourcenodeid":
  ignored: true
"sensor.*_system":
  ignored: true
