zwave.sigma_designs_uzb_zwave_usb_adapter:
  ignored: true
binary_sensor.bathroom_sensor:
  ignored: true
sensor.bathroom_general:
  ignored: true
sensor.bathroom_power:
  ignored: true
binary_sensor.bedroom_sensor:
  ignored: true
