zwave.sigma_designs_uzb_zwave_usb_adapter:
  ignored: true
binary_sensor.bathroom_sensor:
  ignored: true
sensor.bathroom_co2_level:
  ignored: true
sensor.bathroom_direction:
  ignored: true
sensor.bathroom_general:
  ignored: true
sensor.bathroom_power:
  ignored: true
binary_sensor.bedroom_sensor:
  ignored: true
sensor.neo_coolcam_doorwindow_detector_access_control:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_doorwindow_detector_alarm_level:
  ignored: true
  polling_intensity: 0
switch.bathroom_fan_switch:
  ignored: false
  polling_intensity: 5
sensor.bathroom_velocity:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_access_control:
  ignored: true
  polling_intensity: 0
sensor.neo_coolcam_door_window_detector_alarm_level:
  ignored: true
  polling_intensity: 0
light.dining_lights_level:
  ignored: false
  polling_intensity: 2
light.kitchen_cabinet_lights:
  ignored: false
  polling_intensity: 2
fan.sunroom:
  ignored: false
  polling_intensity: 5
