zwave.sigma_designs_uzb_zwave_usb_adapter_1:
  ignored: true
binary_sensor.bathroom_sensor_2_0:
  ignored: true
sensor.bathroom_general_2_2:
  ignored: true
sensor.bathroom_power_2_4:
  ignored: true
binary_sensor.bedroom_sensor_3_0:
  ignored: true
