- platform: template
  switches:
    apartment_fan:
      friendly_name: 'HVAC Fan'
      value_template: "{{ is_state_attr('climate.apartment', 'fan_mode', 'On') }}"
      turn_on:
        - service: climate.set_fan_mode
          entity_id: climate.apartment
          data:
            fan_mode: 'On'
        - delay: 00:15
        - service: climate.set_fan_mode
          entity_id: climate.apartment
          data:
            fan_mode: 'Auto'
      turn_off:
        service: climate.set_fan_mode
        entity_id: climate.apartment
        data:
          fan_mode: 'Auto'

- platform: template
  switches:
    apartment_home:
      friendly_name: 'Home'
      value_template: "{{ is_state_attr('climate.apartment', 'away_mode', 'off') }}"
      turn_on:
        service: climate.set_away_mode
        entity_id: climate.apartment
        data:
          away_mode: off
      turn_off:
        service: climate.set_away_mode
        entity_id: climate.apartment
        data:
          away_mode: on
