- platform: template
  switches:
    apartment_fan:
      friendly_name: 'HVAC Fan'
      value_template: "{{ is_state_attr('thermostat.apartment', 'fan', 'on') }}"
      turn_on:
        service: thermostat.set_fan_mode
        entity_id: thermostat.apartment
        data:
          fan: on
      turn_off:
        service: thermostat.set_fan_mode
        entity_id: thermostat.apartment
        data:
          fan: off

- platform: template
  switches:
    apartment_home:
      friendly_name: 'Home'
      value_template: "{{ is_state_attr('thermostat.apartment', 'away_mode', 'off') }}"
      turn_on:
        service: thermostat.set_away_mode
        entity_id: thermostat.apartment
        data:
          away_mode: off
      turn_off:
        service: thermostat.set_away_mode
        entity_id: thermostat.apartment
        data:
          away_mode: on
