- id: run_service
  alias: Run Service
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: run_service
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'RUN_SERVICE'
  action:
    - choose:
        - conditions: "{{ trigger.event.event_type == 'ios.notification_action_fired' }}"
          sequence:
            - service_template: '{{ trigger.event.data.action_data.service }}'
              data_template:
                entity_id: '{{ trigger.event.data.action_data.entity_id }}'
      default:
        - service_template: '{{ trigger.event.data.data.service }}'
          data_template:
            entity_id: '{{ trigger.event.data.data.entity_id }}'
- id: dehydrator_timer
  alias: Dehydrator Timer
  description: ''
  trigger:
  - platform: time
    at: input_datetime.dehydrator_start
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.orvibo
  - delay: '{{ states(''input_number.dehydrator_runtime'') | multiply(3600) | int
      }}'
  - service: switch.turn_off
    target:
      entity_id: switch.orvibo
  - service: notify.jeff_phone
    data:
      title: Dehydrator
      message: 'Dehydration is complete!'
  mode: single
