- alias: Handle lights when leaving
  trigger:
    platform: state
    entity_id: group.everyone
    to: 'not_home'
  condition:
    - condition: state
      entity_id: binary_sensor.guests
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
  action:
    service: script.turn_on
    entity_id: script.apartment_shutdown


- alias: Run Doomba
  trigger:
    - platform: time
      at: '15:30:00'
    - platform: numeric_state
      entity_id: proximity.home
      above: 500
    - platform: state
      entity_id: group.everyone
      to: 'not_home'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.guests
      state: 'off'
    - condition: state
      entity_id: vacuum.doomba
      state: 'off'
      # Only run Doomba ounce every 40 hours max
      for:
        hours: 40
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform != 'numeric_state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'away_from') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'stationary') }}"
  action:
    - service: vacuum.turn_on
      entity_id: vacuum.doomba


- alias: Nest away
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      above: 500
    - platform: state
      entity_id: group.everyone
      to: 'not_home'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.guests
      state: 'off'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'away_from') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'stationary') }}"
  action:
    service: homeassistant.turn_off
    entity_id: switch.apartment_home


- alias: Update Locations
  trigger:
    platform: numeric_state
    entity_id: device_tracker.jawilson_phosphorus
    value_template: >
      {{ (as_timestamp(now()) - as_timestamp(state.last_updated))/60 }}
    above: 30
  action:
    service: script.owntracks_location_update
    data_template:
      user: jawilson
      device: phosphorus
