- alias: Handle lights when leaving
  trigger:
    platform: state
    entity_id: group.everyone
    to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
  action:
    service: script.turn_on
    entity_id: script.apartment_shutdown


- alias: Update Locations
  trigger:
    platform: numeric_state
    entity_id: device_tracker.jawilson_phosphorus
    value_template: >
      {{ (as_timestamp(now()) - as_timestamp(state.last_updated))/60 }}
    above: 30
  action:
    service: script.owntracks_location_update
    data_template:
      user: jawilson
      device: phosphorus
