- alias: Handle lights when leaving
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
    - platform: state
      entity_id: group.wifi_devices
      to: 'not_home'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: binary_sensor.guests
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.apartment_shutdown


- alias: Nest away
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      above: 450
    - platform: state
      entity_id: group.wifi_devices
      to: 'not_home'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.guests
      state: 'off'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'away_from') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'stationary') }}"
  action:
    service: homeassistant.turn_off
    entity_id: switch.apartment_home


- alias: Circulate while away
  trigger:
    - platform: state
      entity_id: switch.apartment_home
      to: 'off'
      for:
        hours: 2
  condition:
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
  action:
    service: script.turn_on
    entity_id: script.cycle_air


- alias: Update Locations
  trigger:
    - platform: numeric_state
      entity_id: device_tracker.jawilson_fluorine
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(state.last_updated))/60 }}
      above: 30
    - platform: numeric_state
      entity_id: device_tracker.annekat_reality
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(state.last_updated))/60 }}
      above: 30
  action:
    service: script.owntracks_location_update
    data_template:
      user: >
        {% if trigger.entity_id == 'device_tracker.jawilson_fluorine' %}
        jawilson
        {% elif trigger.entity_id == 'device_tracker.annekat_reality' %}
        annekat
        {% endif %}
      device: >
        {% if trigger.entity_id == 'device_tracker.jawilson_fluorine' %}
        fluorine
        {% elif trigger.entity_id == 'device_tracker.annekat_reality' %}
        reality
        {% endif %}
