- alias: Handle lights when leaving
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'not_home'
    - platform: state
      entity_id: group.wifi_devices
      state: 'not_home'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: binary_sensor.guests
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.apartment_shutdown


- alias: Nest away
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      above: 500
    - platform: state
      entity_id: group.wifi_devices
      state: 'not_home'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.guests
      state: 'off'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'away_from') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'stationary') }}"
  action:
    service: homeassistant.turn_off
    entity_id: switch.apartment_home


- alias: Circulate while away
  trigger:
    - platform: state
      entity_id: switch.apartment_home
      state: 'off'
      for:
        hours: 2
  condition:
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
  action:
    service: script.turn_on
    entity_id: script.cycle_air
