- alias: Handle lights when leaving
  trigger:
    - platform: state
      entity_id: binary_sensor.presume_home
      to: 'off'
    - platform: state
      entity_id: binary_sensor.apartment_occupied
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
  action:
    service: script.turn_on
    entity_id: script.apartment_shutdown
