- alias: 'Fan While Showering'
  id: fan_while_showering
  trigger:
    platform: state
    entity_id: binary_sensor.showering
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.apartment_occupied
      state: 'on'
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.bathroom_fan_switch


- alias: 'Fan After Showering'
  id: fan_after_showering
  trigger:
    platform: state
    entity_id: binary_sensor.showering
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_fan_switch


- alias: 'Limit Bathroom Fan'
  id: limit_bathroom_fan
  trigger:
    platform: state
    entity_id: switch.bathroom_fan_switch
    to: 'on'
    for:
      minutes: 15
  condition:
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
    - condition: state
      entity_id: binary_sensor.showering
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_fan_switch

- alias: 'Bathroom Light Switch On'
  id: bathroom_light_switch_on
  trigger:
    platform: device
    domain: zha
    device_id: 0900287a0c5d414f8cbd5099baee1b68
    type: remote_button_short_press
    subtype: turn_on
  action:
    - service: light.turn_on
      entity_id: light.bathroom

- alias: 'Bathroom Light Switch Off'
  id: bathroom_light_switch_off
  trigger:
    platform: device
    domain: zha
    device_id: 0900287a0c5d414f8cbd5099baee1b68
    type: remote_button_short_press
    subtype: turn_off
  action:
    - service: light.turn_off
      entity_id: light.bathroom

- alias: 'Bathroom Light Switch Dim Up'
  id: bathroom_light_switch_dim_up
  trigger:
    platform: device
    domain: zha
    device_id: 0900287a0c5d414f8cbd5099baee1b68
    type: remote_button_short_press
    subtype: dim_up
  action:
    - service: light.turn_on
      entity_id: light.bathroom
      data:
        brightness_step_pct: 10

- alias: 'Bathroom Light Switch Dim Down'
  id: bathroom_light_switch_dim_down
  trigger:
    platform: device
    domain: zha
    device_id: 0900287a0c5d414f8cbd5099baee1b68
    type: remote_button_short_press
    subtype: dim_down
  action:
    - service: light.turn_on
      entity_id: light.bathroom
      data:
        brightness_step_pct: -10

- alias: 'Bathroom Light Switch Scene'
  id: bathroom_light_switch_scene
  trigger:
    platform: device
    domain: zha
    device_id: 0900287a0c5d414f8cbd5099baee1b68
    type: remote_button_double_press
    subtype: turn_on
  action:
    - service: input_select.select_next
      entity_id: input_select.bathroom_light_profile

- alias: 'Bathroom Light Scene'
  id: bathroom_light_scene
  trigger:
    - platform: state
      entity_id: input_select.bathroom_light_profile
  action:
    - choose:
      - conditions: >
          {{ trigger.to_state.state == 'Auto' }}
        sequence:
          - service: switch.turn_on
            entity_id: switch.circadian_lighting_bathroom
      - conditions: >
          {{ trigger.to_state.state == 'Daylight' }}
        sequence:
          - service: switch.turn_off
            entity_id: switch.circadian_lighting_bathroom
          - service: light.turn_on
            entity_id: light.bathroom
            data:
              kelvin: 5000
              brightness_pct: 100

- alias: 'Bathroom Light Switch Reset'
  id: bathroom_light_switch_reset
  trigger:
    platform: device
    domain: zha
    device_id: 0900287a0c5d414f8cbd5099baee1b68
    type: remote_button_long_press
    subtype: turn_on
  action:
    - service: input_select.select_option
      entity_id: input_select.bathroom_light_profile
      data:
        option: 'Auto'
    - service: switch.turn_on
      entity_id: switch.bathroom_motion
