- alias: Living Area Fluxer
  trigger:
    - platform: state
      entity_id: group.living_area_fluxer_lights
      to: 'on'
    - platform: state
      entity_id: switch.living_area_fluxer
      to: 'on'
  condition:
    - condition: state
      entity_id: group.living_area_fluxer_lights
      state: 'on'
    - condition: state
      entity_id: switch.living_area_fluxer
      state: 'on'
  action:
    service: switch.living_area_fluxer_update


- alias: Bedroom Fluxer
  trigger:
    - platform: state
      entity_id: group.bedroom_fluxer_lights
      to: 'on'
    - platform: state
      entity_id: switch.bedroom_fluxer
      to: 'on'
  condition:
    - condition: state
      entity_id: group.bedroom_fluxer_lights
      state: 'on'
    - condition: state
      entity_id: switch.bedroom_fluxer
      state: 'on'
  action:
    service: switch.bedroom_fluxer_update


- alias: Bathroom Fluxer
  trigger:
    - platform: state
      entity_id: group.bathroom_fluxer_lights
      to: 'on'
    - platform: state
      entity_id: switch.bathroom_fluxer
      to: 'on'
  condition:
    - condition: state
      entity_id: group.bathroom_fluxer_lights
      state: 'on'
    - condition: state
      entity_id: switch.bathroom_fluxer
      state: 'on'
  action:
    service: switch.bathroom_fluxer_update
