- alias: Force Dining Lights Off
  id: force_dining_lights_off
  initial_state: false
  trigger:
    - platform: state
      entity_id: light.dining_lights_level
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.dining_lights_level

- alias: Force Bathroom Fan Off
  id: force_bathroom_fan_off
  initial_state: false
  trigger:
    - platform: state
      entity_id: switch.bathroom_fan_switch
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_fan_switch

- alias: Force Closet Light Off
  id: force_closet_light_off
  initial_state: false
  trigger:
    - platform: state
      entity_id: light.closet_light
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.closet_light

- alias: Force Kitchen Cabinet Lights Off
  id: force_kitchen_cabinet_lights_off
  initial_state: false
  trigger:
    - platform: state
      entity_id: light.kitchen_cabinet_lights
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.kitchen_cabinet_lights

- alias: Z-Wave Resurrection
  id: zwave_resurrection
  initial_state: false
  trigger:
    - platform: state
      entity_id:
        - sensor.bathroom_fan_node_status
        - sensor.dining_lights_node_status
        - sensor.kitchen_cabinet_node_status
        - sensor.sunroom_fan_node_status
      to: "dead"
      for: "00:02:00"
  action:
    - service: zwave_js.ping
      target:
        entity_id: "{{ trigger.entity_id }}"
