- alias: Handle lights when arriving home
  trigger:
    platform: state
    entity_id: binary_sensor.apartment_occupied
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: script.apartment_shutdown
    - service: script.turn_on
      entity_id:
        - script.living_area_arrive
        - script.bedroom_arrive


- alias: Handle lights when turned on not home
  trigger:
    platform: state
    entity_id: group.all_lights
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: script.apartment_shutdown
    - service: script.turn_on
      entity_id:
        - script.living_area_arrive
        - script.bedroom_arrive


- alias: Front door open
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.apartment_occupied
      state: 'off'
  action:
    - service: automation.trigger
      entity_id: automation.handle_lights_when_arriving_home
    - condition: state
      entity_id: group.family
      state: 'home'
    - service: tts.google_say
      entity_id: media_player.cast_kitchen_display
      data:
        message: 'Welcome home.'
