- alias: Handle lights when arriving home
  trigger:
    platform: state
    entity_id: group.everyone
    to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: script.apartment_shutdown
    - service: script.living_area_arrive
    - service: script.bedroom_arrive


- alias: Handle lights when turned on not home
  trigger:
    platform: state
    entity_id: group.all_lights
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: script.apartment_shutdown
    - service: script.living_area_arrive
    - service: script.bedroom_arrive


- alias: Dock Doomba when arriving home
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      below: 1000
    - platform: state
      entity_id: group.everyone
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'arrived') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
  action:
    service: vacuum.return_to_base
    entity_id: vacuum.doomba


- alias: Nest home
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      below: 1000
    - platform: state
      entity_id: group.everyone
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(states.automation.home_assistant_start.attributes.last_triggered))/60 > 5 }}
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'arrived') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
  action:
    service: script.turn_on
    entity_id: script.nest_home


- alias: Nest while home
  trigger:
    platform: template
    value_template: "{{ is_state_attr('climate.apartment', 'away_mode', 'on') }}"
  condition:
    - condition: state
      entity_id: group.everyone
      state: 'home'
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.apartment_home
