- alias: Handle lights when arriving home
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
  action:
    - service: script.living_area_arrive
    - service: script.bedroom_arrive


- alias: Nest home
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      below: 1000
    - platform: state
      entity_id: group.all_devices
      state: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'arrived') }}"
        - condition: template
          value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
  action:
    service: script.turn_on
    entity_id: script.nest_home


- alias: Nest while home
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('climate.apartment', 'away_mode', 'on') }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: state
        entity_id: input_boolean.climate_auto
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.apartment_home


- alias: Stop circulating
  trigger:
    - platform: state
      entity_id: switch.apartment_home
      state: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
  action:
    service: script.turn_off
    entity_id:
      - script.cycle_air_loop
      - script.cycle_air
