- alias: 'SHIELD Plex Playing'
  trigger:
    - platform: state
      entity_id: media_player.plex_shield
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
  action:
    - service: media_player.stop
      entity_id: media_player.cast_kitchen_home
    - service: light.turn_off
      entity_id:
        - light.kitchen
        - light.dining
        - light.office
    - service: light.turn_off
      entity_id:
        - light.entryway
        - light.bedroom
        - light.bathroom
      data:
        transition: 5
    - service: switch.turn_off
      entity_id: switch.christmas_tree

- alias: 'SHIELD Plex Idle'
  trigger:
    - platform: state
      entity_id: media_player.plex_shield
      to: 'idle'
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: state
      entity_id: switch.shield_audio
      state: 'off'
    - condition: state
      entity_id: group.living_room_lamp
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.living_area_fluxer
    - service: light.turn_on
      entity_id: light.living_room
      data:
        transition: 15
        profile: nightlight

- alias: 'SHIELD Cast Playing'
  trigger:
    - platform: state
      entity_id: media_player.cast_shield
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: state
      entity_id: remote.living_room
      state: 'off'
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: 'Listen to Shield'

- alias: 'SHIELD Cast Stopped'
  trigger:
    - platform: state
      entity_id: media_player.cast_shield
      to: 'off'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: state
      entity_id: switch.shield_audio
      state: 'on'
  action:
    - service: remote.turn_off
      entity_id: remote.living_room

- alias: 'Projector Off'
  trigger:
    - platform: state
      entity_id: remote.living_room
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: template
      value_template: >
        {{ trigger.from_state.attributes.current_activity != 'Listen to Shield' }}
  action:
    - service: light.turn_on
      entity_id: light.living_room
      data:
        transition: 15
        profile: dimmed
    - service: light.turn_on
      entity_id:
        - light.dining
      data_template:
        brightness: >
          {% if is_state('light.dining', 'on') and states.light.dining.attributes.brightness > 100 %}
          {{states.light.dining.attributes.brightness}}
          {% else %}
          100
          {% endif %}
    - service: light.turn_on
      entity_id:
        - light.kitchen
      data_template:
        brightness: >
          {% if is_state('light.kitchen', 'on') and states.light.kitchen.attributes.brightness > 160 %}
          {{states.light.kitchen.attributes.brightness}}
          {% else %}
          160
          {% endif %}
    - delay:
        seconds: 30
    - service: switch.turn_on
      entity_id: switch.living_area_fluxer
    - service: switch.living_area_fluxer_update
