- alias: 'SHIELD Plex Playing'
  id: shield_plex_playing
  trigger:
    - platform: state
      entity_id: media_player.shield
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: template
      value_template: "{{ trigger.from_state.state != 'playing' }}"
  action:
    - service: python_script.shield_plex_playing
    # Turn off the rest of the lights if we haven't started dinner in the last hour
    - condition: template
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(states.script.dinner.attributes.last_triggered)|float)/60 > 60 }}
    - service: light.turn_off
      entity_id: light.living_room_lights

- alias: 'SHIELD Plex Idle'
  id: shield_plex_idle
  trigger:
    - platform: state
      entity_id: media_player.shield
      to: 'idle'
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state.state != 'idle' and trigger.from_state.state != 'unavailable' }}
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: state
      entity_id: light.entertainment_lights
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.tree_lamp_fluxer
        - switch.living_area_fluxer
    - service: light.turn_on
      entity_id: light.living_room_lights
      data:
        profile: nightlight
        transition: 15

- alias: 'Projector Off'
  id: projector_off
  trigger:
    - platform: state
      entity_id: remote.living_room
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
  action:
    - service: python_script.call_service_if_state
      data:
        service: light.turn_on
        state: 'off'
        entity_id:
          - light.living_room_lights
          - light.kitchen_lights
          - light.entryway_lights
        data:
          profile: nightlight
    - service: python_script.call_service_if_state
      data:
        service: light.turn_on
        state: 'off'
        entity_id: light.dining_lights_level
        data:
          brightness_pct: 10
    - service: switch.turn_on
      entity_id:
        - switch.living_area_fluxer
        - switch.bathroom_fluxer
    - service: switch.entryway_fluxer_update
    - service: switch.living_room_fluxer_update
    - service: switch.tree_lamp_fluxer_update
    - service: switch.kitchen_fluxer_update
    - service: switch.dining_fluxer_update

- alias: 'Update Source Select'
  id: update_source_select
  trigger:
    platform: state
    entity_id: remote.living_room
  mode: restart
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.living_room_activity
      option: "{{ trigger.to_state.attributes.current_activity|default('PowerOff') }}"
