- alias: 'SHIELD Plex Playing'
  trigger:
    - platform: state
      entity_id: media_player.plex_shield
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
  action:
    - service: media_player.stop
      entity_id: media_player.cast_kitchen_home
    - service: light.turn_off
      entity_id:
        - light.kitchen_lights
        - light.dining_lights
        - light.office_light
        - light.entryway
        - light.bedroom
        - light.bathroom
        - light.closet
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree
        - switch.cat_water
    # Turn off the rest of the lights if we haven't started dinner in the last hour
    - condition: template
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(states.script.dinner.attributes.last_triggered))/60 > 60 }}
    - service: light.turn_off
      entity_id: group.all_lights

- alias: 'SHIELD Plex Idle'
  trigger:
    - platform: state
      entity_id: media_player.plex_shield
      to: 'idle'
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state.state != 'idle' }}
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: state
      entity_id: switch.shield_audio
      state: 'off'
    - condition: state
      entity_id: light.living_room_lamp
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.living_area_fluxer
    - service: light.turn_on
      entity_id: light.living_room
      data:
        transition: 15
        profile: nightlight

- alias: 'SHIELD Cast Playing'
  trigger:
    - platform: state
      entity_id: media_player.cast_shield
      to: 'playing'
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state.state != 'playing' }}
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: state
      entity_id: remote.living_room
      state: 'off'
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: 'Listen to Shield'

- alias: 'SHIELD Cast Stopped'
  trigger:
    - platform: state
      entity_id: media_player.cast_shield
      to: 'off'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: state
      entity_id: switch.shield_audio
      state: 'on'
  action:
    - service: remote.turn_off
      entity_id: remote.living_room

- alias: 'Projector Off'
  trigger:
    - platform: state
      entity_id: remote.living_room
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.media_automation
      state: 'on'
    - condition: template
      value_template: >
        {{ trigger.from_state.attributes.current_activity != 'Listen to Shield' }}
  action:
    - service: python_script.projector_off
