- alias: 'Living Room Media Players Playing'
  trigger:
    - platform: state
      entity_id:
        - media_player.shield
      to: 'playing'
  action:
    - service: light.turn_off
      entity_id:
        - light.entryway
        - light.bedroom_lamp
        - light.tree_lamp_1
        - light.tree_lamp_2
        - light.tree_lamp_3
        - light.tree_lamp_4
        - light.tree_lamp_5
      data:
        transition: 5
    - service: light.turn_off
      entity_id:
        - light.kitchen
        - light.dining

- alias: 'Living Room Media Players Idle'
  trigger:
    - platform: state
      entity_id:
        - media_player.shield
      to: 'idle'
  condition:
    - condition: state
      entity_id: group.living_room_lamp
      state: 'off'
  action:
    service: light.turn_on
    entity_id: group.living_room_lamp
    data:
      transition: 15
      profile: nightlight

- alias: 'Projector Off'
  trigger:
    - platform: state
      entity_id: switch.projector
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_on
      entity_id: group.living_room_lamp
      data:
        transition: 15
        profile: dimmed
    - service: light.turn_on
      entity_id:
        - light.dining
      data_template:
        brightness: |
          {% if is_state('light.dining', 'on') and states.light.dining.attributes.brightness > 77 %}
          {{states.light.dining.attributes.brightness}}
          {% else %}
          77
          {% endif %}
    - service: light.turn_on
      entity_id:
        - light.kitchen
      data_template:
        brightness: |
          {% if is_state('light.kitchen', 'on') and states.light.kitchen.attributes.brightness > 128 %}
          {{states.light.kitchen.attributes.brightness}}
          {% else %}
          128
          {% endif %}
    - delay:
        seconds: 30
    - service: switch.turn_on
      entity_id: switch.living_area_fluxer
