- alias: 'Slack Updates'
  trigger:
    - platform: state
      entity_id: device_tracker.jawilson_fluorine, device_tracker.annekat_reality
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: >
        {{ trigger.from_state.state != trigger.to_state.state }}
    - condition: template
      value_template: >
        {{ trigger.from_state.state != 'unknown' }}
  action:
    service: notify.slack
    data_template:
      message: >
        {{ trigger.from_state.attributes.friendly_name }}
        {%- if trigger.to_state.state == 'not_home' %}
        left {{ trigger.from_state.state }}
        {%- else %}
        arrived at {{ trigger.to_state.state }}
        {%- endif %}


- alias: 'Slack Light Intruder Alert'
  trigger:
    - platform: state
      entity_id: group.all_lights
      state: 'on'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        minutes: 5
  action:
    service: notify.slack
    data:
      message: >
        Potential entruder, no one is home and a light turned on!

- alias: 'Slack Motion Intruder Alert'
  trigger:
    - platform: event
      event_type: zwave.node_event
      event_data:
        object_id: bathroom_2
        basic_level: 255
    - platform: event
      event_type: zwave.node_event
      event_data:
        object_id: bedroom_3
        basic_level: 255
  condition:
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
  action:
    - delay:
        minutes: 5
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        minutes: 5
    - service: notify.slack
      data_template:
        message: ""
        data:
          attachments:
            - fallback: 'Potential entruder, no one is home and motion was detected'
              color: 'warning'
              author_name: '{{ states.zwave[trigger.event.data.object_id].attributes.friendly_name }}'
              title: 'Potential Intruder Alert!'
              text: 'No one is home and motion was detected'


- alias: New Device Notification
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    service: notify.slack
    data_template:
      message: 'New device detected: {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}})'


- alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.slack
    data_template:
      message: 'Version <{{trigger.to_state.attributes.release_notes}}|{{trigger.to_state.state}}> of Home Assistant is available.'
