- alias: Location Update Notification
  trigger:
    - platform: state
      entity_id: device_tracker.jawilson_phosphorus
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: >
        {{ trigger.from_state.state != trigger.to_state.state }}
    - condition: template
      value_template: >
        {{ trigger.from_state.state != 'unknown' }}
  action:
    service: notify.html5
    data_template:
      title: Location Update
      message: >
        {{ trigger.from_state.attributes.friendly_name }}
        {%- if trigger.to_state.state == 'not_home' %}
        left {{ trigger.from_state.state }}
        {%- else %}
        arrived at {{ trigger.to_state.state }}
        {%- endif %}


- alias: Light Intruder Alert
  trigger:
    - platform: state
      entity_id: group.all_lights
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        minutes: 2
  action:
    - service: notify.html5
      data:
        title: Potential Intruder Alert!
        message: No one is home and a light was turned on

- alias: Motion Intruder Alert
  trigger:
    - platform: state
      entity_id: sensor.bedroom_alarm_level
      from: '0'
    - platform: state
      entity_id: sensor.bathroom_alarm_level
      from: '0'
  condition:
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        seconds: 30
  action:
    - service: notify.html5
      data:
        title: Potential Intruder Alert!
        message: No one is home and motion was detected


- alias: New Device Notification
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.html5_phosphorus
      data_template:
        title: New Device Detected
        message: '{{trigger.event.data.host_name}} with id {{trigger.event.data.entity_id}}'


- alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.html5
    data_template:
      title: 'Home Assistant Update'
      message: 'Version {{trigger.to_state.state}} of Home Assistant is available'
      data:
        url: '{{trigger.to_state.attributes.release_notes}}'
