- alias: 'Slack Updates'
  trigger:
    - platform: state
      entity_id: device_tracker.jawilson_fluorine, device_tracker.annekat_reality
  condition:
    - condition: state
      entity_id: switch.presence
      state: 'on'
    - condition: template
      value_template: >
        {{ trigger.from_state.state != trigger.to_state.state }}
    - condition: template
      value_template: >
        {{ trigger.from_state.state != 'unknown' }}
  action:
    service: notify.slack
    data_template:
      message: >
        {{ trigger.from_state.attributes.friendly_name }}
        {%- if trigger.to_state.state == 'not_home' %}
        left {{ trigger.from_state.state }}
        {%- else %}
        arrived at {{ trigger.to_state.state }}
        {%- endif %}


- alias: MQTT Notification
  trigger:
    platform: mqtt
    topic: notify/#
  action:
    service_template: notify.{{ trigger.topic.split('/')[1] }}
    data_template:
      target: |
        {% if trigger.topic.split('/')[1] == 'slack' %}#{% endif %}
        {% if trigger.topic.split('/')|length <= 2 %}
        {% if trigger.topic.split('/')[1] == 'slack' %}general{% endif %}
        {% else %}
        {{ trigger.topic.split('/')[2] }}
        {% endif %}
      message: >
        {{ trigger.payload }}


- alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.slack
    data:
      message: 'An update for Home Assistant is available.'
