- alias: Location Update Notification
  trigger:
    - platform: state
      entity_id: device_tracker.jawilson_phosphorus
    - platform: state
      entity_id: device_tracker.sashag_iphone
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: >
        {{ trigger.from_state.state != trigger.to_state.state }}
    - condition: template
      value_template: >
        {{ trigger.from_state.state != 'unknown' or trigger.to_state.state != 'not_home' }}
  action:
    service_template: >-
      {% if trigger.entity_id == 'device_tracker.jawilson_phosphorus' -%}
      notify.ios_sashag_iphone
      {%- else -%}
      notify.html5_jawilson_phosphorus
      {%- endif %}
    data_template:
      title: Location Update
      message: >
        {{ trigger.from_state.attributes.friendly_name }}
        {%- if trigger.to_state.state == 'not_home' %}
        left {{ trigger.from_state.state }}
        {%- else %}
        arrived at {{ trigger.to_state.state }}
        {%- endif %}


- alias: Jeff Stop Working
  trigger:
    - platform: numeric_state
      entity_id: sensor.jeff_at_work_today
      above: 8
    - platform: numeric_state
      entity_id: sensor.jeff_at_work_this_week
      above: 40
  action:
    service: notify.html5
    data_template:
      target:
        - jawilson_phosphorus
        - jawilson_work
      title: Time To Head Home
      message: >
        You have been at work for
        {{ states[trigger.to_state.domain][trigger.to_state.object_id].attributes.value }}
        {{ 'today' if trigger.entity_id == 'sensor.jeff_at_work_today' else 'this week' }}
      data:
        requireInteraction: true
        vibrate: [500, 250, 500, 250, 500, 250, 500, 250, 500]
        image: 'https://render.bitstrips.com/v2/cpanel/efd60697-b088-412c-b450-e2d914c2007a-51c44532-b4a5-4f9d-b914-db4ffc9e30c0-v1.png?transparent=1&palette=1'


- alias: Light Intruder Alert
  trigger:
    - platform: state
      entity_id: group.all_lights
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        minutes: 2
  action:
    - service: notify.html5
      data:
        title: Potential Intruder Alert!
        message: No one is home and a light was turned on
        data:
          tag: 'intruder'
          renotify: 1
          service: 'script.turn_on'
          entity_id: 'script.apartment_shutdown'
          actions:
            - action: 'run_service'
              title: 'Turn off'

- alias: Motion Intruder Alert
  trigger:
    - platform: state
      entity_id: sensor.bedroom_alarm_level
      from: '0'
    - platform: state
      entity_id: sensor.bathroom_alarm_level
      from: '0'
  condition:
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        seconds: 30
  action:
    - service: notify.html5
      data:
        title: Potential Intruder Alert!
        message: No one is home and motion was detected


- alias: New Device Notification
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.html5
      data_template:
        title: New Device Detected
        message: '{{trigger.event.data.host_name}} with id {{trigger.event.data.entity_id}}'


- alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.html5
    data_template:
      title: 'Home Assistant Update'
      message: 'Version {{trigger.to_state.state}} of Home Assistant is available'
      data:
        url: '{{trigger.to_state.attributes.release_notes}}'
