- alias: Location Update Notification
  trigger:
    - platform: state
      entity_id: person.jeff
    - platform: state
      entity_id: person.sasha
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: >
        {{ trigger.from_state.state != trigger.to_state.state }}
    - condition: template
      value_template: >
        {{ trigger.from_state.state != 'unknown' or trigger.to_state.state != 'not_home' }}
  action:
    service_template: >-
      {% if trigger.entity_id == 'person.jeff' -%}
      notify.sasha_phone
      {%- else -%}
      notify.jeff_phone
      {%- endif %}
    data_template:
      title: Location Update
      message: >
        {{ trigger.from_state.attributes.friendly_name }}
        {%- if trigger.to_state.state == 'not_home' %}
        left {{ trigger.from_state.state }}
        {%- else %}
        arrived at {{ trigger.to_state.state }}
        {%- endif %}
      data:
        ttl: 7200
        tag: 'location-update'
        channel: Location
        apns_headers:
          'apns-collapse-id': 'location-update'
        push:
          thread-id: 'location-update'


- alias: Jeff Stop Working
  trigger:
    - platform: numeric_state
      entity_id: sensor.jeff_at_work_today
      above: 8
    - platform: numeric_state
      entity_id: sensor.jeff_at_work_this_week
      above: 40
  action:
    service: notify.jeff
    data_template:
      title: Time To Head Home
      message: >
        You have been at work for
        {{ states[trigger.to_state.domain][trigger.to_state.object_id].attributes.value }}
        {{ 'today' if trigger.entity_id == 'sensor.jeff_at_work_today' else 'this week' }}
      data:
        priority: high
        requireInteraction: true
        vibrate: [500, 250, 500, 250, 500, 250, 500, 250, 500]
        image: 'https://render.bitstrips.com/v2/cpanel/efd60697-b088-412c-b450-e2d914c2007a-51c44532-b4a5-4f9d-b914-db4ffc9e30c0-v1.png?transparent=1&palette=1'


- alias: Light Intruder Alert
  trigger:
    - platform: state
      entity_id: group.all_lights
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        minutes: 2
  action:
    - service: notify.jeff
      data:
        title: Potential Intruder Alert!
        message: No one is home and a light was turned on
        data:
          tag: 'intruder'
          channel: Important
          apns_headers:
            'apns-collapse-id': 'intruder'
          renotify: 1
          service: 'script.turn_on'
          entity_id: 'script.apartment_shutdown'
          actions:
            - action: 'run_service'
              title: 'Turn off'

- alias: Motion Intruder Alert
  trigger:
    - platform: state
      entity_id: sensor.bedroom_alarm_level
      from: '0'
    - platform: state
      entity_id: sensor.bathroom_alarm_level
      from: '0'
  condition:
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        seconds: 30
  action:
    - service: notify.jeff
      data:
        title: Potential Intruder Alert!
        message: No one is home and motion was detected


- alias: New Device Notification
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.jeff
      data_template:
        title: New Device Detected
        message: '{{trigger.event.data.host_name}} with id {{trigger.event.data.entity_id}}'
        data:
          priority: high


- alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
    from: 'off'
    to: 'on'
  action:
    service: notify.jeff
    data_template:
      title: 'Home Assistant Update'
      message: 'Version {{trigger.to_state.state}} of Home Assistant is available'
      data:
        url: '{{trigger.to_state.attributes.release_notes}}'

- alias: Heater Circuit Protector
  description: Turns off sunroom heater when it is pulling too much power while the
    projector is on.
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.sunroom_switch_power
      above: 850
    - platform: state
      entity_id: remote.living_room
      from: 'off'
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.sunroom_switch_power
      above: 850
    - condition: state
      entity_id: remote.living_room
      state: 'on'
  action:
    - service: climate.turn_off
      entity_id: climate.sunroom
    - service_template: >
        {% if is_state('person.jeff', 'home') and is_state('person.sasha', 'home') %}
        notify.family
        {%- elif is_state('person.jeff', 'home') %}
        notify.jeff_phone
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: Warning ⚠
        message: >
          The sunroom heater is pulling too much current while the projector
          is on so it has been turned off. Set the sunroom heater to '1', then you
          may turn it back on.
        data:
          tag: heater-circuit-protector
          channel: Important
          apns_headers:
            apns-collapse-id: heater-circuit-protector
          action_data:
            tag: heater-circuit-protector
            service: 'climate.turn_on'
            entity_id: 'climate.sunroom'
          actions:
            - action: run_service
              title: Turn On
          push:
            category: turn_on


- alias: Heater Circuit Protector Callback
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: 'run_service'
        tag: 'heater-circuit-protector'
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'run_service'
        action_data:
          tag: 'heater-circuit-protector'
  action:
    - service: climate.turn_on
      entity_id: climate.sunroom
