- alias: 'Slack Updates'
  trigger:
    - platform: state
      entity_id: device_tracker.jawilson_fluorine, device_tracker.annekat_reality
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: >
        {{ trigger.from_state.state != trigger.to_state.state }}
    - condition: template
      value_template: >
        {{ trigger.from_state.state != 'unknown' }}
  action:
    service: notify.slack
    data_template:
      message: >
        {{ trigger.from_state.attributes.friendly_name }}
        {%- if trigger.to_state.state == 'not_home' %}
        left {{ trigger.from_state.state }}
        {%- else %}
        arrived at {{ trigger.to_state.state }}
        {%- endif %}


- alias: 'Slack Light Intruder Alert'
  trigger:
    - platform: state
      entity_id: group.all_lights
      to: 'on'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        seconds: 30
  action:
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - fallback: 'Potential entruder, no one is home and a light turned on'
              color: 'warning'
              author_name: '{{trigger.to_state.attributes.friendly_name}}'
              title: 'Potential Intruder Alert!'
              text: 'No one is home and a light was turned on'

- alias: 'Slack Motion Intruder Alert'
  trigger:
    - platform: state
      entity_id: sensor.bedroom_alarm_level_3_1
      from: '0'
    - platform: state
      entity_id: sensor.bathroom_alarm_level_2_1
      from: '0'
  condition:
    - condition: state
      entity_id: input_boolean.intruder_alerts
      state: 'on'
    - condition: state
      entity_id: input_boolean.motion
      state: 'on'
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
      for:
        seconds: 30
  action:
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - fallback: 'Potential entruder, no one is home and motion was detected'
              color: 'warning'
              author_name: '{{trigger.to_state.attributes.friendly_name}}'
              title: 'Potential Intruder Alert!'
              text: 'No one is home and motion was detected'


- alias: New Device Notification
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    service: notify.slack
    data_template:
      message: ''
      data:
        attachments:
          - fallback: 'New device detected'
            color: '##808080'
            text: 'New device detected'
            fields:
              - title: 'Host Name'
                value: '{{trigger.event.data.host_name}}'
                short: true
              - title: 'Entity ID'
                value: '{{trigger.event.data.entity_id}}'
                short: true


- alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.slack
    data_template:
      message: 'Version <{{trigger.to_state.attributes.release_notes}}|{{trigger.to_state.state}}> of Home Assistant is available.'
