- alias: 'Fan While Showering'
  trigger:
    platform: state
    entity_id: binary_sensor.showering
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.bathroom_fan_switch


- alias: 'Fan After Showering'
  trigger:
    platform: state
    entity_id: binary_sensor.showering
    to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_fan_switch
