- alias: 'Go to Sleep'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.ak_sleeping
        - binary_sensor.jeff_sleeping
      to: 'on'
  action:
    - service: script.bedroom_sleep
    - service: script.living_area_sleep
    - service: script.apartment_sleep


- alias: 'Wake Up'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.ak_sleeping
        - binary_sensor.jeff_sleeping
      to: 'off'
    - platform: state
      entity_id: group.sleeping
      to: 'off'
  condition:
    - condition: time
      after: '6:00:00'
      before: '9:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.bedroom_wakeup
      data_template:
        target: |
          {% if trigger.entity_id == 'binary_sensor.ak_sleeping' %}
          reality
          {% elif trigger.entity_id == 'binary_sensor.jeff_sleeping' %}
          fluorine
          {% endif %}
    - service: script.living_area_wakeup
    - service: script.apartment_wakeup


- alias: 'Alarm Ringing'
  trigger:
    - platform: state
      entity_id:
        - sensor.ak_alarm
        - sensor.jeff_alarm
      to: 'Ringing'
  action:
    - service: script.alarm_ringing
      data_template:
        light: |
          {% if trigger.entity_id == 'sensor.ak_alarm' %}
          light.tree_lamp_5
          {% elif trigger.entity_id == 'sensor.jeff_alarm' %}
          light.bedroom_lamp
          {% endif %}
        target: |
          {% if trigger.entity_id == 'sensor.ak_alarm' %}
          reality
          {% elif trigger.entity_id == 'sensor.jeff_alarm' %}
          fluorine
          {% endif %}


- alias: 'Alarm Snooze'
  trigger:
    - platform: state
      entity_id:
        - sensor.ak_alarm
        - sensor.jeff_alarm
      to: 'Snoozed'
  action:
    - service: script.alarm_snooze
      data_template:
        light: |
          {% if trigger.entity_id == 'sensor.ak_alarm' %}
          light.tree_lamp_5
          {% elif trigger.entity_id == 'sensor.jeff_alarm' %}
          light.bedroom_lamp
          {% endif %}


- alias: 'Alarm Dismiss'
  trigger:
    - platform: state
      entity_id:
        - sensor.ak_alarm
        - sensor.jeff_alarm
      to: 'Dismissed'
      for:
        seconds: 5
  condition:
    - condition: state
      entity_id: group.sleeping
      state: 'on'
  action:
    - service: script.alarm_dismiss
      data_template:
        light: |
          {% if trigger.entity_id == 'sensor.ak_alarm' %}
          light.tree_lamp_5
          {% elif trigger.entity_id == 'sensor.jeff_alarm' %}
          light.bedroom_lamp
          {% endif %}


- alias: 'Wakup Cancel'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: wakeup_cancel
  action:
    - service: script.wakeup_cancel
      data_template:
        target: '{{ trigger.event.data.target }}'
        script: '{{ trigger.event.data.data.script }}'
