- alias: 'Go to Sleep'
  trigger:
    platform: state
    entity_id: binary_sensor.jeff_sleeping_at_home
    to: 'on'
  action:
    - service: script.turn_off
      entity_id:
        - script.bedroom_wake_up
        - script.closet_wake_up
        - script.bathroom_wake_up
        - script.living_area_wake_up
        - script.living_room_wake_up
        - script.apartment_wake_up
    - service: script.bedroom_sleep
    - service: script.bathroom_sleep
    - service: script.living_area_sleep
    - service: script.apartment_sleep


- alias: 'Someone Leaves While Jeff Sleeping'
  trigger:
    - platform: state
      entity_id: group.guests
      to: 'not_home'
    - platform: state
      entity_id: person.sasha
      from: 'home'
  condition:
    - condition: state
      entity_id: binary_sensor.jeff_sleeping_at_home
      state: 'on'
    - condition: template
      value_template: "{{ not is_state('sensor.jeff_alarm', 'Ringing') }}"
  action:
    - service: script.turn_off
      entity_id:
        - script.bedroom_wake_up
        - script.closet_wake_up
        - script.bathroom_wake_up
        - script.living_area_wake_up
        - script.living_room_wake_up
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: homeassistant.turn_on
      entity_id:
        - switch.bathroom_fluxer
        - automation.bathroom_motion


- alias: 'Wake-Up'
  trigger:
    platform: state
    entity_id: binary_sensor.jeff_sleeping_at_home
    to: 'off'
  condition:
    condition: state
    entity_id: person.jeff
    state: 'home'
  action:
    - service: switch.turn_off
      entity_id:
        - script.bedroom_sleep
        - script.bathroom_sleep
        - script.living_area_sleep
        - script.apartment_sleep
    - service: script.bathroom_wake_up
    - service: script.living_area_wake_up
    - service: script.apartment_wake_up
    # Provide a way to cancel
    - service_template: >
        {% if is_state('person.jeff', 'home') and is_state('person.sasha', 'home') %}
        notify.family_phones
        {%- elif is_state('person.jeff', 'home') %}
        notify.jeff_phone
        {%- elif is_state('person.sasha', 'home') %}
        notefiy.sasha_phone
        {%- endif %}
      data:
        title: 'Good Morning!'
        message: 'Turning on the apartment lights'
        data:
          tag: 'wake-up'
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'wake_up_bedroom'
              title: 'Wake-Up Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'non_bedroom_wake_up'
    - condition: time
      after: '5:00:00'
      before: '10:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.jawilson_office_closed
      state: 'off'
    - condition: template
      value_template: >
        {{ as_timestamp(state_attr('calendar.sashag_school_start', 'start_time')) == None or
            as_timestamp(state_attr('calendar.sashag_school_end', 'end_time'))|default(0, true) < as_timestamp(state_attr('calendar.sashag_school_start', 'start_time')) }}
    - service: script.closet_wake_up
    - service: script.bedroom_wake_up
    - service_template: >
        {% if is_state('person.jeff', 'home') and is_state('person.sasha', 'home') %}
        notify.family_phones
        {%- elif is_state('person.jeff', 'home') %}
        notify.jeff_phone
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: 'Good Morning!'
        message: 'Turning on the bedroom and apartment lights'
        data:
          tag: 'wake-up'
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'cancel_bedroom_wake_up'
              title: 'Cancel Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'wake_up'


- alias: 'Sasha Warm-Up'
  trigger:
    platform: time
    at: '05:30:00'
  condition:
    - condition: state
      entity_id: person.sasha
      state: 'home'
    - condition: template
      value_template: "{{ not is_state('person.jeff', 'home') }}"
    - condition: template
      value_template: "{{ as_timestamp(now()) < as_timestamp(state_attr('calendar.sashag_school_end', 'end_time'))|default(0, true) }}"
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
  action:
    - service: script.apartment_wake_up


- alias: 'Sasha Wake-Up'
  trigger:
    platform: state
    entity_id: light.bathroom_mirror_1
    to: 'on'
  condition:
    - condition: state
      entity_id: script.bathroom_wake_up
      state: 'off'
    - condition: state
      entity_id: person.sasha
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.jeff_sleeping_at_home
          state: 'on'
        - condition: template
          value_template: "{{ not is_state('person.jeff', 'home') }}"
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '4:00:00'
      before: '7:30:00'
  action:
    - service: switch.turn_off
      entity_id:
        - script.bathroom_sleep
        - script.living_area_sleep
    # Provide a way to cancel
    - service_template: >
        {% if is_state('person.jeff', 'home') %}
        notify.family_phones
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: 'Good Morning!'
        message: 'Sasha is waking up'
        data:
          tag: 'wake-up'
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'cancel_bedroom_wake_up'
              title: 'Cancel Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'wake_up'
    - service: script.bathroom_wake_up
    - service: script.closet_wake_up
    - service: script.living_area_wake_up
    - service: switch.turn_off
      entity_id: switch.bedroom_fluxer
    - service: light.turn_on
      entity_id: light.nightstand_2
      data:
        color_temp: 450
        brightness: 10
    - service: script.apartment_wake_up
    - condition: template
      value_template: "{{ not is_state('person.jeff', 'home') }}"
    - service: script.bedroom_wake_up


- alias: 'Alarm Bedtime'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Bedtime'
  condition:
    condition: state
    entity_id: person.jeff
    state: 'home'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.apartment
        target_temp_high: 70
        temperature: 70
        target_temp_low: 60


- alias: 'Alarm Smart Period'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Smart period'
  condition:
    condition: state
    entity_id: person.jeff
    state: 'home'
  action:
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
    - service: climate.set_temperature
      data:
        entity_id: climate.apartment
      data_template:
        target_temp_high: "{{ states('input_number.default_high_temp')|int }}"
        temperature: "{{ states('input_number.default_low_temp')|int if is_state('climate.apartment', 'heat') else states('input_number.default_high_temp')|int }}"
        target_temp_low: "{{ states('input_number.default_low_temp')|int }}"


- alias: 'Alarm Ringing'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Ringing'
  condition:
    condition: state
    entity_id: person.jeff
    state: 'home'
  action:
    service: script.alarm_ringing
    data:
      light: light.nightstand_1
      target: jawilson_phone


- alias: 'Alarm Snooze'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Snoozed'
  condition:
    condition: state
    entity_id: person.jeff
    state: 'home'
  action:
    service: script.alarm_snooze
    data:
      light: light.nightstand_1


- alias: 'Alarm Dismiss'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Dismissed'
    for:
      seconds: 5
  condition:
    - condition: state
      entity_id: person.jeff
      state: 'home'
    - condition: state
      entity_id: script.bedroom_wake_up
      state: 'off'
  action:
    service: script.alarm_dismiss
    data_template:
      light: light.nightstand_1


- alias: 'Cancel Alarm Ringing'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: alarm_ringing_cancel
  action:
    - service: script.turn_off
      entity_id: script.alarm_ringing
    - service: script.bedroom_sleep


- alias: 'Cancel Bedroom Wake-Up'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: cancel_bedroom_wake_up
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'CANCEL_BEDROOM_WAKE_UP'
  action:
    - service_template: >
        {% if is_state('person.jeff', 'home') and is_state('person.sasha', 'home') %}
        notify.family_phones
        {%- elif is_state('person.jeff', 'home') %}
        notify.jeff_phone
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: 'Sorry!'
        message: Turning the lights back off
        data:
          tag: 'wake-up'
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'wake_up_bedroom'
              title: 'Wake-Up Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'non_bedroom_wake_up'
    - service: script.turn_off
      entity_id: script.bedroom_wake_up
    - service: script.turn_off
      entity_id: script.closet_wake_up
    - service: script.turn_off
      entity_id: script.sunrise_wake_up
    - service: script.bedroom_sleep


- alias: 'Wake-Up Bedroom'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: wake_up_bedroom
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'WAKE_UP_BEDROOM'
  action:
    - service: script.closet_wake_up
    - service: script.bedroom_wake_up
    - service_template: >
        {% if is_state('person.jeff', 'home') and is_state('person.sasha', 'home') %}
        notify.family_phones
        {%- elif is_state('person.jeff', 'home') %}
        notify.jeff_phone
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: 'Good Morning!'
        message: 'Turning on the bedroom and apartment lights'
        data:
          tag: 'wake-up'
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'cancel_bedroom_wake_up'
              title: 'Cancel Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'wake_up'


- alias: 'Cancel Wake-Up'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: cancel_wake_up
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'CANCEL_WAKE_UP'
  action:
    - service: script.turn_off
      entity_id:
        - script.bedroom_wake_up
        - script.closet_wake_up
        - script.bathroom_wake_up
        - script.living_area_wake_up
        - script.living_room_wake_up
        - script.apartment_wake_up
    - service: script.bedroom_sleep
    - service: script.bathroom_sleep
    - service: script.living_area_sleep
