- alias: 'Go to Sleep'
  trigger:
    - platform: state
      entity_id: binary_sensor.jeff_sleeping_at_home
      to: 'on'
    - platform: template
      value_template: "{{ is_state_attr('sensor.bedroom_speaker_alarms', 'next_alarm_status', 'set') }}"
  action:
    - service: script.turn_off
      entity_id:
        - script.bedroom_wake_up
        - script.closet_wake_up
        - script.bathroom_wake_up
        - script.living_area_wake_up
        - script.living_room_wake_up
        - script.apartment_wake_up
    - service: script.turn_on
      entity_id:
        - script.bedroom_sleep
        - script.bathroom_sleep
        - script.living_area_sleep
        - script.apartment_sleep


- alias: 'Someone Leaves While Jeff Sleeping'
  trigger:
    - platform: state
      entity_id: group.guests
      to: 'not_home'
    - platform: state
      entity_id: person.sasha
      from: 'home'
  condition:
    - condition: state
      entity_id: binary_sensor.jeff_sleeping_at_home
      state: 'on'
    - "{{ not is_state('sensor.jeff_alarm', 'Ringing') }}"
    - "{{ not is_state_attr('sensor.bedroom_speaker_alarms', 'next_alarm_status', 'ringing') }}"
  action:
    - service: script.turn_off
      entity_id:
        - script.bedroom_wake_up
        - script.closet_wake_up
        - script.bathroom_wake_up
        - script.living_area_wake_up
        - script.living_room_wake_up
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: homeassistant.turn_on
      entity_id:
        - switch.bathroom_fluxer
        - automation.bathroom_motion


- alias: 'Wake-Up'
  trigger:
    - platform: state
      entity_id: binary_sensor.jeff_sleeping_at_home
      to: 'off'
    - platform: template
      value_template: "{{ is_state_attr('sensor.bedroom_speaker_alarms', 'next_alarm_status', 'none') }}"
  condition:
    - "{{ trigger.entity_id == 'sensor.bedroom_speaker_alarms' or is_state('person.jeff', 'home') }}"
  action:
    - service: script.turn_off
      entity_id:
        - script.bedroom_sleep
        - script.bathroom_sleep
        - script.living_area_sleep
        - script.apartment_sleep
    - service: script.turn_on
      entity_id:
        - script.bathroom_wake_up
        - script.living_area_wake_up
        - script.apartment_wake_up
    - choose:
      - conditions: "{{ is_state('script.apartment_wake_up', 'off') }}"
        sequence:
          service: script.turn_on
          entity_id: script.apartment_wake_up
    - service: notify.jeff_phone
      data:
        message: clear_notification
        data:
          tag: 'alarm-ringing'
    # Provide a way to cancel
    - service_template: >
        {% if is_state('person.jeff', 'home') and is_state('person.sasha', 'home') %}
        notify.family_phones
        {%- elif is_state('person.jeff', 'home') %}
        notify.jeff_phone
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: 'Good Morning!'
        message: 'Turning on the apartment lights'
        data:
          tag: 'wake-up'
          channel: Wake-Up
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'wake_up_bedroom'
              title: 'Wake-Up Bedroom'
            - action: 'reset_bedroom'
              title: 'Reset Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'non_bedroom_wake_up'
    - condition: and
      conditions:
        - condition: time
          after: '5:00:00'
          before: '10:00:00'
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - "{{ as_timestamp(state_attr('calendar.sashag_school_end', 'end_time')) != None }}"
        - "{{ as_timestamp(state_attr('calendar.sashag_school_start', 'start_time')) == None or
                as_timestamp(state_attr('calendar.sashag_school_end', 'end_time')) < as_timestamp(state_attr('calendar.sashag_school_start', 'start_time')) }}"
    - service: script.turn_on
      entity_id:
        - script.closet_wake_up
        - script.bedroom_wake_up
    - service_template: >
        {% if is_state('person.jeff', 'home') and is_state('person.sasha', 'home') %}
        notify.family_phones
        {%- elif is_state('person.jeff', 'home') %}
        notify.jeff_phone
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: 'Good Morning!'
        message: 'Turning on the bedroom and apartment lights'
        data:
          tag: 'wake-up'
          channel: Wake-Up
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'cancel_bedroom_wake_up'
              title: 'Cancel Bedroom'
            - action: 'reset_bedroom'
              title: 'Reset Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'wake_up'


- alias: 'Sasha Warm-Up'
  trigger:
    platform: time
    at: '05:30:00'
  condition:
    - condition: state
      entity_id: person.sasha
      state: 'home'
    - "{{ not is_state('person.jeff', 'home') }}"
    - "{{ as_timestamp(now()) < as_timestamp(state_attr('calendar.sashag_school_end', 'end_time'))|default(0, true) }}"
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.apartment_wake_up


- alias: 'Sasha Wake-Up'
  trigger:
    platform: state
    entity_id: light.bathroom_mirror_1
    to: 'on'
  condition:
    - condition: state
      entity_id: script.bathroom_wake_up
      state: 'off'
    - condition: state
      entity_id: person.sasha
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.jeff_sleeping_at_home
          state: 'on'
        - "{{ not is_state('person.jeff', 'home') }}"
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '4:00:00'
      before: '7:30:00'
  action:
    - service: script.turn_off
      entity_id:
        - script.bathroom_sleep
        - script.living_area_sleep
    - service: notify.jeff_phone
      data:
        message: clear_notification
        data:
          tag: 'alarm-ringing'
    # Provide a way to cancel
    - service_template: >
        {% if is_state('person.jeff', 'home') %}
        notify.family_phones
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: 'Good Morning!'
        message: 'Sasha is waking up'
        data:
          tag: 'wake-up'
          channel: Wake-Up
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'cancel_bedroom_wake_up'
              title: 'Cancel Bedroom'
            - action: 'reset_bedroom'
              title: 'Reset Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'wake_up'
    - service: script.turn_on
      entity_id:
        - script.bathroom_wake_up
        - script.closet_wake_up
        - script.living_area_wake_up
    - service: switch.turn_off
      entity_id: switch.bedroom_fluxer
    - service: light.turn_on
      entity_id: light.nightstand_2
      data:
        color_temp: 450
        brightness: 10
    - service: script.turn_on
      entity_id: script.apartment_wake_up
    - condition: template
      value_template: "{{ not is_state('person.jeff', 'home') }}"
    - service: script.turn_on
      entity_id: script.bedroom_wake_up


- alias: 'Bedtime Cooldown'
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.jeff_alarm
      to: 'Bedtime'
    - platform: numeric_state
      entity_id:
        - sensor.jawilson_phone_next_alarm
        - sensor.time
        - input_number.bedtime_cooldown_hours
      value_template: "{{ 24 if states('sensor.jawilson_phone_next_alarm') == 'unknown' else (states('sensor.jawilson_phone_next_alarm')|as_timestamp - states.sensor.time.last_changed|as_timestamp)/60/60 }}"
      below: input_number.bedtime_cooldown_hours
  condition:
    - condition: state
      entity_id: person.jeff
      state: 'home'
    - condition: state
      entity_id: binary_sensor.jeff_sleeping
      state: 'off'
    - condition: numeric_state
      entity_id:
        - sensor.jawilson_phone_next_alarm
        - input_number.apartment_wakeup_period
      value_template: >
        {{ 0 if states('sensor.jawilson_phone_next_alarm') == 'unknown' else (states('sensor.jawilson_phone_next_alarm')|as_timestamp - states.sensor.time.last_changed|as_timestamp)/60 }}
      above: input_number.apartment_wakeup_period
  action:
    - condition: or
      conditions:
        - "{{ state_attr('climate.apartment', 'temperature') and state_attr('climate.apartment', 'temperature') > 70 }}"
        - "{{ state_attr('climate.apartment', 'target_temp_high') and state_attr('climate.apartment', 'target_temp_high') > 70 }}"
        - "{{ state_attr('climate.apartment', 'target_temp_low') and state_attr('climate.apartment', 'target_temp_low') > 60 }}"
    - service: notify.jeff_phone
      data:
        title: 'Bedtime Cooldown'
        message: 'Good evening, cooling down the apartment in 5 minutes...'
        data:
          timeout: 300
          tag: 'evening-cooldown'
          actions:
            - action: 'bedtime_cooldown'
              title: 'Cool Down Now'
            - action: 'cancel_bedtime_cooldown'
              title: 'Cancel'
    - wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: bedtime_cooldown
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: cancel_bedtime_cooldown
      timeout:
        minutes: 5
    - condition: template
      value_template: >
        "{{ wait.trigger == None or wait.trigger.event.data.action == bedtime_cooldown }}"
    - service: climate.set_temperature
      data:
        entity_id: climate.apartment
      data_template:
        target_temp_high: "{{ state_attr('climate.apartment', 'target_temp_high')|default(70, True)|min(70) }}"
        temperature: "{{ state_attr('climate.apartment', 'temperature')|default(70, True)|min(70) }}"
        target_temp_low: "{{ state_attr('climate.apartment', 'target_temp_low')|default(60, True)|min(60) }}"
    - service: notify.jeff_phone
      data:
        message: clear_notification
        data:
          tag: 'evening-cooldown'


- alias: 'Alarm Smart Period'
  trigger:
    - platform: state
      entity_id: sensor.jeff_alarm
      to: 'Smart Period'
    - platform: numeric_state
      entity_id:
        - sensor.jawilson_phone_next_alarm
        - sensor.time
        - input_number.apartment_wakeup_period
      value_template: >
        {{ 1440 if states('sensor.jawilson_phone_next_alarm') == 'unavailable' else (states('sensor.jawilson_phone_next_alarm')|as_timestamp - states.sensor.time.last_changed|as_timestamp)/60 }}
      below: input_number.apartment_wakeup_period
  condition:
    condition: state
    entity_id: person.jeff
    state: 'home'
  action:
    - condition: state
      entity_id: input_boolean.climate_auto
      state: 'on'
    - service: script.turn_on
      entity_id: script.apartment_wake_up


- alias: 'Alarm Ringing'
  trigger:
    - platform: state
      entity_id: sensor.jeff_alarm
      to: 'Ringing'
    - platform: template
      value_template: "{{ is_state_attr('sensor.bedroom_speaker_alarms', 'next_alarm_status', 'ringing') }}"
  condition:
    - "{{ trigger.entity_id == 'sensor.bedroom_speaker_alarms' or is_state('person.jeff', 'home') }}"
  action:
    - service: script.turn_on
      entity_id: script.alarm_ringing
      data:
        variables:
          light: light.nightstand_1
          target: jawilson_phone


- alias: 'Alarm Snooze'
  trigger:
    - platform: state
      entity_id: sensor.jeff_alarm
      to: 'Snoozed'
    - platform: template
      value_template: "{{ is_state_attr('sensor.bedroom_speaker_alarms', 'next_alarm_status', 'snoozed') }}"
  condition:
    - "{{ trigger.entity_id == 'sensor.bedroom_speaker_alarms' or is_state('person.jeff', 'home') }}"
  action:
    - service: script.turn_on
      entity_id: script.alarm_snooze
      data:
        variables:
          light: light.nightstand_1
    - service: notify.jeff_phone
      data:
        message: clear_notification
        data:
          tag: 'alarm-ringing'


- alias: 'Alarm Dismiss'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Dismissed'
    for:
      seconds: 5
  condition:
    - condition: state
      entity_id: person.jeff
      state: 'home'
    - condition: state
      entity_id: script.bedroom_wake_up
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.alarm_dismiss
      data:
        variables:
          light: light.nightstand_1
    - service: notify.jeff_phone
      data:
        message: clear_notification
        data:
          tag: 'alarm-ringing'


- alias: 'Cancel Alarm Ringing'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: alarm_ringing_cancel
  action:
    - service: script.turn_off
      entity_id: script.alarm_ringing
    - service: script.turn_on
      entity_id: script.bedroom_sleep


- alias: 'Cancel Bedroom Wake-Up'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: cancel_bedroom_wake_up
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'CANCEL_BEDROOM_WAKE_UP'
  action:
    - service_template: >
        {% if is_state('person.jeff', 'home') and is_state('person.sasha', 'home') %}
        notify.family_phones
        {%- elif is_state('person.jeff', 'home') %}
        notify.jeff_phone
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: 'Sorry!'
        message: Turning the lights back off
        data:
          tag: 'wake-up'
          channel: Wake-Up
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'wake_up_bedroom'
              title: 'Wake-Up Bedroom'
            - action: 'reset_bedroom'
              title: 'Reset Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'non_bedroom_wake_up'
    - service: script.turn_off
      entity_id:
        - script.bedroom_wake_up
        - script.closet_wake_up
        - script.sunrise_wake_up
    - service: script.turn_on
      entity_id: script.bedroom_sleep


- alias: 'Wake-Up Bedroom'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: wake_up_bedroom
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'WAKE_UP_BEDROOM'
  action:
    - service: script.turn_on
      entity_id:
        - script.closet_wake_up
        - script.bedroom_wake_up
    - service_template: >
        {% if is_state('person.jeff', 'home') and is_state('person.sasha', 'home') %}
        notify.family_phones
        {%- elif is_state('person.jeff', 'home') %}
        notify.jeff_phone
        {%- elif is_state('person.sasha', 'home') %}
        notify.sasha_phone
        {%- endif %}
      data:
        title: 'Good Morning!'
        message: 'Turning on the bedroom and apartment lights'
        data:
          tag: 'wake-up'
          channel: Wake-Up
          apns_headers:
            'apns-collapse-id': 'wake-up'
          actions:
            - action: 'cancel_bedroom_wake_up'
              title: 'Cancel Bedroom'
            - action: 'reset_bedroom'
              title: 'Reset Bedroom'
            - action: 'cancel_wake_up'
              title: 'Cancel All'
          push:
            category: 'wake_up'


- alias: 'Reset Bedroom'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: reset_bedroom
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'RESET_BEDROOM'
  action:
    - service: script.turn_off
      entity_id:
        - script.bedroom_wake_up
        - script.closet_wake_up
    - service: script.turn_on
      entity_id:
        - script.bedroom_reset
        - script.closet_reset


- alias: 'Cancel Wake-Up'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: cancel_wake_up
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'CANCEL_WAKE_UP'
  action:
    - service: script.turn_off
      entity_id:
        - script.bedroom_wake_up
        - script.closet_wake_up
        - script.bathroom_wake_up
        - script.living_area_wake_up
        - script.living_room_wake_up
        - script.apartment_wake_up
    - service: script.turn_on
      entity_id:
        - script.bedroom_sleep
        - script.bathroom_sleep
        - script.living_area_sleep
