- alias: 'Go to Sleep'
  trigger:
    platform: state
    entity_id: binary_sensor.jeff_sleeping_at_home
    to: 'on'
  action:
    - service: script.turn_off
      entity_id:
        - script.bedroom_wakeup
        - script.living_area_wakeup
        - script.apartment_wakeup
    - service: script.bedroom_sleep
    - service: script.bathroom_sleep
    - service: script.living_area_sleep
    - service: script.apartment_sleep


- alias: 'Guests Leave While Sleeping'
  trigger:
    platform: state
    entity_id: group.all_guests
    to: 'not_home'
  condition:
    - condition: state
      entity_id: binary_sensor.jeff_sleeping_at_home
      state: 'on'
    - condition: template
      value_template: "{{ not is_state('sensor.jeff_alarm', 'Ringing') }}"
  action:
    - service: script.turn_off
      entity_id:
        - script.bathroom_wakeup
        - script.living_area_wakeup
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: homeassistant.turn_on
      entity_id:
        - switch.bathroom_fluxer
        - automation.bathroom_motion


- alias: 'Wake Up'
  trigger:
    platform: state
    entity_id: binary_sensor.jeff_sleeping_at_home
    to: 'off'
  condition:
    condition: state
    entity_id: device_tracker.jawilson_phosphorus
    state: 'home'
  action:
    - service: switch.turn_off
      entity_id:
        - script.bedroom_sleep
        - script.bathroom_sleep
        - script.living_area_sleep
        - script.apartment_sleep
    - service: script.bathroom_wakeup
    - service: script.living_area_wakeup
    - service: script.apartment_wakeup
  # Provide a way to cancel
  - service: notify.html5
    data:
      target: phosphorus
      title: 'Good Morning!'
      message: 'Turning on the bedroom lights'
      data:
        tag: 'wakeup'
        renotify: false
        actions:
          - action: 'cancel_bedroom_wakeup'
            title: 'Cancel Bedroom'
          - action: 'cancel_wakeup'
            title: 'Cancel All'
    - condition: time
      after: '6:00:00'
      before: '10:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - service: script.bedroom_wakeup
      data:
        target: phosphorus


- alias: 'Guest Wake Up'
  trigger:
    platform: state
    entity_id: light.bathroom
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.jeff_sleeping_at_home
      state: 'on'
    - condition: state
      entity_id: group.other_guests
      state: 'home'
    - condition: time
      after: '6:15:00'
      before: '9:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_off
      entity_id:
        - script.bathroom_sleep
        - script.living_area_sleep
  # Provide a way to cancel
  - service: notify.html5
    data:
      target: phosphorus
      title: 'Good Morning!'
      message: 'Guests are waking up'
      data:
        tag: 'wakeup'
        renotify: false
        actions:
          - action: 'cancel_bedroom_wakeup'
            title: 'Cancel Bedroom'
          - action: 'cancel_wakeup'
            title: 'Cancel All'
    - service: script.bathroom_wakeup
    - service: script.living_area_wakeup
    - service: switch.turn_off
      entity_id: switch.bedroom_fluxer
    - service: light.turn_on
      entity_id: light.nightstand_2
      data:
        color_temp: 450
        brightness: 10


- alias: 'Awake'
  trigger:
    platform: state
    entity_id: binary_sensor.jeff_sleeping_at_home
    to: 'off'
    for:
      hours: 1
  action:
    service: switch.turn_on
    entity_id:
      - switch.bathroom_fluxer
      - switch.bedroom_fluxer
      - switch.bathroom_motion
      - switch.bedroom_motion


- alias: 'Alarm Bedtime'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Bedtime'
  condition:
    condition: state
    entity_id: device_tracker.jawilson_phosphorus
    state: 'home'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.apartment
        target_temp_high: 70
        temperature: 70
        target_temp_low: 60


- alias: 'Alarm Smart Period'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Smart period'
  condition:
    condition: state
    entity_id: device_tracker.jawilson_phosphorus
    state: 'home'
  action:
    service: script.apartment_wakeup


- alias: 'Alarm Ringing'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Ringing'
  condition:
    condition: state
    entity_id: device_tracker.jawilson_phosphorus
    state: 'home'
  action:
    service: script.alarm_ringing
    data:
      light: light.nightstand_1
      target: phosphorus


- alias: 'Alarm Snooze'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Snoozed'
  condition:
    condition: state
    entity_id: device_tracker.jawilson_phosphorus
    state: 'home'
  action:
    service: script.alarm_snooze
    data:
      light: light.nightstand_1


- alias: 'Alarm Dismiss'
  trigger:
    platform: state
    entity_id: sensor.jeff_alarm
    to: 'Dismissed'
    for:
      seconds: 5
  condition:
    - condition: state
      entity_id: device_tracker.jawilson_phosphorus
      state: 'home'
    - condition: state
      entity_id: script.bedroom_wakeup
      state: 'off'
  action:
    service: script.alarm_dismiss
    data_template:
      light: light.nightstand_1


- alias: 'Cancel Alarm Ringing'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: alarm_ringing_cancel
  action:
    - service: notify.html5
      data_template:
        target: '{{ trigger.event.data.target }}'
      data:
        title: 'Sorry!'
        message: Turning the lights back off
        data:
          tag: 'wakeup'
          renotify: false
    - service: script.bedroom_sleep


- alias: 'Cancel Bedroom Wakeup'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: cancel_bedroom_wakeup
  action:
    - service: notify.html5
      data_template:
        target: '{{ trigger.event.data.target }}'
      data:
        title: 'Sorry!'
        message: Turning the lights back off
        data:
          tag: 'wakeup'
          renotify: false
        actions:
          - action: 'cancel_wakeup'
            title: 'Cancel All'
    - service: script.turn_off
      entity_id: script.bedroom_wakeup
    - service: script.bedroom_sleep


- alias: 'Cancel Wakeup'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: cancel_wakeup
  action:
    - service: notify.html5
      data_template:
        target: '{{ trigger.event.data.target }}'
      data:
        title: 'Sorry!'
        message: Turning the lights back off
        data:
          tag: 'wakeup'
          renotify: false
    - service: script.turn_off
      entity_id:
        - script.bedroom_wakeup
        - script.living_area_wakeup
        - script.apartment_wakeup
    - service: script.bedroom_sleep
