- alias: Home Assistant Start
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.jawilson_phosphorus_location_update
    - service: automation.turn_off
      entity_id:
        - automation.motion_intruder_alert
        - automation.location_update_notification
        - automation.handle_lights_when_turned_on_not_home
    - service: switch.turn_on
      entity_id:
        - switch.living_area_fluxer
        - switch.bedroom_fluxer
        - switch.bathroom_fluxer
    - service: google_assistant.request_sync
