- alias: Home Assistant Start
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: automation.home_assistant_start
      to: 'on'
  action:
    - service: automation.turn_off
      entity_id: automation.home_assistant_start
    - service: logbook.log
      data:
        name: Home Assistant Start
        message: Running...
    - service: automation.turn_off
      entity_id:
        - automation.motion_intruder_alert
        - automation.handle_lights_when_turned_on_not_home
        - automation.notify_doomba_error
    - service: switch.turn_on
      entity_id:
        - switch.living_area_fluxer
        - switch.bedroom_fluxer
        - switch.bedroom_motion
        - switch.closet_fluxer
        - switch.closet_motion
        - switch.bathroom_fluxer
        - switch.bathroom_motion
    - service: logbook.log
      data:
        name: Home Assistant Start
        message: Ran
