- alias: Home Assistant Start
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.jawilson_fluorine_location_update
    - service: script.annekat_reality_location_update
    - service: automation.turn_off
      entity_id:
        - automation.slack_motion_intruder_alert
        - automation.living_area_fluxer
        - automation.bedroom_fluxer
        - automation.bathroom_fluxer
    - service: switch.turn_on
      entity_id:
        - switch.living_area_fluxer
        - switch.bedroom_fluxer
        - switch.bathroom_fluxer
        - switch.cat_water


- alias: Startup Workaround
  initial_state: 'on'
  trigger:
    - platform: time
      seconds: '/5'
  action:
    - service: automation.turn_off
      entity_id: automation.startup_workaround
    - service: automation.trigger
      entity_id: automation.home_assistant_start
    - service: logbook.log
      data:
        name: 'Startup Workaround'
        message: 'Workaround triggered'
