- alias: Run Doomba
  trigger:
    - platform: time
      at: '15:30:00'
    - platform: numeric_state
      entity_id: proximity.home
      above: 500
    - platform: state
      entity_id: group.everyone
      to: 'not_home'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.schedule_vacuum
          state: 'on'
        - condition: and
          conditions:
            - condition: state
              entity_id: vacuum.doomba
              state: 'off'
              # Only run Doomba ounce every 20 hours max
              for:
                hours: 20
            - condition: template
              value_template: >
                {{ (as_timestamp(now()) - (as_timestamp(states.automation.run_doomba.attributes.last_triggered)|float))/60/60 > 20 }}
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform != 'numeric_state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'away_from') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'stationary') }}"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.schedule_vacuum
    - service: vacuum.turn_on
      entity_id: vacuum.doomba


- alias: Dock Doomba when arriving home
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      below: 1000
    - platform: state
      entity_id: group.everyone
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: vacuum.doomba
      state: 'on'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'arrived') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
    - condition: template
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(states.automation.run_doomba.attributes.last_triggered)|float)/60 > 20 }}
  action:
    service: vacuum.turn_off
    entity_id: vacuum.doomba


- alias: Notify Doomba Ran
  trigger:
    platform: state
    entity_id: vacuum.doomba
  condition:
    - condition: template
      value_template: "{{ not is_state('person.jeff', 'home') }}"
    - condition: template
      value_template: >
        {{ trigger.from_state.attributes.status|lower in ['new mission', 'running', 'user docking', 'docking', 'docking - end mission'] and trigger.to_state.attributes.status|lower in ['charging', 'recharging', 'stuck', 'cancelled', 'stopped', 'paused', 'user docking', 'docking - end mission', 'end mission'] }}
  action:
    - service: notify.html5_jawilson_phone
      data_template:
        title: 'Doomba Stopped'
        message: >
          Doomba has stopped {{ trigger.from_state.attributes.status|lower }} and is now {{ states[trigger.to_state.domain][trigger.to_state.object_id].attributes.status|lower }}
        data:
          tag: 'doomba'
          vibrate: [0]
    - condition: template
      value_template: "{{ is_state_attr('vacuum.doomba', 'status', 'Charging') }}"
    - service: automation.turn_on
      entity_id: automation.notify_empty_doomba_bin


- alias: Notify Doomba Not Docked
  trigger:
    platform: state
    entity_id:
      - person.jeff
      - person.sasha
    to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: "{{ not is_state_attr('vacuum.doomba', 'status', 'Charging') }}"
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ is_state_attr('vacuum.doomba', 'status', 'Stuck') }}"
        - condition: and
          conditions:
            - condition: template
              value_template: "{{ state_attr('vacuum.doomba', 'status')|lower in ['user docking', 'docking - end mission'] }}"
            - condition: template
              value_template: "{{ is_state_attr('vacuum.doomba', 'battery_level', 0) }}"
  action:
    service_template: >-
      {% if trigger.entity_id == 'person.sasha' -%}
      notify.ios_sashag_phone
      {%- else -%}
      notify.html5_jawilson_phone
      {%- endif %}
    data:
      title: Doomba Not Docked
      message: Welcome home, it looks like Doomba isn't docked and charging. Can you help it out?


- alias: Notify Empty Doomba Bin
  trigger:
    platform: state
    entity_id:
      - person.jeff
      - person.sasha
    to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: "{{ is_state_attr('vacuum.doomba', 'status', 'Charging') }}"
  action:
    - service_template: >-
        {% if trigger.entity_id == 'person.sasha' -%}
        notify.ios_sashag_phone
        {%- else -%}
        notify.html5_jawilson_phone
        {%- endif %}
      data:
        title: Doomba Ran Today
        message: Welcome home, Doomba did its duty today, can you please empty its bin?
    - service: automation.turn_off
      entity_id: automation.notify_empty_doomba_bin


- alias: Notify Doomba Error
  trigger:
    platform: state
    entity_id: vacuum.doomba
  condition:
    - condition: template
      value_template: "{{ not is_state('person.jeff', 'home') }}"
    - condition: template
      value_template: "{{ 'error' in trigger.to_state.attributes }}"
  action:
    - service: notify.html5
      data_template:
        title: 'Doomba Error!'
        message: "Doomba encountered error: {{ trigger.to_state.attributes.error }}"
