- alias: Run Doomba
  id: run_doomba
  trigger:
    - platform: time
      at: '15:30:00'
    - platform: template
      value_template: "{{ states('proximity.home')|int(0) > 500 }}"
    - platform: state
      entity_id: binary_sensor.presume_home
      to: 'off'
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
    - alias: Run requested or needs to run
      condition: or
      conditions:
        - alias: Run requested
          condition: state
          entity_id: input_boolean.schedule_vacuum
          state: 'on'
        - alias: Needs to run
          condition: and
          conditions:
            - alias: Docked for 20 hours
              condition: state
              entity_id: vacuum.doomba
              state: 'docked'
              for:
                hours: 20
            - alias: Last triggered more than 20 hours
              condition: template
              value_template: >
                {{ (as_timestamp(now()) - (as_timestamp(state_attr('automation.run_doomba', 'last_triggered'))|float))/60/60 > 20 }}
    - condition: or
      conditions:
        - alias: Not triggered by proximity
          condition: template
          value_template: "{{ trigger.platform != 'numeric_state' }}"
        - alias: Not coming home
          condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'away_from') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'stationary') }}"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.schedule_vacuum
    - service: vacuum.start
      target:
        entity_id: vacuum.doomba


- alias: Dock Doomba when arriving home
  id: dock_doomba_when_arriving_home
  trigger:
    - platform: template
      value_template: "{{ states('proximity.home')|int(1000) < 1000 }}"
    - platform: state
      entity_id: binary_sensor.presume_home
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: vacuum.doomba
      state: 'on'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'arrived') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
    - condition: template
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(states.automation.run_doomba.attributes.last_triggered)|float)/60 > 20 }}
  action:
    service: vacuum.return_to_base
    entity_id: vacuum.doomba


- alias: Notify Doomba Ran
  id: notify_doomba_ran
  trigger:
    platform: state
    entity_id: vacuum.doomba
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state.attributes.status|lower in ['new mission', 'running', 'user docking', 'docking', 'docking - end mission'] and trigger.to_state.attributes.status|lower in ['charging', 'recharging', 'stuck', 'cancelled', 'stopped', 'paused', 'user docking', 'docking - end mission', 'end mission'] }}
  action:
    - service: notify.jeff_phone
      data_template:
        title: 'Doomba Stopped'
        message: >
          Doomba has stopped {{ trigger.from_state.attributes.status|lower }} and is now {{ states[trigger.to_state.domain][trigger.to_state.object_id].attributes.status|lower }}
        data:
          apns_headers:
            'apns-collapse-id': 'doomba'
          tag: 'doomba'
          group: Vacuum
    - condition: template
      value_template: "{{ is_state_attr('vacuum.doomba', 'status', 'Charging') }}"
    - service: automation.turn_on
      entity_id: automation.doomba_notify_empty_bin


- alias: Notify Doomba Not Docked
  id: notify_doomba_not_docked
  trigger:
    platform: state
    entity_id:
      - person.jeff
      - person.sasha
    to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: "{{ not is_state_attr('vacuum.doomba', 'status', 'Charging') }}"
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ is_state_attr('vacuum.doomba', 'status', 'Stuck') }}"
        - condition: and
          conditions:
            - condition: template
              value_template: "{{ state_attr('vacuum.doomba', 'status')|lower in ['user docking', 'docking - end mission'] }}"
            - condition: template
              value_template: "{{ is_state_attr('vacuum.doomba', 'battery_level', 0) }}"
  action:
    service_template: >-
      {% if trigger.entity_id == 'person.sasha' -%}
      notify.sasha_phone
      {%- else -%}
      notify.jeff_phone
      {%- endif %}
    data:
      title: Doomba Not Docked
      message: Welcome home, it looks like Doomba isn't docked and charging. Can you help it out?


- alias: Doomba Notify Empty Bin
  id: doomba_notify_empty_bin
  trigger:
    platform: state
    entity_id:
      - person.jeff
      - person.sasha
    to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: template
      value_template: "{{ is_state_attr('vacuum.doomba', 'status', 'Charging') }}"
  action:
    - service_template: >-
        {% if (trigger != null and trigger.entity_id == 'person.sasha') -%}
        notify.sasha_phone
        {%- else -%}
        notify.jeff_phone
        {%- endif %}
      data:
        title: Doomba Ran Today
        message: Welcome home, Doomba did its duty today, can you please empty its bin?
        data:
          tag: 'doomba-bin'
          group: Vacuum
          apns_headers:
            'apns-collapse-id': 'doomba-bin'
          renotify: false
          actions:
            - action: 'ok'
              title: 'Ok'
            - action: 'nope'
              title: 'Nope'
          push:
            category: 'ok_nope'
            thread-id: 'doomba'
            action_data:
              tag: 'doomba-bin'


- alias: Doomba Bin Emptied
  id: doomba_bin_emptied
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: 'ok'
        tag: 'doomba-bin'
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'OK'
        action_data:
          tag: 'doomba-bin'
  action:
    - service: automation.turn_off
      entity_id: automation.doomba_notify_empty_bin
    - service: notify.family_phones
      data:
        message: clear_notification
        data:
          tag: 'doomba-bin'
          group: Vacuum


- alias: Notify Doomba Error
  id: notify_doomba_error
  initial_state: false
  trigger:
    platform: state
    entity_id: vacuum.doomba
  condition:
    - condition: template
      value_template: "{{ not is_state('person.jeff', 'home') }}"
    - condition: template
      value_template: "{{ 'error' in trigger.to_state.attributes }}"
  action:
    - service: notify.jeff
      data_template:
        title: 'Doomba Error!'
        message: "Doomba encountered error: {{ trigger.to_state.attributes.error }}"
