- alias: Run Doomba
  trigger:
    - platform: time
      at: '15:30:00'
    - platform: numeric_state
      entity_id: proximity.home
      above: 500
    - platform: state
      entity_id: group.everyone
      to: 'not_home'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: binary_sensor.presume_home
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.schedule_vacuum
          state: 'on'
        - condition: and
          conditions:
            - condition: state
              entity_id: vacuum.doomba
              state: 'off'
              # Only run Doomba ounce every 40 hours max
              for:
                hours: 40
            - condition: template
              value_template: >
                {{ (as_timestamp(now()) - (as_timestamp(states.automation.run_doomba.attributes.last_triggered)|float))/60/60 > 40 }}
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform != 'numeric_state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'away_from') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'stationary') }}"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.schedule_vacuum
    - service: vacuum.turn_on
      entity_id: vacuum.doomba


- alias: Dock Doomba when arriving home
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      below: 1000
    - platform: state
      entity_id: group.everyone
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.presence
      state: 'on'
    - condition: state
      entity_id: vacuum.doomba
      state: 'on'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'arrived') }}"
            - condition: template
              value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
    - condition: template
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(states.automation.run_doomba.attributes.last_triggered)|float)/60 > 10 }}
  action:
    service: vacuum.turn_off
    entity_id: vacuum.doomba


- alias: Notify Roomba Ran
  trigger:
    platform: state
    entity_id: vacuum.doomba
  condition:
    - condition: state
      entity_id: binary_sensor.jeff_home
      state: 'off'
    - condition: template
      value_template: >
        {{ trigger.from_state.attributes.status|lower in ['new mission', 'running', 'user docking', 'docking', 'docking - end mission'] and trigger.to_state.attributes.status|lower in ['charging', 'recharging', 'stuck', 'cancelled', 'stopped', 'paused', 'end mission'] }}
  action:
    - service: notify.html5
      data_template:
        title: 'Doomba Stopped'
        message: >
          Doomba has stopped {{ trigger.from_state.attributes.status }} and is now {{ states[trigger.to_state.domain][trigger.to_state.object_id].attributes.status|lower }}


- alias: Notify Roomba Error
  trigger:
    platform: state
    entity_id: vacuum.doomba
  condition:
    - condition: state
      entity_id: binary_sensor.jeff_home
      state: 'off'
    - condition: template
      value_template: "{{ 'error' in trigger.to_state.attributes }}"
  action:
    - service: notify.html5
      data_template:
        title: 'Doomba Error!'
        message: "Doomba encountered error: {{ trigger.to_state.attributes.error }}"
