- alias: Handle lights when leaving
  trigger:
    platform: state
    entity_id: group.all_devices
    state: 'not_home'
  condition:
    - condition: state
      entity_id: switch.guests
      state: 'off'
    - condition: state
      entity_id: switch.presence
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.all_lights


- alias: Nest away
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      above: 0
    - platform: template
      value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'away_from') }}"
  condition:
    - condition: state
      entity_id: switch.presence
      state: 'on'
    - condition: state
      entity_id: switch.guests
      state: 'off'
    - condition: template
      value_template: "{{ distance(closest('group.family')) > 400 }}"
  action:
    service: homeassistant.turn_off
    entity_id: switch.apartment_home
