- alias: Handle lights when arriving home
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'home'
  condition:
    - condition: state
      entity_id: group.sleeping
      state: 'off'
    - condition: state
      entity_id: switch.presence
      state: 'on'
  action:
    - service: light.turn_on
      entity_id:
        - light.entryway
        - light.kitchen
        - group.bedroom
      data:
        transition: 30
    - condition: sun
      after: sunset
      after_offset: '-1:00:00'
    - service: light.turn_on
      entity_id: group.living_room_lamp
      data:
        transition: 15
        profile: bright


- alias: Nest home
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      below: 500
    - platform: state
      entity_id: group.all_devices
      state: 'home'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: switch.presence
      state: 'on'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'arrived') }}"
        - condition: template
          value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
  action:
    service: homeassistant.turn_on
    entity_id: switch.apartment_home


- alias: Nest while home
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('thermostat.apartment', 'away_mode', 'on') }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: state
        entity_id: input_boolean.thermostat_auto
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.apartment_home


- alias: Stop circulating
  trigger:
    - platform: state
      entity_id: switch.apartment_home
      state: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.thermostat_auto
      state: 'on'
  action:
    service: script.turn_off
    entity_id: script.cycle_air
