- alias: Handle lights when arriving home
  trigger:
    - platform: state
      entity_id: group.family
      state: 'home'
  condition:
    - condition: state
      entity_id: group.sleeping
      state: 'off'
    - condition: state
      entity_id: switch.presence
      state: 'on'
  action:
    - service: light.turn_on
      entity_id:
        - light.entryway
        - light.kitchen
      data:
        transition: 15
    - service: homeassistant.turn_on
      entity_id: light.bedroom
    - condition: sun
      after: sunset
      after_offset: '-1:00:00'
    - service: light.turn_on
      entity_id:
        - light.living_room_lamp_1
        - light.living_room_lamp_2
      data:
        transition: 15


- alias: Nest home
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'arrived') }}"
    - platform: template
      value_template: "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
  condition:
    - condition: state
      entity_id: switch.presence
      state: 'on'
    - condition: template
      value_template: "{{ distance(closest('group.family')) < 300 }}"
  action:
    service: homeassistant.turn_on
    entity_id: switch.apartment_home



- alias: Nest while home
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('thermostat.apartment', 'away_mode', 'on') }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: input_boolean.thermostat_auto
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.apartment_home
