- alias: 'Living Room Media Players Playing'
  trigger:
    - platform: state
      entity_id:
        - media_player.blue
        - media_player.living_room
      to: 'playing'
  action:
    service: light.turn_off
    entity_id:
      - group.kitchen
      - light.dining
      - group.bedroom
      - group.entryway
    data:
      transition: 15
