- platform: trend
  sensors:
    showering:
      friendly_name: Showering
      entity_id: sensor.bathroom_relative_humidity
      device_class: moisture
      max_samples: 10
      sample_duration: 900
      min_gradient: 0.009
    bathroom_temp_trend:
      friendly_name: Bathroom Temperature Trend
      entity_id: sensor.bathroom_temperature
      device_class: heat
      sample_duration: 900
