- platform: nest

- platform: trend
  sensors:
    bathroom_humidity_trend:
      friendly_name: Bathroom Humidity Trend
      entity_id: sensor.bedroom_relative_humidity
      device_class: moisture
    bathroom_temp_trend:
      friendly_name: Bathroom Temperature Trend
      entity_id: sensor.bedroom_temperature
      device_class: heat

- platform: template
  sensors:
    showering:
      friendly_name: 'Showering'
      device_class: moisture
      value_template: >-
        {{ states('sensor.bathroom_temperature')|float > 73 }}
