- platform: nest
  monitored_conditions:
    - 'fan'
    - 'hvac_ac_state'
    - 'hvac_aux_heater_state'
    - 'hvac_heat_x2_state'
    - 'hvac_heat_x3_state'
    - 'hvac_alt_heat_state'
    - 'hvac_alt_heat_x2_state'
    - 'hvac_emer_heat_state'
