# Jeff

- platform: mqtt
  state_topic: 'person/jeff/sleeping'
  name: 'Jeff Sleeping'
  qos: 1
  payload_on: 'yes'
  payload_off: 'no'

- platform: template
  sensors:
    jeff_home:
      friendly_name: 'Jeff is at Home'
      value_template: >-
        {{ is_state('device_tracker.jawilson_phosphorus', 'home') }}
    jeff_sleeping_at_home:
      friendly_name: 'Jeff Sleeping at Home'
      value_template: >-
        {{ is_state('binary_sensor.jeff_home', 'on')
            and is_state('binary_sensor.jeff_sleeping', 'on') }}


# All

- platform: template
  sensors:
    guests:
      friendly_name: 'Guests Visiting'
      value_template: >-
        {{ is_state('input_boolean.guests', 'on') or is_state('group.guests', 'home') }}
    presume_home:
      friendly_name: 'Someone presumed home'
      value_template: >-
        {{ is_state('input_boolean.guests', 'on') or is_state('group.everyone', 'home') }}
