# Jeff

- platform: mqtt
  state_topic: 'person/jeff/sleeping'
  name: 'Jeff Sleeping'
  qos: 1
  payload_on: 'yes'
  payload_off: 'no'

- platform: template
  sensors:
    jeff_sleeping_at_home:
      friendly_name: 'Jeff Sleeping at Home'
      value_template: >-
        {{ is_state('device_tracker.jawilson_fluorine', 'home')
            and is_state('binary_sensor.jeff_sleeping', 'on') }}


# AK

- platform: mqtt
  state_topic: 'person/ak/sleeping'
  name: 'AK Sleeping'
  qos: 1
  payload_on: 'yes'
  payload_off: 'no'

- platform: template
  sensors:
    ak_sleeping_at_home:
      friendly_name: 'AK Sleeping at Home'
      value_template: >-
        {{ is_state('device_tracker.annekat_reality', 'home')
            and is_state('binary_sensor.ak_sleeping', 'on') }}


# All

- platform: template
  sensors:
    guests:
      friendly_name: 'Guests Visiting'
      value_template: >-
        {{ is_state('input_boolean.guests', 'on') or is_state('group.guests', 'home') }}
    sleeping_at_home:
      friendly_name: 'Sleeping at Home'
      value_template: >-
        {{ is_state('binary_sensor.jeff_sleeping_at_home', 'on')
            or is_state('binary_sensor.ak_sleeping_at_home', 'on') }}
