# Jeff

- platform: template
  sensors:
    jeff_sleeping_at_home:
      friendly_name: 'Jeff Sleeping at Home'
      value_template: >-
        {{ is_state('person.jeff', 'home') and is_state('binary_sensor.jeff_sleeping', 'on') }}

    jeff_sleeping_at_whitneys:
      friendly_name: "Jeff Sleeping at Whitney's"
      value_template: >-
        {{ is_state('person.jeff', 'Whitney\'s') and is_state('binary_sensor.jeff_sleeping', 'on') }}

    jeff_sleeping_at_home_alone:
      friendly_name: 'Jeff Sleeping at Home Alone'
      value_template: >-
        {{ is_state('binary_sensor.jeff_sleeping_at_home', 'on') and not is_state('group.partners', 'home') }}

    whitney_sleeping_over:
      friendly_name: 'Whitney Sleeping Over'
      value_template: >-
        {{ is_state('binary_sensor.jeff_sleeping_at_home', 'on') and is_state('person.whitney', 'home') }}



# All

- platform: template
  sensors:
    guests:
      friendly_name: 'Guests Visiting'
      device_class: 'presence'
      value_template: |
        {{
          is_state('input_boolean.guests', 'on') or
          (states.device_tracker
            | rejectattr('name','match',
                '(' + expand('person.jeff', 'person.crosstrek', 'group.partners')
                  |map(attribute='attributes.friendly_name')
                  |map('regex_replace', ' .*', '')
                  |join('|') + ')')
            | selectattr('state', 'eq', 'home') | list | count > 0)
        }}
    presume_home:
      friendly_name: 'Someone presumed in home region'
      device_class: 'presence'
      value_template: >-
        {{ is_state('input_boolean.guests', 'on')
            or (states.device_tracker | rejectattr('name', 'match', 'Crosstrek') | selectattr('state', 'eq', 'home') | list | count > 0) }}
    apartment_occupied:
      friendly_name: 'Apartment is occupied'
      device_class: 'presence'
      value_template: >-
        {{ is_state('binary_sensor.guests', 'on') or is_state('device_tracker.jawilson_phone', 'home')
            or is_state('group.partner_phones', 'home') }}
