# Jeff

- platform: template
  sensors:
    jeff_home:
      friendly_name: 'Jeff is at Home'
      device_class: 'presence'
      value_template: >-
        {{ is_state('device_tracker.jawilson_phosphorus', 'home') }}
    jeff_sleeping_at_home:
      friendly_name: 'Jeff Sleeping at Home'
      value_template: >-
        {{ is_state('binary_sensor.jeff_home', 'on')
            and is_state_attr('sensor.jeff_alarm', 'sleep_state', 'sleeping') }}
    sasha_home:
      friendly_name: 'Sasha is at Home'
      device_class: 'presence'
      value_template: >-
        {{ is_state('device_tracker.sashag_iphone', 'home') }}


# All

- platform: template
  sensors:
    guests:
      friendly_name: 'Guests Visiting'
      device_class: 'presence'
      value_template: >-
        {{ is_state('input_boolean.guests', 'on') or is_state('group.guests', 'home') }}
    presume_home:
      friendly_name: 'Someone presumed home'
      device_class: 'presence'
      value_template: >-
        {{ is_state('input_boolean.guests', 'on') or is_state('group.everyone', 'home') }}
