# Jeff

- platform: template
  sensors:
    jeff_sleeping_at_home:
      friendly_name: 'Jeff Sleeping at Home'
      value_template: >-
        {{ is_state('person.jeff', 'home')
            and is_state_attr('sensor.jeff_alarm', 'sleep_state', 'sleeping') }}


# All

- platform: template
  sensors:
    guests:
      friendly_name: 'Guests Visiting'
      device_class: 'presence'
      value_template: >-
        {{ is_state('input_boolean.guests', 'on') or is_state('group.guests', 'home') }}
    presume_home:
      friendly_name: 'Someone presumed home'
      device_class: 'presence'
      value_template: >-
        {{ is_state('input_boolean.guests', 'on') or is_state('group.everyone', 'home') }}

- platform: workday
  country: US
