- platform: template
  switches:
    bedroom_motion:
      friendly_name: Bedroom Motion Automations
      value_template: >
        {{is_state('automation.bedroom_motion', 'on')}}
      turn_on:
        service: automation.turn_on
        entity_id:
          - automation.bedroom_motion
      turn_off:
        service: automation.turn_off
        entity_id:
          - automation.bedroom_motion
    closet_motion:
      friendly_name: Closet Motion Automations
      value_template: >
        {{is_state('automation.closet_motion', 'on')}}
      turn_on:
        service: automation.turn_on
        entity_id: automation.closet_motion
      turn_off:
        service: automation.turn_off
        entity_id: automation.closet_motion
    bathroom_motion:
      friendly_name: Bathroom Motion Automations
      value_template: >
        {{is_state('automation.bathroom_motion', 'on')}}
      turn_on:
        service: automation.turn_on
        entity_id:
          - automation.bathroom_motion
      turn_off:
        service: automation.turn_off
        entity_id:
          - automation.bathroom_motion
