- platform: template
  switches:
    apartment_fan:
      friendly_name: 'HVAC Fan'
      unique_id: 'hvac_fan_switch'
      value_template: "{{ is_state_attr('climate.apartment', 'fan_mode', 'on') }}"
      turn_on:
        - service: climate.set_fan_mode
          entity_id: climate.apartment
          data:
            fan_mode: 'on'
        - delay: 00:15
        - service: climate.set_fan_mode
          entity_id: climate.apartment
          data:
            fan_mode: 'off'
      turn_off:
        service: climate.set_fan_mode
        entity_id: climate.apartment
        data:
          fan_mode: 'off'

- platform: template
  switches:
    apartment_home:
      friendly_name: 'Home'
      unique_id: 'hvac_home_switch'
      value_template: "{{ is_state_attr('climate.apartment', 'preset_mode', 'none') }}"
      turn_on:
        - enabled: false
          service: climate.set_preset_mode
          target:
            entity_id: climate.apartment
          data:
            preset_mode: none
        - service: google_assistant_sdk.send_text_command
          data:
            command: set apartment thermostat to heat/cool
      turn_off:
        - enabled: false
          service: climate.set_preset_mode
          target:
            entity_id: climate.apartment
          data:
            preset_mode: eco
        - service: google_assistant_sdk.send_text_command
          data:
            command: set apartment thermostat to eco
