- platform: template
  switches:
    apartment_fan:
      friendly_name: 'HVAC Fan'
      value_template: "{{ is_state_attr('climate.apartment', 'fan_mode', 'on') }}"
      turn_on:
        - service: climate.set_fan_mode
          entity_id: climate.apartment
          data:
            fan_mode: 'on'
        - delay: 00:15
        - service: climate.set_fan_mode
          entity_id: climate.apartment
          data:
            fan_mode: 'auto'
      turn_off:
        service: climate.set_fan_mode
        entity_id: climate.apartment
        data:
          fan_mode: 'auto'

- platform: template
  switches:
    apartment_home:
      friendly_name: 'Home'
      value_template: "{{ state_attr('climate.apartment', 'preset_mode') not in ['away', 'Away and Eco'] }}"
      turn_on:
        service: nest.set_away_mode
        data:
          away_mode: home
          structure:
            - Meridian
      turn_off:
        service: nest.set_away_mode
        data:
          away_mode: away
          structure:
            - Meridian
