- platform: flux
  lights:
    - light.entryway
    - light.living_room_lamp_1
    - light.living_room_lamp_2
  name: Living Area Fluxer
  start_time: '7:00'
  start_colortemp: 6536

- platform: flux
  lights:
    - light.bedroom_lamp
    - light.tree_lamp_1
    - light.tree_lamp_2
    - light.tree_lamp_3
    - light.tree_lamp_4
    - light.tree_lamp_5
  name: Bedroom Fluxer
  start_time: '7:00'
  start_colortemp: 6536
  mode: mired

- platform: flux
  lights:
    - light.bathroom_mirror_1
    - light.bathroom_mirror_2
    - light.bathroom_mirror_3
    - light.bathroom_mirror_4
    - light.bathroom_shower
  name: Bathroom Fluxer
  start_time: '7:00'
  start_colortemp: 5000
  mode: mired
