- platform: flux
  name: Living Area Fluxer
  lights: !include ../fluxer_lights/living_area.yaml
  start_time: '7:00'
  start_colortemp: 6000

- platform: flux
  name: Bedroom Fluxer
  lights: !include ../fluxer_lights/bedroom.yaml
  start_time: '7:00'
  start_colortemp: 5000
  mode: mired

- platform: flux
  lights: !include ../fluxer_lights/bathroom.yaml
  name: Bathroom Fluxer
  start_time: '7:00'
  start_colortemp: 5000
  mode: mired
