- platform: flux
  name: Entryway Fluxer
  lights:
    - light.entryway_lights
  mode: xy

  start_time: '6:00'
  stop_time: '22:00'

  start_colortemp: 5000
  sunset_colortemp: 4000
  stop_colortemp: 1900



- platform: flux
  name: Kitchen Fluxer
  lights:
    - light.kitchen
  mode: xy

  start_time: '6:00'
  stop_time: '22:00'

  start_colortemp: 5000
  sunset_colortemp: 4000
  stop_colortemp: 1900



- platform: flux
  name: Dining Fluxer
  lights:
    - light.dining_lights_level
  mode: xy

  start_time: '6:00'
  stop_time: '22:00'

  start_colortemp: 5000
  sunset_colortemp: 3500
  stop_colortemp: 1000



- platform: flux
  name: Living Room Fluxer
  lights:
    - light.entertainment_lights
  mode: xy

  start_time: '6:00'
  stop_time: '22:00'

  start_colortemp: 5000
  sunset_colortemp: 3500
  stop_colortemp: 1900


- platform: flux
  name: Tree Lamp Fluxer
  lights:
    - light.tree_lamp
  mode: mired

  start_time: '6:00'
  stop_time: '22:00'

  start_colortemp: 5000
  sunset_colortemp: 3000
  stop_colortemp: 1900



- platform: flux
  name: Sunroom Fluxer
  lights:
    - light.sunroom_lights
  mode: xy

  start_time: '6:00'
  stop_time: '22:00'

  start_colortemp: 5000
  sunset_colortemp: 3500
  stop_colortemp: 1900



- platform: template
  switches:
    living_area_fluxer:
      friendly_name: Living Area Fluxer
      value_template: >-
        {{ is_state('switch.entryway_fluxer', 'on') and
          is_state('switch.kitchen_fluxer', 'on') and
          is_state('switch.dining_fluxer', 'on') and
          is_state('switch.tree_lamp_fluxer', 'on') and
          is_state('switch.living_room_fluxer', 'on') and
          is_state('switch.sunroom_fluxer', 'on') }}
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.entryway_fluxer
          - switch.kitchen_fluxer
          - switch.dining_fluxer
          - switch.tree_lamp_fluxer
          - switch.living_room_fluxer
          - switch.sunroom_fluxer
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.entryway_fluxer
          - switch.kitchen_fluxer
          - switch.dining_fluxer
          - switch.tree_lamp_fluxer
          - switch.living_room_fluxer
          - switch.sunroom_fluxer



- platform: flux
  name: Bedroom Fluxer
  lights:
    - light.bedroom_lights
  mode: mired

  start_time: '6:00'
  stop_time: '22:00'

  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1700



- platform: flux
  name: Closet Fluxer
  lights:
    - light.closet_lights
  mode: mired

  start_time: '6:00'
  stop_time: '22:00'

  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900



- platform: flux
  name: Bathroom Fluxer
  lights:
    - light.bathroom_lights
  mode: mired

  start_time: '6:00'
  stop_time: '22:00'

  start_colortemp: 3500
  sunset_colortemp: 3000
  stop_colortemp: 1900
