- platform: mqtt
  name: 'Projector'
  state_topic: 'home/harmony/hubs/living-room/state'
  command_topic: 'home/harmony/hubs/living-room/activities/play-shield/command'
  qos: 0
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  name: 'Xbox'
  state_topic: 'home/harmony/hubs/living-room/activities/play-xbox-s/state'
  command_topic: 'home/harmony/hubs/living-room/activities/play-xbox-s/command'
  qos: 0
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  name: 'Wii'
  state_topic: 'home/harmony/hubs/living-room/activities/play-wii/state'
  command_topic: 'home/harmony/hubs/living-room/activities/play-wii/command'
  qos: 0
  payload_on: 'on'
  payload_off: 'off'
