- platform: template
  switches:
    projector:
      friendly_name: 'Projector'
      value_template: "{{ is_state('remote.living_room', 'on') }}"
      turn_on:
        - condition: state
          entity_id: remote.living_room
          state: 'off'
        - service: remote.turn_on
          entity_id: remote.living_room
          data:
            activity: 'Play Shield'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    shield:
      friendly_name: 'SHIELD'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play Shield') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
        data:
          activity: 'Play Shield'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    plex:
      friendly_name: 'Plex'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play Shield') }}"
      turn_on:
        - service: remote.turn_on
          entity_id: remote.living_room
          data:
            activity: 'Play Shield'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    netflix:
      friendly_name: 'Netflix'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play Shield') }}"
      turn_on:
        - service: remote.turn_on
          entity_id: remote.living_room
          data:
            activity: 'Play Shield'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    xbox_one:
      friendly_name: 'Xbox One'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play Xbox One') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
        data:
          activity: 'Play Xbox One'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    xbox_360:
      friendly_name: 'Xbox 360'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play Xbox 360') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
        data:
          activity: 'Play Xbox 360'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
