- platform: template
  switches:
    projector:
      friendly_name: 'Projector'
      value_template: "{{ is_state('remote.living_room', 'on') }}"
      turn_on:
        - service: remote.send_command
          entity_id: remote.living_room
          data:
            device: Projector
            command: PowerOn
        - condition: state
          entity_id: remote.living_room
          state: 'off'
        - service: remote.turn_on
          entity_id: remote.living_room
          data:
            activity: 'Play Shield'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
