- platform: mqtt
  name: 'Projector'
  state_topic: 'home/livingroom/harmony/state'
  command_topic: 'home/livingroom/harmony/activities/play-shield/command'
  qos: 0
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  name: 'Plex'
  state_topic: 'home/livingroom/harmony/activities/watch-plex/state'
  command_topic: 'home/livingroom/harmony/activities/watch-plex/command'
  qos: 0
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  name: 'Xbox'
  state_topic: 'home/livingroom/harmony/activities/play-xbox-s/state'
  command_topic: 'home/livingroom/harmony/activities/play-xbox-s/command'
  qos: 0
  payload_on: 'on'
  payload_off: 'off'

- platform: mqtt
  name: 'Wii'
  state_topic: 'home/livingroom/harmony/activities/play-wii/state'
  command_topic: 'home/livingroom/harmony/activities/play-wii/command'
  qos: 0
  payload_on: 'on'
  payload_off: 'off'
