- platform: template
  switches:
    plex:
      friendly_name: 'Plex'
      unique_id: 'shield_plex_switch'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play Shield') and is_state_attr('media_player.androidtv_shield', 'source', 'Plex') }}"
      turn_on:
        - service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Play Shield'
        - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play Shield') and not is_state('media_player.androidtv_shield', 'off') }}"
        - service: media_player.select_source
          data:
            entity_id: media_player.androidtv_shield
            source: 'Plex'
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room