- platform: orvibo
  discovery: false
  switches:
  - host: 192.168.0.55
    mac: 'AC:CF:23:92:F4:98'
    name: 'Orvibo1'
  - host: 192.168.0.56
    mac: 'AC:CF:23:8D:35:F8'
    name: 'Orvibo2'

- platform: template
  switches:
    crockpot:
      friendly_name: 'Crockpot'
      value_template: "{{ is_state('input_select.orvibo1', 'Crockpot') and is_state('switch.orvibo1', 'on') }}"
      turn_on:
        - condition: state
          entity_id: 'input_select.orvibo1'
          state: 'Crockpot'
        - service: switch.turn_on
          entity_id: switch.orvibo1
      turn_off:
        - condition: state
          entity_id: 'input_select.orvibo1'
          state: 'Crockpot'
        - service: switch.turn_off
          entity_id: switch.orvibo1
    christmas_tree:
      friendly_name: Christmas Tree
      value_template: "{{ is_state('input_select.orvibo1', 'Christmas Tree') and is_state('switch.orvibo1', 'on') }}"
      turn_on:
        - condition: state
          entity_id: 'input_select.orvibo1'
          state: 'Christmas Tree'
        - service: switch.turn_on
          entity_id: switch.orvibo1
      turn_off:
        - condition: state
          entity_id: 'input_select.orvibo1'
          state: 'Christmas Tree'
        - service: switch.turn_off
          entity_id: switch.orvibo1
    cat_water:
      friendly_name: 'Cat Water'
      value_template: "{{ is_state('input_select.orvibo1', 'Cat Water') and is_state('switch.orvibo1', 'on') }}"
      turn_on:
        - condition: state
          entity_id: 'input_select.orvibo1'
          state: 'Cat Water'
        - service: switch.turn_on
          entity_id: switch.orvibo1
      turn_off:
        - condition: state
          entity_id: 'input_select.orvibo1'
          state: 'Cat Water'
        - service: switch.turn_off
          entity_id: switch.orvibo1

- platform: template
  switches:
    humidifier:
      friendly_name: Humidifier
      value_template: "{{ is_state('input_select.orvibo2', 'Humidifier') and is_state('switch.orvibo2', 'on') }}"
      turn_on:
        - condition: state
          entity_id: 'input_select.orvibo2'
          state: 'Humidifier'
        - service: switch.turn_on
          entity_id: switch.orvibo2
      turn_off:
        - condition: state
          entity_id: 'input_select.orvibo2'
          state: 'Humidifier'
        - service: switch.turn_off
          entity_id: switch.orvibo2
