- platform: orvibo
  discovery: false
  switches:
    - host: 192.168.0.56
      mac: 'AC:CF:23:8D:35:F8'
      name: 'Orvibo2'

- platform: template
  switches:
    humidifier:
      friendly_name: Humidifier
      value_template: "{{ is_state('input_select.orvibo2', 'Humidifier') and is_state('switch.orvibo2', 'on') }}"
      turn_on:
        - condition: state
          entity_id: 'input_select.orvibo2'
          state: 'Humidifier'
        - service: switch.turn_on
          entity_id: switch.orvibo2
      turn_off:
        - condition: state
          entity_id: 'input_select.orvibo2'
          state: 'Humidifier'
        - service: switch.turn_off
          entity_id: switch.orvibo2
