esphome:
  name: vindriktning-2
  friendly_name: Vindriktning

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "69n8sF8uBhn7BAMWRCCAg5udjQHDcZseXF5VCfEqW8o="

ota:
  password: "18d506f140119f56b992d502df0c149f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vindriktning-2 Fallback Hotspot"
    password: "9afDuh8AHedk"

captive_portal:

uart:
  rx_pin: D5
  baud_rate: 9600
  id: pm1006_uart

i2c:
  sda: D2
  scl: D1
  scan: False

bme680_bsec:
    address: 0x77

binary_sensor:
  - platform: gpio
    pin: D6
    name: Motion
    device_class: motion

output:
  - platform: esp8266_pwm
    pin: D7
    id: gpio_d7

number:
  - platform: template
    name: "Motion Sensitivity"
    optimistic: true
    min_value: 0
    max_value: 31
    step: 1
    restore_value: true
    set_action:
      - output.set_level:
          id: gpio_d7
          level: !lambda return (63 - x*2)/128;
  
sensor:
  - platform: pm1006
    uart_id: pm1006_uart
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    iaq:
      name: "BME680 IAQ"
      id: iaq
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"

  - platform: template
    name: "BME680 IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }
    